package com.google.android.gms.internal.mlkit_vision_common;

import rv.b;
import rv.c;
import rv.d;

/* JADX INFO: loaded from: classes5.dex */
final class zzeo implements c {
    private static final b zzA;
    private static final b zzB;
    private static final b zzC;
    private static final b zzD;
    private static final b zzE;
    private static final b zzF;
    private static final b zzG;
    private static final b zzH;
    private static final b zzI;
    private static final b zzJ;
    private static final b zzK;
    private static final b zzL;
    private static final b zzM;
    private static final b zzN;
    private static final b zzO;
    private static final b zzP;
    private static final b zzQ;
    private static final b zzR;
    private static final b zzS;
    private static final b zzT;
    private static final b zzU;
    private static final b zzV;
    private static final b zzW;
    private static final b zzX;
    private static final b zzY;
    private static final b zzZ;
    static final zzeo zza = new zzeo();
    private static final b zzaA;
    private static final b zzaB;
    private static final b zzaC;
    private static final b zzaD;
    private static final b zzaE;
    private static final b zzaF;
    private static final b zzaG;
    private static final b zzaH;
    private static final b zzaI;
    private static final b zzaJ;
    private static final b zzaK;
    private static final b zzaL;
    private static final b zzaM;
    private static final b zzaa;
    private static final b zzab;
    private static final b zzac;
    private static final b zzad;
    private static final b zzae;
    private static final b zzaf;
    private static final b zzag;
    private static final b zzah;
    private static final b zzai;
    private static final b zzaj;
    private static final b zzak;
    private static final b zzal;
    private static final b zzam;
    private static final b zzan;
    private static final b zzao;
    private static final b zzap;
    private static final b zzaq;
    private static final b zzar;
    private static final b zzas;
    private static final b zzat;
    private static final b zzau;
    private static final b zzav;
    private static final b zzaw;
    private static final b zzax;
    private static final b zzay;
    private static final b zzaz;
    private static final b zzb;
    private static final b zzc;
    private static final b zzd;
    private static final b zze;
    private static final b zzf;
    private static final b zzg;
    private static final b zzh;
    private static final b zzi;
    private static final b zzj;
    private static final b zzk;
    private static final b zzl;
    private static final b zzm;
    private static final b zzn;
    private static final b zzo;
    private static final b zzp;
    private static final b zzq;
    private static final b zzr;
    private static final b zzs;
    private static final b zzt;
    private static final b zzu;
    private static final b zzv;
    private static final b zzw;
    private static final b zzx;
    private static final b zzy;
    private static final b zzz;

    static {
        b.C2317b c2317bA = b.a("systemInfo");
        zzae zzaeVar = new zzae();
        zzaeVar.zza(1);
        zzb = c2317bA.b(zzaeVar.zzb()).a();
        b.C2317b c2317bA2 = b.a("eventName");
        zzae zzaeVar2 = new zzae();
        zzaeVar2.zza(2);
        zzc = c2317bA2.b(zzaeVar2.zzb()).a();
        b.C2317b c2317bA3 = b.a("isThickClient");
        zzae zzaeVar3 = new zzae();
        zzaeVar3.zza(37);
        zzd = c2317bA3.b(zzaeVar3.zzb()).a();
        b.C2317b c2317bA4 = b.a("clientType");
        zzae zzaeVar4 = new zzae();
        zzaeVar4.zza(61);
        zze = c2317bA4.b(zzaeVar4.zzb()).a();
        b.C2317b c2317bA5 = b.a("modelDownloadLogEvent");
        zzae zzaeVar5 = new zzae();
        zzaeVar5.zza(3);
        zzf = c2317bA5.b(zzaeVar5.zzb()).a();
        b.C2317b c2317bA6 = b.a("customModelLoadLogEvent");
        zzae zzaeVar6 = new zzae();
        zzaeVar6.zza(20);
        zzg = c2317bA6.b(zzaeVar6.zzb()).a();
        b.C2317b c2317bA7 = b.a("customModelInferenceLogEvent");
        zzae zzaeVar7 = new zzae();
        zzaeVar7.zza(4);
        zzh = c2317bA7.b(zzaeVar7.zzb()).a();
        b.C2317b c2317bA8 = b.a("customModelCreateLogEvent");
        zzae zzaeVar8 = new zzae();
        zzaeVar8.zza(29);
        zzi = c2317bA8.b(zzaeVar8.zzb()).a();
        b.C2317b c2317bA9 = b.a("onDeviceFaceDetectionLogEvent");
        zzae zzaeVar9 = new zzae();
        zzaeVar9.zza(5);
        zzj = c2317bA9.b(zzaeVar9.zzb()).a();
        b.C2317b c2317bA10 = b.a("onDeviceFaceLoadLogEvent");
        zzae zzaeVar10 = new zzae();
        zzaeVar10.zza(59);
        zzk = c2317bA10.b(zzaeVar10.zzb()).a();
        b.C2317b c2317bA11 = b.a("onDeviceTextDetectionLogEvent");
        zzae zzaeVar11 = new zzae();
        zzaeVar11.zza(6);
        zzl = c2317bA11.b(zzaeVar11.zzb()).a();
        b.C2317b c2317bA12 = b.a("onDeviceTextDetectionLoadLogEvent");
        zzae zzaeVar12 = new zzae();
        zzaeVar12.zza(79);
        zzm = c2317bA12.b(zzaeVar12.zzb()).a();
        b.C2317b c2317bA13 = b.a("onDeviceBarcodeDetectionLogEvent");
        zzae zzaeVar13 = new zzae();
        zzaeVar13.zza(7);
        zzn = c2317bA13.b(zzaeVar13.zzb()).a();
        b.C2317b c2317bA14 = b.a("onDeviceBarcodeLoadLogEvent");
        zzae zzaeVar14 = new zzae();
        zzaeVar14.zza(58);
        zzo = c2317bA14.b(zzaeVar14.zzb()).a();
        b.C2317b c2317bA15 = b.a("onDeviceImageLabelCreateLogEvent");
        zzae zzaeVar15 = new zzae();
        zzaeVar15.zza(48);
        zzp = c2317bA15.b(zzaeVar15.zzb()).a();
        b.C2317b c2317bA16 = b.a("onDeviceImageLabelLoadLogEvent");
        zzae zzaeVar16 = new zzae();
        zzaeVar16.zza(49);
        zzq = c2317bA16.b(zzaeVar16.zzb()).a();
        b.C2317b c2317bA17 = b.a("onDeviceImageLabelDetectionLogEvent");
        zzae zzaeVar17 = new zzae();
        zzaeVar17.zza(18);
        zzr = c2317bA17.b(zzaeVar17.zzb()).a();
        b.C2317b c2317bA18 = b.a("onDeviceObjectCreateLogEvent");
        zzae zzaeVar18 = new zzae();
        zzaeVar18.zza(26);
        zzs = c2317bA18.b(zzaeVar18.zzb()).a();
        b.C2317b c2317bA19 = b.a("onDeviceObjectLoadLogEvent");
        zzae zzaeVar19 = new zzae();
        zzaeVar19.zza(27);
        zzt = c2317bA19.b(zzaeVar19.zzb()).a();
        b.C2317b c2317bA20 = b.a("onDeviceObjectInferenceLogEvent");
        zzae zzaeVar20 = new zzae();
        zzaeVar20.zza(28);
        zzu = c2317bA20.b(zzaeVar20.zzb()).a();
        b.C2317b c2317bA21 = b.a("onDevicePoseDetectionLogEvent");
        zzae zzaeVar21 = new zzae();
        zzaeVar21.zza(44);
        zzv = c2317bA21.b(zzaeVar21.zzb()).a();
        b.C2317b c2317bA22 = b.a("onDeviceSegmentationLogEvent");
        zzae zzaeVar22 = new zzae();
        zzaeVar22.zza(45);
        zzw = c2317bA22.b(zzaeVar22.zzb()).a();
        b.C2317b c2317bA23 = b.a("onDeviceSmartReplyLogEvent");
        zzae zzaeVar23 = new zzae();
        zzaeVar23.zza(19);
        zzx = c2317bA23.b(zzaeVar23.zzb()).a();
        b.C2317b c2317bA24 = b.a("onDeviceLanguageIdentificationLogEvent");
        zzae zzaeVar24 = new zzae();
        zzaeVar24.zza(21);
        zzy = c2317bA24.b(zzaeVar24.zzb()).a();
        b.C2317b c2317bA25 = b.a("onDeviceTranslationLogEvent");
        zzae zzaeVar25 = new zzae();
        zzaeVar25.zza(22);
        zzz = c2317bA25.b(zzaeVar25.zzb()).a();
        b.C2317b c2317bA26 = b.a("cloudFaceDetectionLogEvent");
        zzae zzaeVar26 = new zzae();
        zzaeVar26.zza(8);
        zzA = c2317bA26.b(zzaeVar26.zzb()).a();
        b.C2317b c2317bA27 = b.a("cloudCropHintDetectionLogEvent");
        zzae zzaeVar27 = new zzae();
        zzaeVar27.zza(9);
        zzB = c2317bA27.b(zzaeVar27.zzb()).a();
        b.C2317b c2317bA28 = b.a("cloudDocumentTextDetectionLogEvent");
        zzae zzaeVar28 = new zzae();
        zzaeVar28.zza(10);
        zzC = c2317bA28.b(zzaeVar28.zzb()).a();
        b.C2317b c2317bA29 = b.a("cloudImagePropertiesDetectionLogEvent");
        zzae zzaeVar29 = new zzae();
        zzaeVar29.zza(11);
        zzD = c2317bA29.b(zzaeVar29.zzb()).a();
        b.C2317b c2317bA30 = b.a("cloudImageLabelDetectionLogEvent");
        zzae zzaeVar30 = new zzae();
        zzaeVar30.zza(12);
        zzE = c2317bA30.b(zzaeVar30.zzb()).a();
        b.C2317b c2317bA31 = b.a("cloudLandmarkDetectionLogEvent");
        zzae zzaeVar31 = new zzae();
        zzaeVar31.zza(13);
        zzF = c2317bA31.b(zzaeVar31.zzb()).a();
        b.C2317b c2317bA32 = b.a("cloudLogoDetectionLogEvent");
        zzae zzaeVar32 = new zzae();
        zzaeVar32.zza(14);
        zzG = c2317bA32.b(zzaeVar32.zzb()).a();
        b.C2317b c2317bA33 = b.a("cloudSafeSearchDetectionLogEvent");
        zzae zzaeVar33 = new zzae();
        zzaeVar33.zza(15);
        zzH = c2317bA33.b(zzaeVar33.zzb()).a();
        b.C2317b c2317bA34 = b.a("cloudTextDetectionLogEvent");
        zzae zzaeVar34 = new zzae();
        zzaeVar34.zza(16);
        zzI = c2317bA34.b(zzaeVar34.zzb()).a();
        b.C2317b c2317bA35 = b.a("cloudWebSearchDetectionLogEvent");
        zzae zzaeVar35 = new zzae();
        zzaeVar35.zza(17);
        zzJ = c2317bA35.b(zzaeVar35.zzb()).a();
        b.C2317b c2317bA36 = b.a("automlImageLabelingCreateLogEvent");
        zzae zzaeVar36 = new zzae();
        zzaeVar36.zza(23);
        zzK = c2317bA36.b(zzaeVar36.zzb()).a();
        b.C2317b c2317bA37 = b.a("automlImageLabelingLoadLogEvent");
        zzae zzaeVar37 = new zzae();
        zzaeVar37.zza(24);
        zzL = c2317bA37.b(zzaeVar37.zzb()).a();
        b.C2317b c2317bA38 = b.a("automlImageLabelingInferenceLogEvent");
        zzae zzaeVar38 = new zzae();
        zzaeVar38.zza(25);
        zzM = c2317bA38.b(zzaeVar38.zzb()).a();
        b.C2317b c2317bA39 = b.a("isModelDownloadedLogEvent");
        zzae zzaeVar39 = new zzae();
        zzaeVar39.zza(39);
        zzN = c2317bA39.b(zzaeVar39.zzb()).a();
        b.C2317b c2317bA40 = b.a("deleteModelLogEvent");
        zzae zzaeVar40 = new zzae();
        zzaeVar40.zza(40);
        zzO = c2317bA40.b(zzaeVar40.zzb()).a();
        b.C2317b c2317bA41 = b.a("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzae zzaeVar41 = new zzae();
        zzaeVar41.zza(30);
        zzP = c2317bA41.b(zzaeVar41.zzb()).a();
        b.C2317b c2317bA42 = b.a("aggregatedCustomModelInferenceLogEvent");
        zzae zzaeVar42 = new zzae();
        zzaeVar42.zza(31);
        zzQ = c2317bA42.b(zzaeVar42.zzb()).a();
        b.C2317b c2317bA43 = b.a("aggregatedOnDeviceFaceDetectionLogEvent");
        zzae zzaeVar43 = new zzae();
        zzaeVar43.zza(32);
        zzR = c2317bA43.b(zzaeVar43.zzb()).a();
        b.C2317b c2317bA44 = b.a("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzae zzaeVar44 = new zzae();
        zzaeVar44.zza(33);
        zzS = c2317bA44.b(zzaeVar44.zzb()).a();
        b.C2317b c2317bA45 = b.a("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzae zzaeVar45 = new zzae();
        zzaeVar45.zza(34);
        zzT = c2317bA45.b(zzaeVar45.zzb()).a();
        b.C2317b c2317bA46 = b.a("aggregatedOnDeviceObjectInferenceLogEvent");
        zzae zzaeVar46 = new zzae();
        zzaeVar46.zza(35);
        zzU = c2317bA46.b(zzaeVar46.zzb()).a();
        b.C2317b c2317bA47 = b.a("aggregatedOnDeviceTextDetectionLogEvent");
        zzae zzaeVar47 = new zzae();
        zzaeVar47.zza(36);
        zzV = c2317bA47.b(zzaeVar47.zzb()).a();
        b.C2317b c2317bA48 = b.a("aggregatedOnDevicePoseDetectionLogEvent");
        zzae zzaeVar48 = new zzae();
        zzaeVar48.zza(46);
        zzW = c2317bA48.b(zzaeVar48.zzb()).a();
        b.C2317b c2317bA49 = b.a("aggregatedOnDeviceSegmentationLogEvent");
        zzae zzaeVar49 = new zzae();
        zzaeVar49.zza(47);
        zzX = c2317bA49.b(zzaeVar49.zzb()).a();
        b.C2317b c2317bA50 = b.a("pipelineAccelerationInferenceEvents");
        zzae zzaeVar50 = new zzae();
        zzaeVar50.zza(69);
        zzY = c2317bA50.b(zzaeVar50.zzb()).a();
        b.C2317b c2317bA51 = b.a("remoteConfigLogEvent");
        zzae zzaeVar51 = new zzae();
        zzaeVar51.zza(42);
        zzZ = c2317bA51.b(zzaeVar51.zzb()).a();
        b.C2317b c2317bA52 = b.a("inputImageConstructionLogEvent");
        zzae zzaeVar52 = new zzae();
        zzaeVar52.zza(50);
        zzaa = c2317bA52.b(zzaeVar52.zzb()).a();
        b.C2317b c2317bA53 = b.a("leakedHandleEvent");
        zzae zzaeVar53 = new zzae();
        zzaeVar53.zza(51);
        zzab = c2317bA53.b(zzaeVar53.zzb()).a();
        b.C2317b c2317bA54 = b.a("cameraSourceLogEvent");
        zzae zzaeVar54 = new zzae();
        zzaeVar54.zza(52);
        zzac = c2317bA54.b(zzaeVar54.zzb()).a();
        b.C2317b c2317bA55 = b.a("imageLabelOptionalModuleLogEvent");
        zzae zzaeVar55 = new zzae();
        zzaeVar55.zza(53);
        zzad = c2317bA55.b(zzaeVar55.zzb()).a();
        b.C2317b c2317bA56 = b.a("languageIdentificationOptionalModuleLogEvent");
        zzae zzaeVar56 = new zzae();
        zzaeVar56.zza(54);
        zzae = c2317bA56.b(zzaeVar56.zzb()).a();
        b.C2317b c2317bA57 = b.a("faceDetectionOptionalModuleLogEvent");
        zzae zzaeVar57 = new zzae();
        zzaeVar57.zza(60);
        zzaf = c2317bA57.b(zzaeVar57.zzb()).a();
        b.C2317b c2317bA58 = b.a("documentDetectionOptionalModuleLogEvent");
        zzae zzaeVar58 = new zzae();
        zzaeVar58.zza(85);
        zzag = c2317bA58.b(zzaeVar58.zzb()).a();
        b.C2317b c2317bA59 = b.a("documentCroppingOptionalModuleLogEvent");
        zzae zzaeVar59 = new zzae();
        zzaeVar59.zza(86);
        zzah = c2317bA59.b(zzaeVar59.zzb()).a();
        b.C2317b c2317bA60 = b.a("documentEnhancementOptionalModuleLogEvent");
        zzae zzaeVar60 = new zzae();
        zzaeVar60.zza(87);
        zzai = c2317bA60.b(zzaeVar60.zzb()).a();
        b.C2317b c2317bA61 = b.a("nlClassifierOptionalModuleLogEvent");
        zzae zzaeVar61 = new zzae();
        zzaeVar61.zza(55);
        zzaj = c2317bA61.b(zzaeVar61.zzb()).a();
        b.C2317b c2317bA62 = b.a("nlClassifierClientLibraryLogEvent");
        zzae zzaeVar62 = new zzae();
        zzaeVar62.zza(56);
        zzak = c2317bA62.b(zzaeVar62.zzb()).a();
        b.C2317b c2317bA63 = b.a("accelerationAllowlistLogEvent");
        zzae zzaeVar63 = new zzae();
        zzaeVar63.zza(57);
        zzal = c2317bA63.b(zzaeVar63.zzb()).a();
        b.C2317b c2317bA64 = b.a("toxicityDetectionCreateEvent");
        zzae zzaeVar64 = new zzae();
        zzaeVar64.zza(62);
        zzam = c2317bA64.b(zzaeVar64.zzb()).a();
        b.C2317b c2317bA65 = b.a("toxicityDetectionLoadEvent");
        zzae zzaeVar65 = new zzae();
        zzaeVar65.zza(63);
        zzan = c2317bA65.b(zzaeVar65.zzb()).a();
        b.C2317b c2317bA66 = b.a("toxicityDetectionInferenceEvent");
        zzae zzaeVar66 = new zzae();
        zzaeVar66.zza(64);
        zzao = c2317bA66.b(zzaeVar66.zzb()).a();
        b.C2317b c2317bA67 = b.a("barcodeDetectionOptionalModuleLogEvent");
        zzae zzaeVar67 = new zzae();
        zzaeVar67.zza(65);
        zzap = c2317bA67.b(zzaeVar67.zzb()).a();
        b.C2317b c2317bA68 = b.a("customImageLabelOptionalModuleLogEvent");
        zzae zzaeVar68 = new zzae();
        zzaeVar68.zza(66);
        zzaq = c2317bA68.b(zzaeVar68.zzb()).a();
        b.C2317b c2317bA69 = b.a("codeScannerScanApiEvent");
        zzae zzaeVar69 = new zzae();
        zzaeVar69.zza(67);
        zzar = c2317bA69.b(zzaeVar69.zzb()).a();
        b.C2317b c2317bA70 = b.a("codeScannerOptionalModuleEvent");
        zzae zzaeVar70 = new zzae();
        zzaeVar70.zza(68);
        zzas = c2317bA70.b(zzaeVar70.zzb()).a();
        b.C2317b c2317bA71 = b.a("onDeviceExplicitContentCreateLogEvent");
        zzae zzaeVar71 = new zzae();
        zzaeVar71.zza(70);
        zzat = c2317bA71.b(zzaeVar71.zzb()).a();
        b.C2317b c2317bA72 = b.a("onDeviceExplicitContentLoadLogEvent");
        zzae zzaeVar72 = new zzae();
        zzaeVar72.zza(71);
        zzau = c2317bA72.b(zzaeVar72.zzb()).a();
        b.C2317b c2317bA73 = b.a("onDeviceExplicitContentInferenceLogEvent");
        zzae zzaeVar73 = new zzae();
        zzaeVar73.zza(72);
        zzav = c2317bA73.b(zzaeVar73.zzb()).a();
        b.C2317b c2317bA74 = b.a("aggregatedOnDeviceExplicitContentLogEvent");
        zzae zzaeVar74 = new zzae();
        zzaeVar74.zza(73);
        zzaw = c2317bA74.b(zzaeVar74.zzb()).a();
        b.C2317b c2317bA75 = b.a("onDeviceFaceMeshCreateLogEvent");
        zzae zzaeVar75 = new zzae();
        zzaeVar75.zza(74);
        zzax = c2317bA75.b(zzaeVar75.zzb()).a();
        b.C2317b c2317bA76 = b.a("onDeviceFaceMeshLoadLogEvent");
        zzae zzaeVar76 = new zzae();
        zzaeVar76.zza(75);
        zzay = c2317bA76.b(zzaeVar76.zzb()).a();
        b.C2317b c2317bA77 = b.a("onDeviceFaceMeshLogEvent");
        zzae zzaeVar77 = new zzae();
        zzaeVar77.zza(76);
        zzaz = c2317bA77.b(zzaeVar77.zzb()).a();
        b.C2317b c2317bA78 = b.a("aggregatedOnDeviceFaceMeshLogEvent");
        zzae zzaeVar78 = new zzae();
        zzaeVar78.zza(77);
        zzaA = c2317bA78.b(zzaeVar78.zzb()).a();
        b.C2317b c2317bA79 = b.a("smartReplyOptionalModuleLogEvent");
        zzae zzaeVar79 = new zzae();
        zzaeVar79.zza(78);
        zzaB = c2317bA79.b(zzaeVar79.zzb()).a();
        b.C2317b c2317bA80 = b.a("textDetectionOptionalModuleLogEvent");
        zzae zzaeVar80 = new zzae();
        zzaeVar80.zza(80);
        zzaC = c2317bA80.b(zzaeVar80.zzb()).a();
        b.C2317b c2317bA81 = b.a("onDeviceImageQualityAnalysisCreateLogEvent");
        zzae zzaeVar81 = new zzae();
        zzaeVar81.zza(81);
        zzaD = c2317bA81.b(zzaeVar81.zzb()).a();
        b.C2317b c2317bA82 = b.a("onDeviceImageQualityAnalysisLoadLogEvent");
        zzae zzaeVar82 = new zzae();
        zzaeVar82.zza(82);
        zzaE = c2317bA82.b(zzaeVar82.zzb()).a();
        b.C2317b c2317bA83 = b.a("onDeviceImageQualityAnalysisLogEvent");
        zzae zzaeVar83 = new zzae();
        zzaeVar83.zza(83);
        zzaF = c2317bA83.b(zzaeVar83.zzb()).a();
        b.C2317b c2317bA84 = b.a("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zzae zzaeVar84 = new zzae();
        zzaeVar84.zza(84);
        zzaG = c2317bA84.b(zzaeVar84.zzb()).a();
        b.C2317b c2317bA85 = b.a("imageQualityAnalysisOptionalModuleLogEvent");
        zzae zzaeVar85 = new zzae();
        zzaeVar85.zza(88);
        zzaH = c2317bA85.b(zzaeVar85.zzb()).a();
        b.C2317b c2317bA86 = b.a("imageCaptioningOptionalModuleLogEvent");
        zzae zzaeVar86 = new zzae();
        zzaeVar86.zza(89);
        zzaI = c2317bA86.b(zzaeVar86.zzb()).a();
        b.C2317b c2317bA87 = b.a("onDeviceImageCaptioningCreateLogEvent");
        zzae zzaeVar87 = new zzae();
        zzaeVar87.zza(90);
        zzaJ = c2317bA87.b(zzaeVar87.zzb()).a();
        b.C2317b c2317bA88 = b.a("onDeviceImageCaptioningLoadLogEvent");
        zzae zzaeVar88 = new zzae();
        zzaeVar88.zza(91);
        zzaK = c2317bA88.b(zzaeVar88.zzb()).a();
        b.C2317b c2317bA89 = b.a("onDeviceImageCaptioningInferenceLogEvent");
        zzae zzaeVar89 = new zzae();
        zzaeVar89.zza(92);
        zzaL = c2317bA89.b(zzaeVar89.zzb()).a();
        b.C2317b c2317bA90 = b.a("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zzae zzaeVar90 = new zzae();
        zzaeVar90.zza(93);
        zzaM = c2317bA90.b(zzaeVar90.zzb()).a();
    }

    private zzeo() {
    }

    @Override // rv.c
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) {
        zziy zziyVar = (zziy) obj;
        d dVar = (d) obj2;
        dVar.add(zzb, zziyVar.zzc());
        dVar.add(zzc, zziyVar.zzb());
        dVar.add(zzd, (Object) null);
        dVar.add(zze, (Object) null);
        dVar.add(zzf, (Object) null);
        dVar.add(zzg, (Object) null);
        dVar.add(zzh, (Object) null);
        dVar.add(zzi, (Object) null);
        dVar.add(zzj, (Object) null);
        dVar.add(zzk, (Object) null);
        dVar.add(zzl, (Object) null);
        dVar.add(zzm, (Object) null);
        dVar.add(zzn, (Object) null);
        dVar.add(zzo, (Object) null);
        dVar.add(zzp, (Object) null);
        dVar.add(zzq, (Object) null);
        dVar.add(zzr, (Object) null);
        dVar.add(zzs, (Object) null);
        dVar.add(zzt, (Object) null);
        dVar.add(zzu, (Object) null);
        dVar.add(zzv, (Object) null);
        dVar.add(zzw, (Object) null);
        dVar.add(zzx, (Object) null);
        dVar.add(zzy, (Object) null);
        dVar.add(zzz, (Object) null);
        dVar.add(zzA, (Object) null);
        dVar.add(zzB, (Object) null);
        dVar.add(zzC, (Object) null);
        dVar.add(zzD, (Object) null);
        dVar.add(zzE, (Object) null);
        dVar.add(zzF, (Object) null);
        dVar.add(zzG, (Object) null);
        dVar.add(zzH, (Object) null);
        dVar.add(zzI, (Object) null);
        dVar.add(zzJ, (Object) null);
        dVar.add(zzK, (Object) null);
        dVar.add(zzL, (Object) null);
        dVar.add(zzM, (Object) null);
        dVar.add(zzN, (Object) null);
        dVar.add(zzO, (Object) null);
        dVar.add(zzP, (Object) null);
        dVar.add(zzQ, (Object) null);
        dVar.add(zzR, (Object) null);
        dVar.add(zzS, (Object) null);
        dVar.add(zzT, (Object) null);
        dVar.add(zzU, (Object) null);
        dVar.add(zzV, (Object) null);
        dVar.add(zzW, (Object) null);
        dVar.add(zzX, (Object) null);
        dVar.add(zzY, (Object) null);
        dVar.add(zzZ, (Object) null);
        dVar.add(zzaa, zziyVar.zza());
        dVar.add(zzab, (Object) null);
        dVar.add(zzac, (Object) null);
        dVar.add(zzad, (Object) null);
        dVar.add(zzae, (Object) null);
        dVar.add(zzaf, (Object) null);
        dVar.add(zzag, (Object) null);
        dVar.add(zzah, (Object) null);
        dVar.add(zzai, (Object) null);
        dVar.add(zzaj, (Object) null);
        dVar.add(zzak, (Object) null);
        dVar.add(zzal, (Object) null);
        dVar.add(zzam, (Object) null);
        dVar.add(zzan, (Object) null);
        dVar.add(zzao, (Object) null);
        dVar.add(zzap, (Object) null);
        dVar.add(zzaq, (Object) null);
        dVar.add(zzar, (Object) null);
        dVar.add(zzas, (Object) null);
        dVar.add(zzat, (Object) null);
        dVar.add(zzau, (Object) null);
        dVar.add(zzav, (Object) null);
        dVar.add(zzaw, (Object) null);
        dVar.add(zzax, (Object) null);
        dVar.add(zzay, (Object) null);
        dVar.add(zzaz, (Object) null);
        dVar.add(zzaA, (Object) null);
        dVar.add(zzaB, (Object) null);
        dVar.add(zzaC, (Object) null);
        dVar.add(zzaD, (Object) null);
        dVar.add(zzaE, (Object) null);
        dVar.add(zzaF, (Object) null);
        dVar.add(zzaG, (Object) null);
        dVar.add(zzaH, (Object) null);
        dVar.add(zzaI, (Object) null);
        dVar.add(zzaJ, (Object) null);
        dVar.add(zzaK, (Object) null);
        dVar.add(zzaL, (Object) null);
        dVar.add(zzaM, (Object) null);
    }
}
