sonar.projectKey=Blaze209_t1test
sonar.organization=blaze209
sonar.host.url=https://sonarcloud.io
sonar.sources=src/main/java
sonar.java.binaries=
sonar.java.libraries=
sonar.exclusions=**/androidx/**/*,**/kotlin/**/*,**/kotlinx/**/*,**/okhttp3/**/*,**/okio/**/*,**/retrofit2/**/*,**/dagger/**/*,**/com/google/**/*,**/com/facebook/**/*,**/com/bumptech/**/*,**/com/appsflyer/**/*,**/com/airbnb/**/*,**/com/reactlibrary/**/*,**/com/reactnativecommunity/**/*,**/com/swmansion/**/*,**/com/arkoselabs/**/*,**/com/apollographql/**/*,**/com/fasterxml/**/*,**/io/reactivex/**/*,**/io/ktor/**/*,**/org/apache/**/*,**/org/bouncycastle/**/*,**/org/json/**/*,**/org/slf4j/**/*,**/org/xml/**/*,**/org/w3c/**/*,**/org/junit/**/*,**/org/hamcrest/**/*,**/javax/**/*,**/dalvik/**/*,**/expo/**/*,**/bolts/**/*,**/eightbitlab/**/*,**/jp/**/*,**/fr/**/*,**/sprig/**/*,**/shadow/**/*,**/test/**/*,**/*Test*.java,**/*IT*.java,**/generated/**/*,**/com/braze/ui/inappmessage/jsinterface/InAppMessageJavascriptInterface.java
sonar.coverage.exclusions=**/test/**/*,**/*Test*.java,**/*IT*.java
sonar.cpd.exclusions=**/test/**/*,**/*Test*.java,**/generated/**/*
sonar.scanner.excludeHiddenFiles=true
sonar.java.source=11
sonar.java.target=11