package p013kotlin.reflect.jvm.internal.impl.util;

import ch.qos.logback.classic.pattern.CallerDataConverter;
import java.util.Map;
import java.util.Set;
import jn0.x;
import org.slf4j.Marker;
import p013kotlin.collections.d1;
import p013kotlin.collections.v0;
import p013kotlin.jvm.internal.s;
import p013kotlin.reflect.jvm.internal.impl.name.Name;
import p013kotlin.text.q;

/* JADX INFO: loaded from: classes9.dex */
public final class OperatorNameConventions {
    public static final Set<Name> ALL_BINARY_OPERATION_NAMES;
    public static final Name AND;
    public static final Set<Name> ASSIGNMENT_OPERATIONS;
    public static final Set<Name> BINARY_OPERATION_NAMES;
    public static final Set<Name> BITWISE_OPERATION_NAMES;
    public static final Name COMPARE_TO;
    public static final q COMPONENT_REGEX;
    public static final Name CONTAINS;
    public static final Name DEC;
    public static final Set<Name> DELEGATED_PROPERTY_OPERATORS;
    public static final Name DIV;
    public static final Name DIV_ASSIGN;
    public static final Name EQUALS;
    public static final Name GET;
    public static final Name GET_VALUE;
    public static final Name HASH_CODE;
    public static final Name HAS_NEXT;
    public static final Name INC;
    public static final OperatorNameConventions INSTANCE = new OperatorNameConventions();
    public static final Name INV;
    public static final Name INVOKE;
    public static final Name ITERATOR;
    public static final Name MINUS;
    public static final Name MINUS_ASSIGN;
    public static final Name MOD;
    public static final Name MOD_ASSIGN;
    public static final Map<Name, Name> MOD_OPERATORS_REPLACEMENT;
    public static final Name NEXT;
    public static final Name NOT;
    public static final Set<Name> NUMBER_CONVERSIONS;
    public static final Name OR;
    public static final Name PLUS;
    public static final Name PLUS_ASSIGN;
    public static final Name PROVIDE_DELEGATE;
    public static final Name RANGE_TO;
    public static final Name RANGE_UNTIL;
    public static final Name REM;
    public static final Name REM_ASSIGN;
    public static final Name SET;
    public static final Name SET_VALUE;
    public static final Name SHL;
    public static final Name SHR;
    public static final Set<Name> SIMPLE_BINARY_OPERATION_NAMES;
    public static final Set<Name> SIMPLE_BITWISE_OPERATION_NAMES;
    public static final Set<Name> SIMPLE_UNARY_OPERATION_NAMES;
    public static final Set<Name> STATEMENT_LIKE_OPERATORS;
    public static final Name TIMES;
    public static final Name TIMES_ASSIGN;
    public static final Name TO_BYTE;
    public static final Name TO_CHAR;
    public static final Name TO_DOUBLE;
    public static final Name TO_FLOAT;
    public static final Name TO_INT;
    public static final Name TO_LONG;
    public static final Name TO_SHORT;
    public static final Name TO_STRING;
    public static final Name UNARY_MINUS;
    public static final Set<Name> UNARY_OPERATION_NAMES;
    public static final Name UNARY_PLUS;
    public static final Name USHR;
    public static final Name XOR;

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    private static final Map<Name, String> f89071a;

    static {
        Name nameIdentifier = Name.identifier("getValue");
        s.j(nameIdentifier, "identifier(...)");
        GET_VALUE = nameIdentifier;
        Name nameIdentifier2 = Name.identifier("setValue");
        s.j(nameIdentifier2, "identifier(...)");
        SET_VALUE = nameIdentifier2;
        Name nameIdentifier3 = Name.identifier("provideDelegate");
        s.j(nameIdentifier3, "identifier(...)");
        PROVIDE_DELEGATE = nameIdentifier3;
        Name nameIdentifier4 = Name.identifier("equals");
        s.j(nameIdentifier4, "identifier(...)");
        EQUALS = nameIdentifier4;
        Name nameIdentifier5 = Name.identifier("hashCode");
        s.j(nameIdentifier5, "identifier(...)");
        HASH_CODE = nameIdentifier5;
        Name nameIdentifier6 = Name.identifier("compareTo");
        s.j(nameIdentifier6, "identifier(...)");
        COMPARE_TO = nameIdentifier6;
        Name nameIdentifier7 = Name.identifier("contains");
        s.j(nameIdentifier7, "identifier(...)");
        CONTAINS = nameIdentifier7;
        Name nameIdentifier8 = Name.identifier("invoke");
        s.j(nameIdentifier8, "identifier(...)");
        INVOKE = nameIdentifier8;
        Name nameIdentifier9 = Name.identifier("iterator");
        s.j(nameIdentifier9, "identifier(...)");
        ITERATOR = nameIdentifier9;
        Name nameIdentifier10 = Name.identifier("get");
        s.j(nameIdentifier10, "identifier(...)");
        GET = nameIdentifier10;
        Name nameIdentifier11 = Name.identifier("set");
        s.j(nameIdentifier11, "identifier(...)");
        SET = nameIdentifier11;
        Name nameIdentifier12 = Name.identifier("next");
        s.j(nameIdentifier12, "identifier(...)");
        NEXT = nameIdentifier12;
        Name nameIdentifier13 = Name.identifier("hasNext");
        s.j(nameIdentifier13, "identifier(...)");
        HAS_NEXT = nameIdentifier13;
        Name nameIdentifier14 = Name.identifier("toString");
        s.j(nameIdentifier14, "identifier(...)");
        TO_STRING = nameIdentifier14;
        COMPONENT_REGEX = new q("component\\d+");
        Name nameIdentifier15 = Name.identifier("and");
        s.j(nameIdentifier15, "identifier(...)");
        AND = nameIdentifier15;
        Name nameIdentifier16 = Name.identifier("or");
        s.j(nameIdentifier16, "identifier(...)");
        OR = nameIdentifier16;
        Name nameIdentifier17 = Name.identifier("xor");
        s.j(nameIdentifier17, "identifier(...)");
        XOR = nameIdentifier17;
        Name nameIdentifier18 = Name.identifier("inv");
        s.j(nameIdentifier18, "identifier(...)");
        INV = nameIdentifier18;
        Name nameIdentifier19 = Name.identifier("shl");
        s.j(nameIdentifier19, "identifier(...)");
        SHL = nameIdentifier19;
        Name nameIdentifier20 = Name.identifier("shr");
        s.j(nameIdentifier20, "identifier(...)");
        SHR = nameIdentifier20;
        Name nameIdentifier21 = Name.identifier("ushr");
        s.j(nameIdentifier21, "identifier(...)");
        USHR = nameIdentifier21;
        Name nameIdentifier22 = Name.identifier("inc");
        s.j(nameIdentifier22, "identifier(...)");
        INC = nameIdentifier22;
        Name nameIdentifier23 = Name.identifier("dec");
        s.j(nameIdentifier23, "identifier(...)");
        DEC = nameIdentifier23;
        Name nameIdentifier24 = Name.identifier("plus");
        s.j(nameIdentifier24, "identifier(...)");
        PLUS = nameIdentifier24;
        Name nameIdentifier25 = Name.identifier("minus");
        s.j(nameIdentifier25, "identifier(...)");
        MINUS = nameIdentifier25;
        Name nameIdentifier26 = Name.identifier("not");
        s.j(nameIdentifier26, "identifier(...)");
        NOT = nameIdentifier26;
        Name nameIdentifier27 = Name.identifier("unaryMinus");
        s.j(nameIdentifier27, "identifier(...)");
        UNARY_MINUS = nameIdentifier27;
        Name nameIdentifier28 = Name.identifier("unaryPlus");
        s.j(nameIdentifier28, "identifier(...)");
        UNARY_PLUS = nameIdentifier28;
        Name nameIdentifier29 = Name.identifier("times");
        s.j(nameIdentifier29, "identifier(...)");
        TIMES = nameIdentifier29;
        Name nameIdentifier30 = Name.identifier("div");
        s.j(nameIdentifier30, "identifier(...)");
        DIV = nameIdentifier30;
        Name nameIdentifier31 = Name.identifier("mod");
        s.j(nameIdentifier31, "identifier(...)");
        MOD = nameIdentifier31;
        Name nameIdentifier32 = Name.identifier("rem");
        s.j(nameIdentifier32, "identifier(...)");
        REM = nameIdentifier32;
        Name nameIdentifier33 = Name.identifier("rangeTo");
        s.j(nameIdentifier33, "identifier(...)");
        RANGE_TO = nameIdentifier33;
        Name nameIdentifier34 = Name.identifier("rangeUntil");
        s.j(nameIdentifier34, "identifier(...)");
        RANGE_UNTIL = nameIdentifier34;
        Name nameIdentifier35 = Name.identifier("timesAssign");
        s.j(nameIdentifier35, "identifier(...)");
        TIMES_ASSIGN = nameIdentifier35;
        Name nameIdentifier36 = Name.identifier("divAssign");
        s.j(nameIdentifier36, "identifier(...)");
        DIV_ASSIGN = nameIdentifier36;
        Name nameIdentifier37 = Name.identifier("modAssign");
        s.j(nameIdentifier37, "identifier(...)");
        MOD_ASSIGN = nameIdentifier37;
        Name nameIdentifier38 = Name.identifier("remAssign");
        s.j(nameIdentifier38, "identifier(...)");
        REM_ASSIGN = nameIdentifier38;
        Name nameIdentifier39 = Name.identifier("plusAssign");
        s.j(nameIdentifier39, "identifier(...)");
        PLUS_ASSIGN = nameIdentifier39;
        Name nameIdentifier40 = Name.identifier("minusAssign");
        s.j(nameIdentifier40, "identifier(...)");
        MINUS_ASSIGN = nameIdentifier40;
        Name nameIdentifier41 = Name.identifier("toDouble");
        s.j(nameIdentifier41, "identifier(...)");
        TO_DOUBLE = nameIdentifier41;
        Name nameIdentifier42 = Name.identifier("toFloat");
        s.j(nameIdentifier42, "identifier(...)");
        TO_FLOAT = nameIdentifier42;
        Name nameIdentifier43 = Name.identifier("toLong");
        s.j(nameIdentifier43, "identifier(...)");
        TO_LONG = nameIdentifier43;
        Name nameIdentifier44 = Name.identifier("toInt");
        s.j(nameIdentifier44, "identifier(...)");
        TO_INT = nameIdentifier44;
        Name nameIdentifier45 = Name.identifier("toChar");
        s.j(nameIdentifier45, "identifier(...)");
        TO_CHAR = nameIdentifier45;
        Name nameIdentifier46 = Name.identifier("toShort");
        s.j(nameIdentifier46, "identifier(...)");
        TO_SHORT = nameIdentifier46;
        Name nameIdentifier47 = Name.identifier("toByte");
        s.j(nameIdentifier47, "identifier(...)");
        TO_BYTE = nameIdentifier47;
        UNARY_OPERATION_NAMES = d1.i(nameIdentifier22, nameIdentifier23, nameIdentifier28, nameIdentifier27, nameIdentifier26, nameIdentifier18);
        SIMPLE_UNARY_OPERATION_NAMES = d1.i(nameIdentifier28, nameIdentifier27, nameIdentifier26, nameIdentifier18);
        Set<Name> setI = d1.i(nameIdentifier29, nameIdentifier24, nameIdentifier25, nameIdentifier30, nameIdentifier31, nameIdentifier32, nameIdentifier33, nameIdentifier34);
        BINARY_OPERATION_NAMES = setI;
        SIMPLE_BINARY_OPERATION_NAMES = d1.i(nameIdentifier29, nameIdentifier24, nameIdentifier25, nameIdentifier30, nameIdentifier31, nameIdentifier32);
        Set<Name> setI2 = d1.i(nameIdentifier15, nameIdentifier16, nameIdentifier17, nameIdentifier18, nameIdentifier19, nameIdentifier20, nameIdentifier21);
        BITWISE_OPERATION_NAMES = setI2;
        SIMPLE_BITWISE_OPERATION_NAMES = d1.i(nameIdentifier15, nameIdentifier16, nameIdentifier17, nameIdentifier19, nameIdentifier20, nameIdentifier21);
        ALL_BINARY_OPERATION_NAMES = d1.n(d1.n(setI, setI2), d1.i(nameIdentifier4, nameIdentifier7, nameIdentifier6));
        Set<Name> setI3 = d1.i(nameIdentifier35, nameIdentifier36, nameIdentifier37, nameIdentifier38, nameIdentifier39, nameIdentifier40);
        ASSIGNMENT_OPERATIONS = setI3;
        DELEGATED_PROPERTY_OPERATORS = d1.i(nameIdentifier, nameIdentifier2, nameIdentifier3);
        MOD_OPERATORS_REPLACEMENT = v0.m(x.a(nameIdentifier31, nameIdentifier32), x.a(nameIdentifier37, nameIdentifier38));
        STATEMENT_LIKE_OPERATORS = d1.n(d1.c(nameIdentifier11), setI3);
        NUMBER_CONVERSIONS = d1.i(nameIdentifier41, nameIdentifier42, nameIdentifier43, nameIdentifier44, nameIdentifier46, nameIdentifier47, nameIdentifier45);
        f89071a = v0.m(x.a(nameIdentifier22, "++"), x.a(nameIdentifier23, "--"), x.a(nameIdentifier28, Marker.ANY_NON_NULL_MARKER), x.a(nameIdentifier27, "-"), x.a(nameIdentifier26, "!"), x.a(nameIdentifier29, Marker.ANY_MARKER), x.a(nameIdentifier24, Marker.ANY_NON_NULL_MARKER), x.a(nameIdentifier25, "-"), x.a(nameIdentifier30, "/"), x.a(nameIdentifier32, "%"), x.a(nameIdentifier33, CallerDataConverter.DEFAULT_RANGE_DELIMITER), x.a(nameIdentifier34, "..<"));
    }

    private OperatorNameConventions() {
    }
}
