package com.google.android.gms.internal.mlkit_vision_face;

import rv.b;
import rv.c;
import rv.d;

/* JADX INFO: loaded from: classes5.dex */
final class zzgq implements c {
    private static final b zzA;
    private static final b zzB;
    private static final b zzC;
    private static final b zzD;
    private static final b zzE;
    private static final b zzF;
    private static final b zzG;
    private static final b zzH;
    private static final b zzI;
    private static final b zzJ;
    private static final b zzK;
    private static final b zzL;
    private static final b zzM;
    private static final b zzN;
    private static final b zzO;
    private static final b zzP;
    private static final b zzQ;
    private static final b zzR;
    private static final b zzS;
    private static final b zzT;
    private static final b zzU;
    private static final b zzV;
    private static final b zzW;
    private static final b zzX;
    private static final b zzY;
    private static final b zzZ;
    static final zzgq zza = new zzgq();
    private static final b zzaa;
    private static final b zzab;
    private static final b zzac;
    private static final b zzad;
    private static final b zzae;
    private static final b zzaf;
    private static final b zzag;
    private static final b zzah;
    private static final b zzai;
    private static final b zzaj;
    private static final b zzak;
    private static final b zzal;
    private static final b zzam;
    private static final b zzan;
    private static final b zzao;
    private static final b zzap;
    private static final b zzaq;
    private static final b zzar;
    private static final b zzas;
    private static final b zzat;
    private static final b zzau;
    private static final b zzav;
    private static final b zzaw;
    private static final b zzax;
    private static final b zzay;
    private static final b zzb;
    private static final b zzc;
    private static final b zzd;
    private static final b zze;
    private static final b zzf;
    private static final b zzg;
    private static final b zzh;
    private static final b zzi;
    private static final b zzj;
    private static final b zzk;
    private static final b zzl;
    private static final b zzm;
    private static final b zzn;
    private static final b zzo;
    private static final b zzp;
    private static final b zzq;
    private static final b zzr;
    private static final b zzs;
    private static final b zzt;
    private static final b zzu;
    private static final b zzv;
    private static final b zzw;
    private static final b zzx;
    private static final b zzy;
    private static final b zzz;

    static {
        b.C2317b c2317bA = b.a("systemInfo");
        zzcq zzcqVar = new zzcq();
        zzcqVar.zza(1);
        zzb = c2317bA.b(zzcqVar.zzb()).a();
        b.C2317b c2317bA2 = b.a("eventName");
        zzcq zzcqVar2 = new zzcq();
        zzcqVar2.zza(2);
        zzc = c2317bA2.b(zzcqVar2.zzb()).a();
        b.C2317b c2317bA3 = b.a("isThickClient");
        zzcq zzcqVar3 = new zzcq();
        zzcqVar3.zza(37);
        zzd = c2317bA3.b(zzcqVar3.zzb()).a();
        b.C2317b c2317bA4 = b.a("clientType");
        zzcq zzcqVar4 = new zzcq();
        zzcqVar4.zza(61);
        zze = c2317bA4.b(zzcqVar4.zzb()).a();
        b.C2317b c2317bA5 = b.a("modelDownloadLogEvent");
        zzcq zzcqVar5 = new zzcq();
        zzcqVar5.zza(3);
        zzf = c2317bA5.b(zzcqVar5.zzb()).a();
        b.C2317b c2317bA6 = b.a("customModelLoadLogEvent");
        zzcq zzcqVar6 = new zzcq();
        zzcqVar6.zza(20);
        zzg = c2317bA6.b(zzcqVar6.zzb()).a();
        b.C2317b c2317bA7 = b.a("customModelInferenceLogEvent");
        zzcq zzcqVar7 = new zzcq();
        zzcqVar7.zza(4);
        zzh = c2317bA7.b(zzcqVar7.zzb()).a();
        b.C2317b c2317bA8 = b.a("customModelCreateLogEvent");
        zzcq zzcqVar8 = new zzcq();
        zzcqVar8.zza(29);
        zzi = c2317bA8.b(zzcqVar8.zzb()).a();
        b.C2317b c2317bA9 = b.a("onDeviceFaceDetectionLogEvent");
        zzcq zzcqVar9 = new zzcq();
        zzcqVar9.zza(5);
        zzj = c2317bA9.b(zzcqVar9.zzb()).a();
        b.C2317b c2317bA10 = b.a("onDeviceFaceLoadLogEvent");
        zzcq zzcqVar10 = new zzcq();
        zzcqVar10.zza(59);
        zzk = c2317bA10.b(zzcqVar10.zzb()).a();
        b.C2317b c2317bA11 = b.a("onDeviceTextDetectionLogEvent");
        zzcq zzcqVar11 = new zzcq();
        zzcqVar11.zza(6);
        zzl = c2317bA11.b(zzcqVar11.zzb()).a();
        b.C2317b c2317bA12 = b.a("onDeviceTextDetectionLoadLogEvent");
        zzcq zzcqVar12 = new zzcq();
        zzcqVar12.zza(79);
        zzm = c2317bA12.b(zzcqVar12.zzb()).a();
        b.C2317b c2317bA13 = b.a("onDeviceBarcodeDetectionLogEvent");
        zzcq zzcqVar13 = new zzcq();
        zzcqVar13.zza(7);
        zzn = c2317bA13.b(zzcqVar13.zzb()).a();
        b.C2317b c2317bA14 = b.a("onDeviceBarcodeLoadLogEvent");
        zzcq zzcqVar14 = new zzcq();
        zzcqVar14.zza(58);
        zzo = c2317bA14.b(zzcqVar14.zzb()).a();
        b.C2317b c2317bA15 = b.a("onDeviceImageLabelCreateLogEvent");
        zzcq zzcqVar15 = new zzcq();
        zzcqVar15.zza(48);
        zzp = c2317bA15.b(zzcqVar15.zzb()).a();
        b.C2317b c2317bA16 = b.a("onDeviceImageLabelLoadLogEvent");
        zzcq zzcqVar16 = new zzcq();
        zzcqVar16.zza(49);
        zzq = c2317bA16.b(zzcqVar16.zzb()).a();
        b.C2317b c2317bA17 = b.a("onDeviceImageLabelDetectionLogEvent");
        zzcq zzcqVar17 = new zzcq();
        zzcqVar17.zza(18);
        zzr = c2317bA17.b(zzcqVar17.zzb()).a();
        b.C2317b c2317bA18 = b.a("onDeviceObjectCreateLogEvent");
        zzcq zzcqVar18 = new zzcq();
        zzcqVar18.zza(26);
        zzs = c2317bA18.b(zzcqVar18.zzb()).a();
        b.C2317b c2317bA19 = b.a("onDeviceObjectLoadLogEvent");
        zzcq zzcqVar19 = new zzcq();
        zzcqVar19.zza(27);
        zzt = c2317bA19.b(zzcqVar19.zzb()).a();
        b.C2317b c2317bA20 = b.a("onDeviceObjectInferenceLogEvent");
        zzcq zzcqVar20 = new zzcq();
        zzcqVar20.zza(28);
        zzu = c2317bA20.b(zzcqVar20.zzb()).a();
        b.C2317b c2317bA21 = b.a("onDevicePoseDetectionLogEvent");
        zzcq zzcqVar21 = new zzcq();
        zzcqVar21.zza(44);
        zzv = c2317bA21.b(zzcqVar21.zzb()).a();
        b.C2317b c2317bA22 = b.a("onDeviceSegmentationLogEvent");
        zzcq zzcqVar22 = new zzcq();
        zzcqVar22.zza(45);
        zzw = c2317bA22.b(zzcqVar22.zzb()).a();
        b.C2317b c2317bA23 = b.a("onDeviceSmartReplyLogEvent");
        zzcq zzcqVar23 = new zzcq();
        zzcqVar23.zza(19);
        zzx = c2317bA23.b(zzcqVar23.zzb()).a();
        b.C2317b c2317bA24 = b.a("onDeviceLanguageIdentificationLogEvent");
        zzcq zzcqVar24 = new zzcq();
        zzcqVar24.zza(21);
        zzy = c2317bA24.b(zzcqVar24.zzb()).a();
        b.C2317b c2317bA25 = b.a("onDeviceTranslationLogEvent");
        zzcq zzcqVar25 = new zzcq();
        zzcqVar25.zza(22);
        zzz = c2317bA25.b(zzcqVar25.zzb()).a();
        b.C2317b c2317bA26 = b.a("cloudFaceDetectionLogEvent");
        zzcq zzcqVar26 = new zzcq();
        zzcqVar26.zza(8);
        zzA = c2317bA26.b(zzcqVar26.zzb()).a();
        b.C2317b c2317bA27 = b.a("cloudCropHintDetectionLogEvent");
        zzcq zzcqVar27 = new zzcq();
        zzcqVar27.zza(9);
        zzB = c2317bA27.b(zzcqVar27.zzb()).a();
        b.C2317b c2317bA28 = b.a("cloudDocumentTextDetectionLogEvent");
        zzcq zzcqVar28 = new zzcq();
        zzcqVar28.zza(10);
        zzC = c2317bA28.b(zzcqVar28.zzb()).a();
        b.C2317b c2317bA29 = b.a("cloudImagePropertiesDetectionLogEvent");
        zzcq zzcqVar29 = new zzcq();
        zzcqVar29.zza(11);
        zzD = c2317bA29.b(zzcqVar29.zzb()).a();
        b.C2317b c2317bA30 = b.a("cloudImageLabelDetectionLogEvent");
        zzcq zzcqVar30 = new zzcq();
        zzcqVar30.zza(12);
        zzE = c2317bA30.b(zzcqVar30.zzb()).a();
        b.C2317b c2317bA31 = b.a("cloudLandmarkDetectionLogEvent");
        zzcq zzcqVar31 = new zzcq();
        zzcqVar31.zza(13);
        zzF = c2317bA31.b(zzcqVar31.zzb()).a();
        b.C2317b c2317bA32 = b.a("cloudLogoDetectionLogEvent");
        zzcq zzcqVar32 = new zzcq();
        zzcqVar32.zza(14);
        zzG = c2317bA32.b(zzcqVar32.zzb()).a();
        b.C2317b c2317bA33 = b.a("cloudSafeSearchDetectionLogEvent");
        zzcq zzcqVar33 = new zzcq();
        zzcqVar33.zza(15);
        zzH = c2317bA33.b(zzcqVar33.zzb()).a();
        b.C2317b c2317bA34 = b.a("cloudTextDetectionLogEvent");
        zzcq zzcqVar34 = new zzcq();
        zzcqVar34.zza(16);
        zzI = c2317bA34.b(zzcqVar34.zzb()).a();
        b.C2317b c2317bA35 = b.a("cloudWebSearchDetectionLogEvent");
        zzcq zzcqVar35 = new zzcq();
        zzcqVar35.zza(17);
        zzJ = c2317bA35.b(zzcqVar35.zzb()).a();
        b.C2317b c2317bA36 = b.a("automlImageLabelingCreateLogEvent");
        zzcq zzcqVar36 = new zzcq();
        zzcqVar36.zza(23);
        zzK = c2317bA36.b(zzcqVar36.zzb()).a();
        b.C2317b c2317bA37 = b.a("automlImageLabelingLoadLogEvent");
        zzcq zzcqVar37 = new zzcq();
        zzcqVar37.zza(24);
        zzL = c2317bA37.b(zzcqVar37.zzb()).a();
        b.C2317b c2317bA38 = b.a("automlImageLabelingInferenceLogEvent");
        zzcq zzcqVar38 = new zzcq();
        zzcqVar38.zza(25);
        zzM = c2317bA38.b(zzcqVar38.zzb()).a();
        b.C2317b c2317bA39 = b.a("isModelDownloadedLogEvent");
        zzcq zzcqVar39 = new zzcq();
        zzcqVar39.zza(39);
        zzN = c2317bA39.b(zzcqVar39.zzb()).a();
        b.C2317b c2317bA40 = b.a("deleteModelLogEvent");
        zzcq zzcqVar40 = new zzcq();
        zzcqVar40.zza(40);
        zzO = c2317bA40.b(zzcqVar40.zzb()).a();
        b.C2317b c2317bA41 = b.a("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzcq zzcqVar41 = new zzcq();
        zzcqVar41.zza(30);
        zzP = c2317bA41.b(zzcqVar41.zzb()).a();
        b.C2317b c2317bA42 = b.a("aggregatedCustomModelInferenceLogEvent");
        zzcq zzcqVar42 = new zzcq();
        zzcqVar42.zza(31);
        zzQ = c2317bA42.b(zzcqVar42.zzb()).a();
        b.C2317b c2317bA43 = b.a("aggregatedOnDeviceFaceDetectionLogEvent");
        zzcq zzcqVar43 = new zzcq();
        zzcqVar43.zza(32);
        zzR = c2317bA43.b(zzcqVar43.zzb()).a();
        b.C2317b c2317bA44 = b.a("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzcq zzcqVar44 = new zzcq();
        zzcqVar44.zza(33);
        zzS = c2317bA44.b(zzcqVar44.zzb()).a();
        b.C2317b c2317bA45 = b.a("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzcq zzcqVar45 = new zzcq();
        zzcqVar45.zza(34);
        zzT = c2317bA45.b(zzcqVar45.zzb()).a();
        b.C2317b c2317bA46 = b.a("aggregatedOnDeviceObjectInferenceLogEvent");
        zzcq zzcqVar46 = new zzcq();
        zzcqVar46.zza(35);
        zzU = c2317bA46.b(zzcqVar46.zzb()).a();
        b.C2317b c2317bA47 = b.a("aggregatedOnDeviceTextDetectionLogEvent");
        zzcq zzcqVar47 = new zzcq();
        zzcqVar47.zza(36);
        zzV = c2317bA47.b(zzcqVar47.zzb()).a();
        b.C2317b c2317bA48 = b.a("aggregatedOnDevicePoseDetectionLogEvent");
        zzcq zzcqVar48 = new zzcq();
        zzcqVar48.zza(46);
        zzW = c2317bA48.b(zzcqVar48.zzb()).a();
        b.C2317b c2317bA49 = b.a("aggregatedOnDeviceSegmentationLogEvent");
        zzcq zzcqVar49 = new zzcq();
        zzcqVar49.zza(47);
        zzX = c2317bA49.b(zzcqVar49.zzb()).a();
        b.C2317b c2317bA50 = b.a("pipelineAccelerationInferenceEvents");
        zzcq zzcqVar50 = new zzcq();
        zzcqVar50.zza(69);
        zzY = c2317bA50.b(zzcqVar50.zzb()).a();
        b.C2317b c2317bA51 = b.a("remoteConfigLogEvent");
        zzcq zzcqVar51 = new zzcq();
        zzcqVar51.zza(42);
        zzZ = c2317bA51.b(zzcqVar51.zzb()).a();
        b.C2317b c2317bA52 = b.a("inputImageConstructionLogEvent");
        zzcq zzcqVar52 = new zzcq();
        zzcqVar52.zza(50);
        zzaa = c2317bA52.b(zzcqVar52.zzb()).a();
        b.C2317b c2317bA53 = b.a("leakedHandleEvent");
        zzcq zzcqVar53 = new zzcq();
        zzcqVar53.zza(51);
        zzab = c2317bA53.b(zzcqVar53.zzb()).a();
        b.C2317b c2317bA54 = b.a("cameraSourceLogEvent");
        zzcq zzcqVar54 = new zzcq();
        zzcqVar54.zza(52);
        zzac = c2317bA54.b(zzcqVar54.zzb()).a();
        b.C2317b c2317bA55 = b.a("imageLabelOptionalModuleLogEvent");
        zzcq zzcqVar55 = new zzcq();
        zzcqVar55.zza(53);
        zzad = c2317bA55.b(zzcqVar55.zzb()).a();
        b.C2317b c2317bA56 = b.a("languageIdentificationOptionalModuleLogEvent");
        zzcq zzcqVar56 = new zzcq();
        zzcqVar56.zza(54);
        zzae = c2317bA56.b(zzcqVar56.zzb()).a();
        b.C2317b c2317bA57 = b.a("faceDetectionOptionalModuleLogEvent");
        zzcq zzcqVar57 = new zzcq();
        zzcqVar57.zza(60);
        zzaf = c2317bA57.b(zzcqVar57.zzb()).a();
        b.C2317b c2317bA58 = b.a("nlClassifierOptionalModuleLogEvent");
        zzcq zzcqVar58 = new zzcq();
        zzcqVar58.zza(55);
        zzag = c2317bA58.b(zzcqVar58.zzb()).a();
        b.C2317b c2317bA59 = b.a("nlClassifierClientLibraryLogEvent");
        zzcq zzcqVar59 = new zzcq();
        zzcqVar59.zza(56);
        zzah = c2317bA59.b(zzcqVar59.zzb()).a();
        b.C2317b c2317bA60 = b.a("accelerationAllowlistLogEvent");
        zzcq zzcqVar60 = new zzcq();
        zzcqVar60.zza(57);
        zzai = c2317bA60.b(zzcqVar60.zzb()).a();
        b.C2317b c2317bA61 = b.a("toxicityDetectionCreateEvent");
        zzcq zzcqVar61 = new zzcq();
        zzcqVar61.zza(62);
        zzaj = c2317bA61.b(zzcqVar61.zzb()).a();
        b.C2317b c2317bA62 = b.a("toxicityDetectionLoadEvent");
        zzcq zzcqVar62 = new zzcq();
        zzcqVar62.zza(63);
        zzak = c2317bA62.b(zzcqVar62.zzb()).a();
        b.C2317b c2317bA63 = b.a("toxicityDetectionInferenceEvent");
        zzcq zzcqVar63 = new zzcq();
        zzcqVar63.zza(64);
        zzal = c2317bA63.b(zzcqVar63.zzb()).a();
        b.C2317b c2317bA64 = b.a("barcodeDetectionOptionalModuleLogEvent");
        zzcq zzcqVar64 = new zzcq();
        zzcqVar64.zza(65);
        zzam = c2317bA64.b(zzcqVar64.zzb()).a();
        b.C2317b c2317bA65 = b.a("customImageLabelOptionalModuleLogEvent");
        zzcq zzcqVar65 = new zzcq();
        zzcqVar65.zza(66);
        zzan = c2317bA65.b(zzcqVar65.zzb()).a();
        b.C2317b c2317bA66 = b.a("codeScannerScanApiEvent");
        zzcq zzcqVar66 = new zzcq();
        zzcqVar66.zza(67);
        zzao = c2317bA66.b(zzcqVar66.zzb()).a();
        b.C2317b c2317bA67 = b.a("codeScannerOptionalModuleEvent");
        zzcq zzcqVar67 = new zzcq();
        zzcqVar67.zza(68);
        zzap = c2317bA67.b(zzcqVar67.zzb()).a();
        b.C2317b c2317bA68 = b.a("onDeviceExplicitContentCreateLogEvent");
        zzcq zzcqVar68 = new zzcq();
        zzcqVar68.zza(70);
        zzaq = c2317bA68.b(zzcqVar68.zzb()).a();
        b.C2317b c2317bA69 = b.a("onDeviceExplicitContentLoadLogEvent");
        zzcq zzcqVar69 = new zzcq();
        zzcqVar69.zza(71);
        zzar = c2317bA69.b(zzcqVar69.zzb()).a();
        b.C2317b c2317bA70 = b.a("onDeviceExplicitContentInferenceLogEvent");
        zzcq zzcqVar70 = new zzcq();
        zzcqVar70.zza(72);
        zzas = c2317bA70.b(zzcqVar70.zzb()).a();
        b.C2317b c2317bA71 = b.a("aggregatedOnDeviceExplicitContentLogEvent");
        zzcq zzcqVar71 = new zzcq();
        zzcqVar71.zza(73);
        zzat = c2317bA71.b(zzcqVar71.zzb()).a();
        b.C2317b c2317bA72 = b.a("onDeviceSelfieFaceCreateLogEvent");
        zzcq zzcqVar72 = new zzcq();
        zzcqVar72.zza(74);
        zzau = c2317bA72.b(zzcqVar72.zzb()).a();
        b.C2317b c2317bA73 = b.a("onDeviceSelfieFaceLoadLogEvent");
        zzcq zzcqVar73 = new zzcq();
        zzcqVar73.zza(75);
        zzav = c2317bA73.b(zzcqVar73.zzb()).a();
        b.C2317b c2317bA74 = b.a("onDeviceSelfieFaceLogEvent");
        zzcq zzcqVar74 = new zzcq();
        zzcqVar74.zza(76);
        zzaw = c2317bA74.b(zzcqVar74.zzb()).a();
        b.C2317b c2317bA75 = b.a("aggregatedOnDeviceSelfieFaceLogEvent");
        zzcq zzcqVar75 = new zzcq();
        zzcqVar75.zza(77);
        zzax = c2317bA75.b(zzcqVar75.zzb()).a();
        b.C2317b c2317bA76 = b.a("smartReplyOptionalModuleLogEvent");
        zzcq zzcqVar76 = new zzcq();
        zzcqVar76.zza(78);
        zzay = c2317bA76.b(zzcqVar76.zzb()).a();
    }

    private zzgq() {
    }

    @Override // rv.c
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) {
        zzkw zzkwVar = (zzkw) obj;
        d dVar = (d) obj2;
        dVar.add(zzb, zzkwVar.zzf());
        dVar.add(zzc, zzkwVar.zzc());
        dVar.add(zzd, (Object) null);
        dVar.add(zze, zzkwVar.zzb());
        dVar.add(zzf, (Object) null);
        dVar.add(zzg, (Object) null);
        dVar.add(zzh, (Object) null);
        dVar.add(zzi, (Object) null);
        dVar.add(zzj, zzkwVar.zzd());
        dVar.add(zzk, zzkwVar.zze());
        dVar.add(zzl, (Object) null);
        dVar.add(zzm, (Object) null);
        dVar.add(zzn, (Object) null);
        dVar.add(zzo, (Object) null);
        dVar.add(zzp, (Object) null);
        dVar.add(zzq, (Object) null);
        dVar.add(zzr, (Object) null);
        dVar.add(zzs, (Object) null);
        dVar.add(zzt, (Object) null);
        dVar.add(zzu, (Object) null);
        dVar.add(zzv, (Object) null);
        dVar.add(zzw, (Object) null);
        dVar.add(zzx, (Object) null);
        dVar.add(zzy, (Object) null);
        dVar.add(zzz, (Object) null);
        dVar.add(zzA, (Object) null);
        dVar.add(zzB, (Object) null);
        dVar.add(zzC, (Object) null);
        dVar.add(zzD, (Object) null);
        dVar.add(zzE, (Object) null);
        dVar.add(zzF, (Object) null);
        dVar.add(zzG, (Object) null);
        dVar.add(zzH, (Object) null);
        dVar.add(zzI, (Object) null);
        dVar.add(zzJ, (Object) null);
        dVar.add(zzK, (Object) null);
        dVar.add(zzL, (Object) null);
        dVar.add(zzM, (Object) null);
        dVar.add(zzN, (Object) null);
        dVar.add(zzO, (Object) null);
        dVar.add(zzP, (Object) null);
        dVar.add(zzQ, (Object) null);
        dVar.add(zzR, zzkwVar.zza());
        dVar.add(zzS, (Object) null);
        dVar.add(zzT, (Object) null);
        dVar.add(zzU, (Object) null);
        dVar.add(zzV, (Object) null);
        dVar.add(zzW, (Object) null);
        dVar.add(zzX, (Object) null);
        dVar.add(zzY, (Object) null);
        dVar.add(zzZ, (Object) null);
        dVar.add(zzaa, (Object) null);
        dVar.add(zzab, (Object) null);
        dVar.add(zzac, (Object) null);
        dVar.add(zzad, (Object) null);
        dVar.add(zzae, (Object) null);
        dVar.add(zzaf, (Object) null);
        dVar.add(zzag, (Object) null);
        dVar.add(zzah, (Object) null);
        dVar.add(zzai, (Object) null);
        dVar.add(zzaj, (Object) null);
        dVar.add(zzak, (Object) null);
        dVar.add(zzal, (Object) null);
        dVar.add(zzam, (Object) null);
        dVar.add(zzan, (Object) null);
        dVar.add(zzao, (Object) null);
        dVar.add(zzap, (Object) null);
        dVar.add(zzaq, (Object) null);
        dVar.add(zzar, (Object) null);
        dVar.add(zzas, (Object) null);
        dVar.add(zzat, (Object) null);
        dVar.add(zzau, (Object) null);
        dVar.add(zzav, (Object) null);
        dVar.add(zzaw, (Object) null);
        dVar.add(zzax, (Object) null);
        dVar.add(zzay, (Object) null);
    }
}
