package com.google.android.gms.internal.mlkit_vision_document_scanner;

import com.plaid.internal.EnumC4419g;
import rv.b;
import rv.c;
import rv.d;

/* JADX INFO: loaded from: classes5.dex */
final class zzgm implements c {
    private static final b zzA;
    private static final b zzB;
    private static final b zzC;
    private static final b zzD;
    private static final b zzE;
    private static final b zzF;
    private static final b zzG;
    private static final b zzH;
    private static final b zzI;
    private static final b zzJ;
    private static final b zzK;
    private static final b zzL;
    private static final b zzM;
    private static final b zzN;
    private static final b zzO;
    private static final b zzP;
    private static final b zzQ;
    private static final b zzR;
    private static final b zzS;
    private static final b zzT;
    private static final b zzU;
    private static final b zzV;
    private static final b zzW;
    private static final b zzX;
    private static final b zzY;
    private static final b zzZ;
    static final zzgm zza = new zzgm();
    private static final b zzaA;
    private static final b zzaB;
    private static final b zzaC;
    private static final b zzaD;
    private static final b zzaE;
    private static final b zzaF;
    private static final b zzaG;
    private static final b zzaH;
    private static final b zzaI;
    private static final b zzaJ;
    private static final b zzaK;
    private static final b zzaL;
    private static final b zzaM;
    private static final b zzaN;
    private static final b zzaO;
    private static final b zzaP;
    private static final b zzaQ;
    private static final b zzaR;
    private static final b zzaS;
    private static final b zzaT;
    private static final b zzaU;
    private static final b zzaV;
    private static final b zzaW;
    private static final b zzaX;
    private static final b zzaY;
    private static final b zzaZ;
    private static final b zzaa;
    private static final b zzab;
    private static final b zzac;
    private static final b zzad;
    private static final b zzae;
    private static final b zzaf;
    private static final b zzag;
    private static final b zzah;
    private static final b zzai;
    private static final b zzaj;
    private static final b zzak;
    private static final b zzal;
    private static final b zzam;
    private static final b zzan;
    private static final b zzao;
    private static final b zzap;
    private static final b zzaq;
    private static final b zzar;
    private static final b zzas;
    private static final b zzat;
    private static final b zzau;
    private static final b zzav;
    private static final b zzaw;
    private static final b zzax;
    private static final b zzay;
    private static final b zzaz;
    private static final b zzb;
    private static final b zzbA;
    private static final b zzbB;
    private static final b zzbC;
    private static final b zzbD;
    private static final b zzbE;
    private static final b zzbF;
    private static final b zzbG;
    private static final b zzbH;
    private static final b zzbI;
    private static final b zzbJ;
    private static final b zzbK;
    private static final b zzbL;
    private static final b zzbM;
    private static final b zzbN;
    private static final b zzbO;
    private static final b zzbP;
    private static final b zzbQ;
    private static final b zzbR;
    private static final b zzbS;
    private static final b zzbT;
    private static final b zzba;
    private static final b zzbb;
    private static final b zzbc;
    private static final b zzbd;
    private static final b zzbe;
    private static final b zzbf;
    private static final b zzbg;
    private static final b zzbh;
    private static final b zzbi;
    private static final b zzbj;
    private static final b zzbk;
    private static final b zzbl;
    private static final b zzbm;
    private static final b zzbn;
    private static final b zzbo;
    private static final b zzbp;
    private static final b zzbq;
    private static final b zzbr;
    private static final b zzbs;
    private static final b zzbt;
    private static final b zzbu;
    private static final b zzbv;
    private static final b zzbw;
    private static final b zzbx;
    private static final b zzby;
    private static final b zzbz;
    private static final b zzc;
    private static final b zzd;
    private static final b zze;
    private static final b zzf;
    private static final b zzg;
    private static final b zzh;
    private static final b zzi;
    private static final b zzj;
    private static final b zzk;
    private static final b zzl;
    private static final b zzm;
    private static final b zzn;
    private static final b zzo;
    private static final b zzp;
    private static final b zzq;
    private static final b zzr;
    private static final b zzs;
    private static final b zzt;
    private static final b zzu;
    private static final b zzv;
    private static final b zzw;
    private static final b zzx;
    private static final b zzy;
    private static final b zzz;

    static {
        b.C2317b c2317bA = b.a("systemInfo");
        zzal zzalVar = new zzal();
        zzalVar.zza(1);
        zzb = c2317bA.b(zzalVar.zzb()).a();
        b.C2317b c2317bA2 = b.a("eventName");
        zzal zzalVar2 = new zzal();
        zzalVar2.zza(2);
        zzc = c2317bA2.b(zzalVar2.zzb()).a();
        b.C2317b c2317bA3 = b.a("isThickClient");
        zzal zzalVar3 = new zzal();
        zzalVar3.zza(37);
        zzd = c2317bA3.b(zzalVar3.zzb()).a();
        b.C2317b c2317bA4 = b.a("clientType");
        zzal zzalVar4 = new zzal();
        zzalVar4.zza(61);
        zze = c2317bA4.b(zzalVar4.zzb()).a();
        b.C2317b c2317bA5 = b.a("modelDownloadLogEvent");
        zzal zzalVar5 = new zzal();
        zzalVar5.zza(3);
        zzf = c2317bA5.b(zzalVar5.zzb()).a();
        b.C2317b c2317bA6 = b.a("customModelLoadLogEvent");
        zzal zzalVar6 = new zzal();
        zzalVar6.zza(20);
        zzg = c2317bA6.b(zzalVar6.zzb()).a();
        b.C2317b c2317bA7 = b.a("customModelInferenceLogEvent");
        zzal zzalVar7 = new zzal();
        zzalVar7.zza(4);
        zzh = c2317bA7.b(zzalVar7.zzb()).a();
        b.C2317b c2317bA8 = b.a("customModelCreateLogEvent");
        zzal zzalVar8 = new zzal();
        zzalVar8.zza(29);
        zzi = c2317bA8.b(zzalVar8.zzb()).a();
        b.C2317b c2317bA9 = b.a("onDeviceFaceDetectionLogEvent");
        zzal zzalVar9 = new zzal();
        zzalVar9.zza(5);
        zzj = c2317bA9.b(zzalVar9.zzb()).a();
        b.C2317b c2317bA10 = b.a("onDeviceFaceLoadLogEvent");
        zzal zzalVar10 = new zzal();
        zzalVar10.zza(59);
        zzk = c2317bA10.b(zzalVar10.zzb()).a();
        b.C2317b c2317bA11 = b.a("onDeviceTextDetectionLogEvent");
        zzal zzalVar11 = new zzal();
        zzalVar11.zza(6);
        zzl = c2317bA11.b(zzalVar11.zzb()).a();
        b.C2317b c2317bA12 = b.a("onDeviceTextDetectionLoadLogEvent");
        zzal zzalVar12 = new zzal();
        zzalVar12.zza(79);
        zzm = c2317bA12.b(zzalVar12.zzb()).a();
        b.C2317b c2317bA13 = b.a("onDeviceBarcodeDetectionLogEvent");
        zzal zzalVar13 = new zzal();
        zzalVar13.zza(7);
        zzn = c2317bA13.b(zzalVar13.zzb()).a();
        b.C2317b c2317bA14 = b.a("onDeviceBarcodeLoadLogEvent");
        zzal zzalVar14 = new zzal();
        zzalVar14.zza(58);
        zzo = c2317bA14.b(zzalVar14.zzb()).a();
        b.C2317b c2317bA15 = b.a("onDeviceImageLabelCreateLogEvent");
        zzal zzalVar15 = new zzal();
        zzalVar15.zza(48);
        zzp = c2317bA15.b(zzalVar15.zzb()).a();
        b.C2317b c2317bA16 = b.a("onDeviceImageLabelLoadLogEvent");
        zzal zzalVar16 = new zzal();
        zzalVar16.zza(49);
        zzq = c2317bA16.b(zzalVar16.zzb()).a();
        b.C2317b c2317bA17 = b.a("onDeviceImageLabelDetectionLogEvent");
        zzal zzalVar17 = new zzal();
        zzalVar17.zza(18);
        zzr = c2317bA17.b(zzalVar17.zzb()).a();
        b.C2317b c2317bA18 = b.a("onDeviceObjectCreateLogEvent");
        zzal zzalVar18 = new zzal();
        zzalVar18.zza(26);
        zzs = c2317bA18.b(zzalVar18.zzb()).a();
        b.C2317b c2317bA19 = b.a("onDeviceObjectLoadLogEvent");
        zzal zzalVar19 = new zzal();
        zzalVar19.zza(27);
        zzt = c2317bA19.b(zzalVar19.zzb()).a();
        b.C2317b c2317bA20 = b.a("onDeviceObjectInferenceLogEvent");
        zzal zzalVar20 = new zzal();
        zzalVar20.zza(28);
        zzu = c2317bA20.b(zzalVar20.zzb()).a();
        b.C2317b c2317bA21 = b.a("onDevicePoseDetectionLogEvent");
        zzal zzalVar21 = new zzal();
        zzalVar21.zza(44);
        zzv = c2317bA21.b(zzalVar21.zzb()).a();
        b.C2317b c2317bA22 = b.a("onDeviceSegmentationLogEvent");
        zzal zzalVar22 = new zzal();
        zzalVar22.zza(45);
        zzw = c2317bA22.b(zzalVar22.zzb()).a();
        b.C2317b c2317bA23 = b.a("onDeviceSmartReplyLogEvent");
        zzal zzalVar23 = new zzal();
        zzalVar23.zza(19);
        zzx = c2317bA23.b(zzalVar23.zzb()).a();
        b.C2317b c2317bA24 = b.a("onDeviceLanguageIdentificationLogEvent");
        zzal zzalVar24 = new zzal();
        zzalVar24.zza(21);
        zzy = c2317bA24.b(zzalVar24.zzb()).a();
        b.C2317b c2317bA25 = b.a("onDeviceTranslationLogEvent");
        zzal zzalVar25 = new zzal();
        zzalVar25.zza(22);
        zzz = c2317bA25.b(zzalVar25.zzb()).a();
        b.C2317b c2317bA26 = b.a("cloudFaceDetectionLogEvent");
        zzal zzalVar26 = new zzal();
        zzalVar26.zza(8);
        zzA = c2317bA26.b(zzalVar26.zzb()).a();
        b.C2317b c2317bA27 = b.a("cloudCropHintDetectionLogEvent");
        zzal zzalVar27 = new zzal();
        zzalVar27.zza(9);
        zzB = c2317bA27.b(zzalVar27.zzb()).a();
        b.C2317b c2317bA28 = b.a("cloudDocumentTextDetectionLogEvent");
        zzal zzalVar28 = new zzal();
        zzalVar28.zza(10);
        zzC = c2317bA28.b(zzalVar28.zzb()).a();
        b.C2317b c2317bA29 = b.a("cloudImagePropertiesDetectionLogEvent");
        zzal zzalVar29 = new zzal();
        zzalVar29.zza(11);
        zzD = c2317bA29.b(zzalVar29.zzb()).a();
        b.C2317b c2317bA30 = b.a("cloudImageLabelDetectionLogEvent");
        zzal zzalVar30 = new zzal();
        zzalVar30.zza(12);
        zzE = c2317bA30.b(zzalVar30.zzb()).a();
        b.C2317b c2317bA31 = b.a("cloudLandmarkDetectionLogEvent");
        zzal zzalVar31 = new zzal();
        zzalVar31.zza(13);
        zzF = c2317bA31.b(zzalVar31.zzb()).a();
        b.C2317b c2317bA32 = b.a("cloudLogoDetectionLogEvent");
        zzal zzalVar32 = new zzal();
        zzalVar32.zza(14);
        zzG = c2317bA32.b(zzalVar32.zzb()).a();
        b.C2317b c2317bA33 = b.a("cloudSafeSearchDetectionLogEvent");
        zzal zzalVar33 = new zzal();
        zzalVar33.zza(15);
        zzH = c2317bA33.b(zzalVar33.zzb()).a();
        b.C2317b c2317bA34 = b.a("cloudTextDetectionLogEvent");
        zzal zzalVar34 = new zzal();
        zzalVar34.zza(16);
        zzI = c2317bA34.b(zzalVar34.zzb()).a();
        b.C2317b c2317bA35 = b.a("cloudWebSearchDetectionLogEvent");
        zzal zzalVar35 = new zzal();
        zzalVar35.zza(17);
        zzJ = c2317bA35.b(zzalVar35.zzb()).a();
        b.C2317b c2317bA36 = b.a("automlImageLabelingCreateLogEvent");
        zzal zzalVar36 = new zzal();
        zzalVar36.zza(23);
        zzK = c2317bA36.b(zzalVar36.zzb()).a();
        b.C2317b c2317bA37 = b.a("automlImageLabelingLoadLogEvent");
        zzal zzalVar37 = new zzal();
        zzalVar37.zza(24);
        zzL = c2317bA37.b(zzalVar37.zzb()).a();
        b.C2317b c2317bA38 = b.a("automlImageLabelingInferenceLogEvent");
        zzal zzalVar38 = new zzal();
        zzalVar38.zza(25);
        zzM = c2317bA38.b(zzalVar38.zzb()).a();
        b.C2317b c2317bA39 = b.a("isModelDownloadedLogEvent");
        zzal zzalVar39 = new zzal();
        zzalVar39.zza(39);
        zzN = c2317bA39.b(zzalVar39.zzb()).a();
        b.C2317b c2317bA40 = b.a("deleteModelLogEvent");
        zzal zzalVar40 = new zzal();
        zzalVar40.zza(40);
        zzO = c2317bA40.b(zzalVar40.zzb()).a();
        b.C2317b c2317bA41 = b.a("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzal zzalVar41 = new zzal();
        zzalVar41.zza(30);
        zzP = c2317bA41.b(zzalVar41.zzb()).a();
        b.C2317b c2317bA42 = b.a("aggregatedCustomModelInferenceLogEvent");
        zzal zzalVar42 = new zzal();
        zzalVar42.zza(31);
        zzQ = c2317bA42.b(zzalVar42.zzb()).a();
        b.C2317b c2317bA43 = b.a("aggregatedOnDeviceFaceDetectionLogEvent");
        zzal zzalVar43 = new zzal();
        zzalVar43.zza(32);
        zzR = c2317bA43.b(zzalVar43.zzb()).a();
        b.C2317b c2317bA44 = b.a("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzal zzalVar44 = new zzal();
        zzalVar44.zza(33);
        zzS = c2317bA44.b(zzalVar44.zzb()).a();
        b.C2317b c2317bA45 = b.a("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzal zzalVar45 = new zzal();
        zzalVar45.zza(34);
        zzT = c2317bA45.b(zzalVar45.zzb()).a();
        b.C2317b c2317bA46 = b.a("aggregatedOnDeviceObjectInferenceLogEvent");
        zzal zzalVar46 = new zzal();
        zzalVar46.zza(35);
        zzU = c2317bA46.b(zzalVar46.zzb()).a();
        b.C2317b c2317bA47 = b.a("aggregatedOnDeviceTextDetectionLogEvent");
        zzal zzalVar47 = new zzal();
        zzalVar47.zza(36);
        zzV = c2317bA47.b(zzalVar47.zzb()).a();
        b.C2317b c2317bA48 = b.a("aggregatedOnDevicePoseDetectionLogEvent");
        zzal zzalVar48 = new zzal();
        zzalVar48.zza(46);
        zzW = c2317bA48.b(zzalVar48.zzb()).a();
        b.C2317b c2317bA49 = b.a("aggregatedOnDeviceSegmentationLogEvent");
        zzal zzalVar49 = new zzal();
        zzalVar49.zza(47);
        zzX = c2317bA49.b(zzalVar49.zzb()).a();
        b.C2317b c2317bA50 = b.a("pipelineAccelerationInferenceEvents");
        zzal zzalVar50 = new zzal();
        zzalVar50.zza(69);
        zzY = c2317bA50.b(zzalVar50.zzb()).a();
        b.C2317b c2317bA51 = b.a("remoteConfigLogEvent");
        zzal zzalVar51 = new zzal();
        zzalVar51.zza(42);
        zzZ = c2317bA51.b(zzalVar51.zzb()).a();
        b.C2317b c2317bA52 = b.a("inputImageConstructionLogEvent");
        zzal zzalVar52 = new zzal();
        zzalVar52.zza(50);
        zzaa = c2317bA52.b(zzalVar52.zzb()).a();
        b.C2317b c2317bA53 = b.a("leakedHandleEvent");
        zzal zzalVar53 = new zzal();
        zzalVar53.zza(51);
        zzab = c2317bA53.b(zzalVar53.zzb()).a();
        b.C2317b c2317bA54 = b.a("cameraSourceLogEvent");
        zzal zzalVar54 = new zzal();
        zzalVar54.zza(52);
        zzac = c2317bA54.b(zzalVar54.zzb()).a();
        b.C2317b c2317bA55 = b.a("imageLabelOptionalModuleLogEvent");
        zzal zzalVar55 = new zzal();
        zzalVar55.zza(53);
        zzad = c2317bA55.b(zzalVar55.zzb()).a();
        b.C2317b c2317bA56 = b.a("languageIdentificationOptionalModuleLogEvent");
        zzal zzalVar56 = new zzal();
        zzalVar56.zza(54);
        zzae = c2317bA56.b(zzalVar56.zzb()).a();
        b.C2317b c2317bA57 = b.a("faceDetectionOptionalModuleLogEvent");
        zzal zzalVar57 = new zzal();
        zzalVar57.zza(60);
        zzaf = c2317bA57.b(zzalVar57.zzb()).a();
        b.C2317b c2317bA58 = b.a("documentDetectionOptionalModuleLogEvent");
        zzal zzalVar58 = new zzal();
        zzalVar58.zza(85);
        zzag = c2317bA58.b(zzalVar58.zzb()).a();
        b.C2317b c2317bA59 = b.a("documentCroppingOptionalModuleLogEvent");
        zzal zzalVar59 = new zzal();
        zzalVar59.zza(86);
        zzah = c2317bA59.b(zzalVar59.zzb()).a();
        b.C2317b c2317bA60 = b.a("documentEnhancementOptionalModuleLogEvent");
        zzal zzalVar60 = new zzal();
        zzalVar60.zza(87);
        zzai = c2317bA60.b(zzalVar60.zzb()).a();
        b.C2317b c2317bA61 = b.a("nlClassifierOptionalModuleLogEvent");
        zzal zzalVar61 = new zzal();
        zzalVar61.zza(55);
        zzaj = c2317bA61.b(zzalVar61.zzb()).a();
        b.C2317b c2317bA62 = b.a("nlClassifierClientLibraryLogEvent");
        zzal zzalVar62 = new zzal();
        zzalVar62.zza(56);
        zzak = c2317bA62.b(zzalVar62.zzb()).a();
        b.C2317b c2317bA63 = b.a("accelerationAllowlistLogEvent");
        zzal zzalVar63 = new zzal();
        zzalVar63.zza(57);
        zzal = c2317bA63.b(zzalVar63.zzb()).a();
        b.C2317b c2317bA64 = b.a("toxicityDetectionCreateEvent");
        zzal zzalVar64 = new zzal();
        zzalVar64.zza(62);
        zzam = c2317bA64.b(zzalVar64.zzb()).a();
        b.C2317b c2317bA65 = b.a("toxicityDetectionLoadEvent");
        zzal zzalVar65 = new zzal();
        zzalVar65.zza(63);
        zzan = c2317bA65.b(zzalVar65.zzb()).a();
        b.C2317b c2317bA66 = b.a("toxicityDetectionInferenceEvent");
        zzal zzalVar66 = new zzal();
        zzalVar66.zza(64);
        zzao = c2317bA66.b(zzalVar66.zzb()).a();
        b.C2317b c2317bA67 = b.a("barcodeDetectionOptionalModuleLogEvent");
        zzal zzalVar67 = new zzal();
        zzalVar67.zza(65);
        zzap = c2317bA67.b(zzalVar67.zzb()).a();
        b.C2317b c2317bA68 = b.a("customImageLabelOptionalModuleLogEvent");
        zzal zzalVar68 = new zzal();
        zzalVar68.zza(66);
        zzaq = c2317bA68.b(zzalVar68.zzb()).a();
        b.C2317b c2317bA69 = b.a("codeScannerScanApiEvent");
        zzal zzalVar69 = new zzal();
        zzalVar69.zza(67);
        zzar = c2317bA69.b(zzalVar69.zzb()).a();
        b.C2317b c2317bA70 = b.a("codeScannerOptionalModuleEvent");
        zzal zzalVar70 = new zzal();
        zzalVar70.zza(68);
        zzas = c2317bA70.b(zzalVar70.zzb()).a();
        b.C2317b c2317bA71 = b.a("onDeviceExplicitContentCreateLogEvent");
        zzal zzalVar71 = new zzal();
        zzalVar71.zza(70);
        zzat = c2317bA71.b(zzalVar71.zzb()).a();
        b.C2317b c2317bA72 = b.a("onDeviceExplicitContentLoadLogEvent");
        zzal zzalVar72 = new zzal();
        zzalVar72.zza(71);
        zzau = c2317bA72.b(zzalVar72.zzb()).a();
        b.C2317b c2317bA73 = b.a("onDeviceExplicitContentInferenceLogEvent");
        zzal zzalVar73 = new zzal();
        zzalVar73.zza(72);
        zzav = c2317bA73.b(zzalVar73.zzb()).a();
        b.C2317b c2317bA74 = b.a("aggregatedOnDeviceExplicitContentLogEvent");
        zzal zzalVar74 = new zzal();
        zzalVar74.zza(73);
        zzaw = c2317bA74.b(zzalVar74.zzb()).a();
        b.C2317b c2317bA75 = b.a("onDeviceFaceMeshCreateLogEvent");
        zzal zzalVar75 = new zzal();
        zzalVar75.zza(74);
        zzax = c2317bA75.b(zzalVar75.zzb()).a();
        b.C2317b c2317bA76 = b.a("onDeviceFaceMeshLoadLogEvent");
        zzal zzalVar76 = new zzal();
        zzalVar76.zza(75);
        zzay = c2317bA76.b(zzalVar76.zzb()).a();
        b.C2317b c2317bA77 = b.a("onDeviceFaceMeshLogEvent");
        zzal zzalVar77 = new zzal();
        zzalVar77.zza(76);
        zzaz = c2317bA77.b(zzalVar77.zzb()).a();
        b.C2317b c2317bA78 = b.a("aggregatedOnDeviceFaceMeshLogEvent");
        zzal zzalVar78 = new zzal();
        zzalVar78.zza(77);
        zzaA = c2317bA78.b(zzalVar78.zzb()).a();
        b.C2317b c2317bA79 = b.a("smartReplyOptionalModuleLogEvent");
        zzal zzalVar79 = new zzal();
        zzalVar79.zza(78);
        zzaB = c2317bA79.b(zzalVar79.zzb()).a();
        b.C2317b c2317bA80 = b.a("textDetectionOptionalModuleLogEvent");
        zzal zzalVar80 = new zzal();
        zzalVar80.zza(80);
        zzaC = c2317bA80.b(zzalVar80.zzb()).a();
        b.C2317b c2317bA81 = b.a("onDeviceImageQualityAnalysisCreateLogEvent");
        zzal zzalVar81 = new zzal();
        zzalVar81.zza(81);
        zzaD = c2317bA81.b(zzalVar81.zzb()).a();
        b.C2317b c2317bA82 = b.a("onDeviceImageQualityAnalysisLoadLogEvent");
        zzal zzalVar82 = new zzal();
        zzalVar82.zza(82);
        zzaE = c2317bA82.b(zzalVar82.zzb()).a();
        b.C2317b c2317bA83 = b.a("onDeviceImageQualityAnalysisLogEvent");
        zzal zzalVar83 = new zzal();
        zzalVar83.zza(83);
        zzaF = c2317bA83.b(zzalVar83.zzb()).a();
        b.C2317b c2317bA84 = b.a("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zzal zzalVar84 = new zzal();
        zzalVar84.zza(84);
        zzaG = c2317bA84.b(zzalVar84.zzb()).a();
        b.C2317b c2317bA85 = b.a("imageQualityAnalysisOptionalModuleLogEvent");
        zzal zzalVar85 = new zzal();
        zzalVar85.zza(88);
        zzaH = c2317bA85.b(zzalVar85.zzb()).a();
        b.C2317b c2317bA86 = b.a("imageCaptioningOptionalModuleLogEvent");
        zzal zzalVar86 = new zzal();
        zzalVar86.zza(89);
        zzaI = c2317bA86.b(zzalVar86.zzb()).a();
        b.C2317b c2317bA87 = b.a("onDeviceImageCaptioningCreateLogEvent");
        zzal zzalVar87 = new zzal();
        zzalVar87.zza(90);
        zzaJ = c2317bA87.b(zzalVar87.zzb()).a();
        b.C2317b c2317bA88 = b.a("onDeviceImageCaptioningLoadLogEvent");
        zzal zzalVar88 = new zzal();
        zzalVar88.zza(91);
        zzaK = c2317bA88.b(zzalVar88.zzb()).a();
        b.C2317b c2317bA89 = b.a("onDeviceImageCaptioningInferenceLogEvent");
        zzal zzalVar89 = new zzal();
        zzalVar89.zza(92);
        zzaL = c2317bA89.b(zzalVar89.zzb()).a();
        b.C2317b c2317bA90 = b.a("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zzal zzalVar90 = new zzal();
        zzalVar90.zza(93);
        zzaM = c2317bA90.b(zzalVar90.zzb()).a();
        b.C2317b c2317bA91 = b.a("onDeviceDocumentDetectionCreateLogEvent");
        zzal zzalVar91 = new zzal();
        zzalVar91.zza(94);
        zzaN = c2317bA91.b(zzalVar91.zzb()).a();
        b.C2317b c2317bA92 = b.a("onDeviceDocumentDetectionLoadLogEvent");
        zzal zzalVar92 = new zzal();
        zzalVar92.zza(95);
        zzaO = c2317bA92.b(zzalVar92.zzb()).a();
        b.C2317b c2317bA93 = b.a("onDeviceDocumentDetectionLogEvent");
        zzal zzalVar93 = new zzal();
        zzalVar93.zza(96);
        zzaP = c2317bA93.b(zzalVar93.zzb()).a();
        b.C2317b c2317bA94 = b.a("aggregatedOnDeviceDocumentDetectionLogEvent");
        zzal zzalVar94 = new zzal();
        zzalVar94.zza(97);
        zzaQ = c2317bA94.b(zzalVar94.zzb()).a();
        b.C2317b c2317bA95 = b.a("onDeviceDocumentCroppingCreateLogEvent");
        zzal zzalVar95 = new zzal();
        zzalVar95.zza(98);
        zzaR = c2317bA95.b(zzalVar95.zzb()).a();
        b.C2317b c2317bA96 = b.a("onDeviceDocumentCroppingLoadLogEvent");
        zzal zzalVar96 = new zzal();
        zzalVar96.zza(99);
        zzaS = c2317bA96.b(zzalVar96.zzb()).a();
        b.C2317b c2317bA97 = b.a("onDeviceDocumentCroppingLogEvent");
        zzal zzalVar97 = new zzal();
        zzalVar97.zza(100);
        zzaT = c2317bA97.b(zzalVar97.zzb()).a();
        b.C2317b c2317bA98 = b.a("aggregatedOnDeviceDocumentCroppingLogEvent");
        zzal zzalVar98 = new zzal();
        zzalVar98.zza(101);
        zzaU = c2317bA98.b(zzalVar98.zzb()).a();
        b.C2317b c2317bA99 = b.a("onDeviceDocumentEnhancementCreateLogEvent");
        zzal zzalVar99 = new zzal();
        zzalVar99.zza(102);
        zzaV = c2317bA99.b(zzalVar99.zzb()).a();
        b.C2317b c2317bA100 = b.a("onDeviceDocumentEnhancementLoadLogEvent");
        zzal zzalVar100 = new zzal();
        zzalVar100.zza(103);
        zzaW = c2317bA100.b(zzalVar100.zzb()).a();
        b.C2317b c2317bA101 = b.a("onDeviceDocumentEnhancementLogEvent");
        zzal zzalVar101 = new zzal();
        zzalVar101.zza(104);
        zzaX = c2317bA101.b(zzalVar101.zzb()).a();
        b.C2317b c2317bA102 = b.a("aggregatedOnDeviceDocumentEnhancementLogEvent");
        zzal zzalVar102 = new zzal();
        zzalVar102.zza(105);
        zzaY = c2317bA102.b(zzalVar102.zzb()).a();
        b.C2317b c2317bA103 = b.a("scannerAutoZoomEvent");
        zzal zzalVar103 = new zzal();
        zzalVar103.zza(106);
        zzaZ = c2317bA103.b(zzalVar103.zzb()).a();
        b.C2317b c2317bA104 = b.a("lowLightAutoExposureComputationEvent");
        zzal zzalVar104 = new zzal();
        zzalVar104.zza(107);
        zzba = c2317bA104.b(zzalVar104.zzb()).a();
        b.C2317b c2317bA105 = b.a("lowLightFrameProcessEvent");
        zzal zzalVar105 = new zzal();
        zzalVar105.zza(108);
        zzbb = c2317bA105.b(zzalVar105.zzb()).a();
        b.C2317b c2317bA106 = b.a("lowLightSceneDetectionEvent");
        zzal zzalVar106 = new zzal();
        zzalVar106.zza(109);
        zzbc = c2317bA106.b(zzalVar106.zzb()).a();
        b.C2317b c2317bA107 = b.a("onDeviceStainRemovalLogEvent");
        zzal zzalVar107 = new zzal();
        zzalVar107.zza(110);
        zzbd = c2317bA107.b(zzalVar107.zzb()).a();
        b.C2317b c2317bA108 = b.a("aggregatedOnDeviceStainRemovalLogEvent");
        zzal zzalVar108 = new zzal();
        zzalVar108.zza(111);
        zzbe = c2317bA108.b(zzalVar108.zzb()).a();
        b.C2317b c2317bA109 = b.a("stainRemovalOptionalModuleLogEvent");
        zzal zzalVar109 = new zzal();
        zzalVar109.zza(112);
        zzbf = c2317bA109.b(zzalVar109.zzb()).a();
        b.C2317b c2317bA110 = b.a("onDeviceShadowRemovalLogEvent");
        zzal zzalVar110 = new zzal();
        zzalVar110.zza(113);
        zzbg = c2317bA110.b(zzalVar110.zzb()).a();
        b.C2317b c2317bA111 = b.a("aggregatedOnDeviceShadowRemovalLogEvent");
        zzal zzalVar111 = new zzal();
        zzalVar111.zza(114);
        zzbh = c2317bA111.b(zzalVar111.zzb()).a();
        b.C2317b c2317bA112 = b.a("shadowRemovalOptionalModuleLogEvent");
        zzal zzalVar112 = new zzal();
        zzalVar112.zza(115);
        zzbi = c2317bA112.b(zzalVar112.zzb()).a();
        b.C2317b c2317bA113 = b.a("onDeviceDigitalInkSegmentationLogEvent");
        zzal zzalVar113 = new zzal();
        zzalVar113.zza(116);
        zzbj = c2317bA113.b(zzalVar113.zzb()).a();
        b.C2317b c2317bA114 = b.a("onDeviceDocumentScannerStartLogEvent");
        zzal zzalVar114 = new zzal();
        zzalVar114.zza(117);
        zzbk = c2317bA114.b(zzalVar114.zzb()).a();
        b.C2317b c2317bA115 = b.a("onDeviceDocumentScannerFinishLogEvent");
        zzal zzalVar115 = new zzal();
        zzalVar115.zza(118);
        zzbl = c2317bA115.b(zzalVar115.zzb()).a();
        b.C2317b c2317bA116 = b.a("onDeviceDocumentScannerUiStartLogEvent");
        zzal zzalVar116 = new zzal();
        zzalVar116.zza(119);
        zzbm = c2317bA116.b(zzalVar116.zzb()).a();
        b.C2317b c2317bA117 = b.a("onDeviceDocumentScannerUiFinishLogEvent");
        zzal zzalVar117 = new zzal();
        zzalVar117.zza(120);
        zzbn = c2317bA117.b(zzalVar117.zzb()).a();
        b.C2317b c2317bA118 = b.a("documentScannerUiOptionalModuleSessionStartLogEvent");
        zzal zzalVar118 = new zzal();
        zzalVar118.zza(121);
        zzbo = c2317bA118.b(zzalVar118.zzb()).a();
        b.C2317b c2317bA119 = b.a("documentScannerUiOptionalModuleSessionFinishLogEvent");
        zzal zzalVar119 = new zzal();
        zzalVar119.zza(122);
        zzbp = c2317bA119.b(zzalVar119.zzb()).a();
        b.C2317b c2317bA120 = b.a("onDeviceDocumentScannerUiCreateLogEvent");
        zzal zzalVar120 = new zzal();
        zzalVar120.zza(123);
        zzbq = c2317bA120.b(zzalVar120.zzb()).a();
        b.C2317b c2317bA121 = b.a("onDeviceSubjectSegmentationCreateLogEvent");
        zzal zzalVar121 = new zzal();
        zzalVar121.zza(124);
        zzbr = c2317bA121.b(zzalVar121.zzb()).a();
        b.C2317b c2317bA122 = b.a("onDeviceSubjectSegmentationLoadLogEvent");
        zzal zzalVar122 = new zzal();
        zzalVar122.zza(125);
        zzbs = c2317bA122.b(zzalVar122.zzb()).a();
        b.C2317b c2317bA123 = b.a("onDeviceSubjectSegmentationInferenceLogEvent");
        zzal zzalVar123 = new zzal();
        zzalVar123.zza(126);
        zzbt = c2317bA123.b(zzalVar123.zzb()).a();
        b.C2317b c2317bA124 = b.a("aggregatedOnDeviceSubjectSegmentationLogEvent");
        zzal zzalVar124 = new zzal();
        zzalVar124.zza(127);
        zzbu = c2317bA124.b(zzalVar124.zzb()).a();
        b.C2317b c2317bA125 = b.a("subjectSegmentationOptionalModuleLogEvent");
        zzal zzalVar125 = new zzal();
        zzalVar125.zza(128);
        zzbv = c2317bA125.b(zzalVar125.zzb()).a();
        b.C2317b c2317bA126 = b.a("documentScannerUiModuleScreenViewEvent");
        zzal zzalVar126 = new zzal();
        zzalVar126.zza(EnumC4419g.SDK_ASSET_ILLUSTRATION_FORM_VALUE);
        zzbw = c2317bA126.b(zzalVar126.zzb()).a();
        b.C2317b c2317bA127 = b.a("documentScannerUiModuleScreenClickEvent");
        zzal zzalVar127 = new zzal();
        zzalVar127.zza(EnumC4419g.SDK_ASSET_ILLUSTRATION_CONSUMER_VALUE);
        zzbx = c2317bA127.b(zzalVar127.zzb()).a();
        b.C2317b c2317bA128 = b.a("documentScannerUiModuleScreenErrorEvent");
        zzal zzalVar128 = new zzal();
        zzalVar128.zza(131);
        zzby = c2317bA128.b(zzalVar128.zzb()).a();
        b.C2317b c2317bA129 = b.a("documentScannerUiModuleScreenTransitionEvent");
        zzal zzalVar129 = new zzal();
        zzalVar129.zza(144);
        zzbz = c2317bA129.b(zzalVar129.zzb()).a();
        b.C2317b c2317bA130 = b.a("documentScannerUiModulePreviewScreenUserWaitingEvent");
        zzal zzalVar130 = new zzal();
        zzalVar130.zza(145);
        zzbA = c2317bA130.b(zzalVar130.zzb()).a();
        b.C2317b c2317bA131 = b.a("documentScannerUiModulePageProcessingEvent");
        zzal zzalVar131 = new zzal();
        zzalVar131.zza(146);
        zzbB = c2317bA131.b(zzalVar131.zzb()).a();
        b.C2317b c2317bA132 = b.a("sapiSummarizationInferenceEvent");
        zzal zzalVar132 = new zzal();
        zzalVar132.zza(132);
        zzbC = c2317bA132.b(zzalVar132.zzb()).a();
        b.C2317b c2317bA133 = b.a("sapiProofreadingInferenceEvent");
        zzal zzalVar133 = new zzal();
        zzalVar133.zza(133);
        zzbD = c2317bA133.b(zzalVar133.zzb()).a();
        b.C2317b c2317bA134 = b.a("sapiRewritingInferenceEvent");
        zzal zzalVar134 = new zzal();
        zzalVar134.zza(134);
        zzbE = c2317bA134.b(zzalVar134.zzb()).a();
        b.C2317b c2317bA135 = b.a("sapiSummarizationCreateEvent");
        zzal zzalVar135 = new zzal();
        zzalVar135.zza(135);
        zzbF = c2317bA135.b(zzalVar135.zzb()).a();
        b.C2317b c2317bA136 = b.a("sapiSummarizationCloseEvent");
        zzal zzalVar136 = new zzal();
        zzalVar136.zza(136);
        zzbG = c2317bA136.b(zzalVar136.zzb()).a();
        b.C2317b c2317bA137 = b.a("sapiProofreadingCreateEvent");
        zzal zzalVar137 = new zzal();
        zzalVar137.zza(137);
        zzbH = c2317bA137.b(zzalVar137.zzb()).a();
        b.C2317b c2317bA138 = b.a("sapiProofreadingCloseEvent");
        zzal zzalVar138 = new zzal();
        zzalVar138.zza(138);
        zzbI = c2317bA138.b(zzalVar138.zzb()).a();
        b.C2317b c2317bA139 = b.a("sapiRewritingCreateEvent");
        zzal zzalVar139 = new zzal();
        zzalVar139.zza(139);
        zzbJ = c2317bA139.b(zzalVar139.zzb()).a();
        b.C2317b c2317bA140 = b.a("sapiRewritingCloseEvent");
        zzal zzalVar140 = new zzal();
        zzalVar140.zza(140);
        zzbK = c2317bA140.b(zzalVar140.zzb()).a();
        b.C2317b c2317bA141 = b.a("sapiImageDescriptionInferenceEvent");
        zzal zzalVar141 = new zzal();
        zzalVar141.zza(141);
        zzbL = c2317bA141.b(zzalVar141.zzb()).a();
        b.C2317b c2317bA142 = b.a("sapiImageDescriptionCreateEvent");
        zzal zzalVar142 = new zzal();
        zzalVar142.zza(142);
        zzbM = c2317bA142.b(zzalVar142.zzb()).a();
        b.C2317b c2317bA143 = b.a("sapiImageDescriptionCloseEvent");
        zzal zzalVar143 = new zzal();
        zzalVar143.zza(143);
        zzbN = c2317bA143.b(zzalVar143.zzb()).a();
        b.C2317b c2317bA144 = b.a("sapiGenerationInferenceEvent");
        zzal zzalVar144 = new zzal();
        zzalVar144.zza(147);
        zzbO = c2317bA144.b(zzalVar144.zzb()).a();
        b.C2317b c2317bA145 = b.a("sapiGenerationCreateEvent");
        zzal zzalVar145 = new zzal();
        zzalVar145.zza(148);
        zzbP = c2317bA145.b(zzalVar145.zzb()).a();
        b.C2317b c2317bA146 = b.a("sapiGenerationCloseEvent");
        zzal zzalVar146 = new zzal();
        zzalVar146.zza(149);
        zzbQ = c2317bA146.b(zzalVar146.zzb()).a();
        b.C2317b c2317bA147 = b.a("speechRecognitionCreateEvent");
        zzal zzalVar147 = new zzal();
        zzalVar147.zza(150);
        zzbR = c2317bA147.b(zzalVar147.zzb()).a();
        b.C2317b c2317bA148 = b.a("speechRecognitionInferenceEvent");
        zzal zzalVar148 = new zzal();
        zzalVar148.zza(151);
        zzbS = c2317bA148.b(zzalVar148.zzb()).a();
        b.C2317b c2317bA149 = b.a("speechRecognitionCloseEvent");
        zzal zzalVar149 = new zzal();
        zzalVar149.zza(152);
        zzbT = c2317bA149.b(zzalVar149.zzb()).a();
    }

    private zzgm() {
    }

    @Override // rv.c
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) {
        zznw zznwVar = (zznw) obj;
        d dVar = (d) obj2;
        dVar.add(zzb, zznwVar.zza());
        dVar.add(zzc, zznwVar.zzb());
        dVar.add(zzd, (Object) null);
        dVar.add(zze, (Object) null);
        dVar.add(zzf, (Object) null);
        dVar.add(zzg, (Object) null);
        dVar.add(zzh, (Object) null);
        dVar.add(zzi, (Object) null);
        dVar.add(zzj, (Object) null);
        dVar.add(zzk, (Object) null);
        dVar.add(zzl, (Object) null);
        dVar.add(zzm, (Object) null);
        dVar.add(zzn, (Object) null);
        dVar.add(zzo, (Object) null);
        dVar.add(zzp, (Object) null);
        dVar.add(zzq, (Object) null);
        dVar.add(zzr, (Object) null);
        dVar.add(zzs, (Object) null);
        dVar.add(zzt, (Object) null);
        dVar.add(zzu, (Object) null);
        dVar.add(zzv, (Object) null);
        dVar.add(zzw, (Object) null);
        dVar.add(zzx, (Object) null);
        dVar.add(zzy, (Object) null);
        dVar.add(zzz, (Object) null);
        dVar.add(zzA, (Object) null);
        dVar.add(zzB, (Object) null);
        dVar.add(zzC, (Object) null);
        dVar.add(zzD, (Object) null);
        dVar.add(zzE, (Object) null);
        dVar.add(zzF, (Object) null);
        dVar.add(zzG, (Object) null);
        dVar.add(zzH, (Object) null);
        dVar.add(zzI, (Object) null);
        dVar.add(zzJ, (Object) null);
        dVar.add(zzK, (Object) null);
        dVar.add(zzL, (Object) null);
        dVar.add(zzM, (Object) null);
        dVar.add(zzN, (Object) null);
        dVar.add(zzO, (Object) null);
        dVar.add(zzP, (Object) null);
        dVar.add(zzQ, (Object) null);
        dVar.add(zzR, (Object) null);
        dVar.add(zzS, (Object) null);
        dVar.add(zzT, (Object) null);
        dVar.add(zzU, (Object) null);
        dVar.add(zzV, (Object) null);
        dVar.add(zzW, (Object) null);
        dVar.add(zzX, (Object) null);
        dVar.add(zzY, (Object) null);
        dVar.add(zzZ, (Object) null);
        dVar.add(zzaa, (Object) null);
        dVar.add(zzab, (Object) null);
        dVar.add(zzac, (Object) null);
        dVar.add(zzad, (Object) null);
        dVar.add(zzae, (Object) null);
        dVar.add(zzaf, (Object) null);
        dVar.add(zzag, (Object) null);
        dVar.add(zzah, (Object) null);
        dVar.add(zzai, (Object) null);
        dVar.add(zzaj, (Object) null);
        dVar.add(zzak, (Object) null);
        dVar.add(zzal, (Object) null);
        dVar.add(zzam, (Object) null);
        dVar.add(zzan, (Object) null);
        dVar.add(zzao, (Object) null);
        dVar.add(zzap, (Object) null);
        dVar.add(zzaq, (Object) null);
        dVar.add(zzar, (Object) null);
        dVar.add(zzas, (Object) null);
        dVar.add(zzat, (Object) null);
        dVar.add(zzau, (Object) null);
        dVar.add(zzav, (Object) null);
        dVar.add(zzaw, (Object) null);
        dVar.add(zzax, (Object) null);
        dVar.add(zzay, (Object) null);
        dVar.add(zzaz, (Object) null);
        dVar.add(zzaA, (Object) null);
        dVar.add(zzaB, (Object) null);
        dVar.add(zzaC, (Object) null);
        dVar.add(zzaD, (Object) null);
        dVar.add(zzaE, (Object) null);
        dVar.add(zzaF, (Object) null);
        dVar.add(zzaG, (Object) null);
        dVar.add(zzaH, (Object) null);
        dVar.add(zzaI, (Object) null);
        dVar.add(zzaJ, (Object) null);
        dVar.add(zzaK, (Object) null);
        dVar.add(zzaL, (Object) null);
        dVar.add(zzaM, (Object) null);
        dVar.add(zzaN, (Object) null);
        dVar.add(zzaO, (Object) null);
        dVar.add(zzaP, (Object) null);
        dVar.add(zzaQ, (Object) null);
        dVar.add(zzaR, (Object) null);
        dVar.add(zzaS, (Object) null);
        dVar.add(zzaT, (Object) null);
        dVar.add(zzaU, (Object) null);
        dVar.add(zzaV, (Object) null);
        dVar.add(zzaW, (Object) null);
        dVar.add(zzaX, (Object) null);
        dVar.add(zzaY, (Object) null);
        dVar.add(zzaZ, (Object) null);
        dVar.add(zzba, (Object) null);
        dVar.add(zzbb, (Object) null);
        dVar.add(zzbc, (Object) null);
        dVar.add(zzbd, (Object) null);
        dVar.add(zzbe, (Object) null);
        dVar.add(zzbf, (Object) null);
        dVar.add(zzbg, (Object) null);
        dVar.add(zzbh, (Object) null);
        dVar.add(zzbi, (Object) null);
        dVar.add(zzbj, (Object) null);
        dVar.add(zzbk, (Object) null);
        dVar.add(zzbl, (Object) null);
        dVar.add(zzbm, zznwVar.zzc());
        dVar.add(zzbn, zznwVar.zzd());
        dVar.add(zzbo, (Object) null);
        dVar.add(zzbp, (Object) null);
        dVar.add(zzbq, zznwVar.zze());
        dVar.add(zzbr, (Object) null);
        dVar.add(zzbs, (Object) null);
        dVar.add(zzbt, (Object) null);
        dVar.add(zzbu, (Object) null);
        dVar.add(zzbv, (Object) null);
        dVar.add(zzbw, (Object) null);
        dVar.add(zzbx, (Object) null);
        dVar.add(zzby, (Object) null);
        dVar.add(zzbz, (Object) null);
        dVar.add(zzbA, (Object) null);
        dVar.add(zzbB, (Object) null);
        dVar.add(zzbC, (Object) null);
        dVar.add(zzbD, (Object) null);
        dVar.add(zzbE, (Object) null);
        dVar.add(zzbF, (Object) null);
        dVar.add(zzbG, (Object) null);
        dVar.add(zzbH, (Object) null);
        dVar.add(zzbI, (Object) null);
        dVar.add(zzbJ, (Object) null);
        dVar.add(zzbK, (Object) null);
        dVar.add(zzbL, (Object) null);
        dVar.add(zzbM, (Object) null);
        dVar.add(zzbN, (Object) null);
        dVar.add(zzbO, (Object) null);
        dVar.add(zzbP, (Object) null);
        dVar.add(zzbQ, (Object) null);
        dVar.add(zzbR, (Object) null);
        dVar.add(zzbS, (Object) null);
        dVar.add(zzbT, (Object) null);
    }
}
