package com.google.android.gms.internal.mlkit_vision_document_scanner;

import com.google.android.gms.wallet.WalletConstants;
import com.google.android.vending.expansion.downloader.impl.DownloaderService;
import com.plaid.internal.EnumC4419g;
import com.withpersona.sdk2.inquiry.network.core.HttpStatusCode;

/* JADX INFO: loaded from: classes5.dex */
public enum zznt implements zzan {
    NO_ERROR(0),
    INCOMPATIBLE_INPUT(1),
    INCOMPATIBLE_OUTPUT(2),
    INCOMPATIBLE_TFLITE_VERSION(3),
    MISSING_OP(4),
    DATA_TYPE_ERROR(6),
    TFLITE_INTERNAL_ERROR(7),
    TFLITE_UNKNOWN_ERROR(8),
    MEDIAPIPE_ERROR(9),
    TIME_OUT_FETCHING_MODEL_METADATA(5),
    MODEL_NOT_DOWNLOADED(100),
    URI_EXPIRED(101),
    NO_NETWORK_CONNECTION(102),
    METERED_NETWORK(103),
    DOWNLOAD_FAILED(104),
    MODEL_INFO_DOWNLOAD_UNSUCCESSFUL_HTTP_STATUS(105),
    MODEL_INFO_DOWNLOAD_NO_HASH(106),
    MODEL_INFO_DOWNLOAD_CONNECTION_FAILED(107),
    NO_VALID_MODEL(108),
    LOCAL_MODEL_INVALID(109),
    REMOTE_MODEL_INVALID(110),
    REMOTE_MODEL_LOADER_ERROR(111),
    REMOTE_MODEL_LOADER_LOADS_NO_MODEL(112),
    SMART_REPLY_LANG_ID_DETECTAION_FAILURE(113),
    MODEL_NOT_REGISTERED(114),
    MODEL_TYPE_MISUSE(115),
    MODEL_HASH_MISMATCH(116),
    OPTIONAL_MODULE_NOT_AVAILABLE(EnumC4419g.SDK_ASSET_ICON_CHEVRON_LEFT_DOUBLE_S2_VALUE),
    OPTIONAL_MODULE_INIT_ERROR(EnumC4419g.SDK_ASSET_ICON_CHEVRON_RIGHT_DOUBLE_S1_VALUE),
    OPTIONAL_MODULE_INFERENCE_ERROR(EnumC4419g.SDK_ASSET_ICON_CHEVRON_RIGHT_DOUBLE_S2_VALUE),
    OPTIONAL_MODULE_RELEASE_ERROR(EnumC4419g.SDK_ASSET_ICON_CLEARED_REC_VALUE),
    OPTIONAL_TFLITE_MODULE_INIT_ERROR(EnumC4419g.SDK_ASSET_ICON_CLIPBOARD_VALUE),
    NATIVE_LIBRARY_LOAD_ERROR(EnumC4419g.SDK_ASSET_ICON_CLOCK_VALUE),
    OPTIONAL_MODULE_CREATE_ERROR(EnumC4419g.SDK_ASSET_ICON_COMMENT_VALUE),
    CAMERAX_SOURCE_ERROR(EnumC4419g.SDK_ASSET_CASH_ICON_CIRCLE_VALUE),
    CAMERA1_SOURCE_CANT_START_ERROR(EnumC4419g.SDK_ASSET_ANIMATION_MOBILE_AUTH_LOADING_VALUE),
    CAMERA1_SOURCE_NO_SUITABLE_SIZE_ERROR(EnumC4419g.SDK_ASSET_ANIMATION_MOBILE_AUTH_LOADING_DARK_APPEARANCE_VALUE),
    CAMERA1_SOURCE_NO_SUITABLE_FPS_ERROR(EnumC4419g.SDK_ASSET_ICON_INLINE_LIGHTNING_VALUE),
    CAMERA1_SOURCE_NO_BYTE_SOURCE_FOUND_ERROR(EnumC4419g.SDK_ASSET_ICON_INLINE_LIGHTNING_DARK_APPEARANCE_VALUE),
    CODE_SCANNER_UNAVAILABLE(400),
    CODE_SCANNER_CANCELLED(HttpStatusCode.UNAUTHORIZED_401),
    CODE_SCANNER_CAMERA_PERMISSION_NOT_GRANTED(WalletConstants.ERROR_CODE_SERVICE_UNAVAILABLE),
    CODE_SCANNER_APP_NAME_UNAVAILABLE(DownloaderService.STATUS_FORBIDDEN),
    CODE_SCANNER_TASK_IN_PROGRESS(404),
    CODE_SCANNER_PIPELINE_INITIALIZATION_ERROR(WalletConstants.ERROR_CODE_MERCHANT_ACCOUNT_ERROR),
    CODE_SCANNER_PIPELINE_INFERENCE_ERROR(WalletConstants.ERROR_CODE_SPENDING_LIMIT_EXCEEDED),
    CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(407),
    LOW_LIGHT_AUTO_EXPOSURE_COMPUTATION_FAILURE(500),
    LOW_LIGHT_IMAGE_CAPTURE_PROCESSING_FAILURE(501),
    PERMISSION_DENIED(600),
    CANCELLED(601),
    GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(602),
    LOW_MEMORY(603),
    SAPI_BUSY(700),
    SAPI_CANCELLED(701),
    SAPI_NEEDS_SYSTEM_UPDATE(702),
    SAPI_NOT_AVAILABLE(703),
    SAPI_NOT_ENOUGH_DISK_SPACE(704),
    SAPI_REQUEST_PROCESSING_ERROR(705),
    SAPI_REQUEST_TOO_LARGE(706),
    SAPI_RESPONSE_GENERATION_ERROR(707),
    SAPI_RESPONSE_PROCESSING_ERROR(708),
    SAPI_REQUEST_TOO_SMALL(709),
    SAPI_BAD_DATA(710),
    SAPI_BAD_REQUEST(711),
    SAPI_COMPUTE_ERROR(712),
    SAPI_IPC_ERROR(713),
    SAPI_SERVICE_PROCESSING_ERROR(714),
    SAPI_SUSPENDED(715),
    SAPI_INTERNAL_ERROR(716),
    SAPI_NOT_SUPPORTED(717),
    SAPI_SUSPENDED_STATELESS(718),
    SAPI_INTERNAL_ERROR_DOUBLE_MODEL_LOAD_ATTEMPT(719),
    SAPI_BINDING_FAILURE(720),
    SAPI_SERVICE_DISCONNECTED(721),
    SAPI_BINDING_DIED(722),
    SAPI_NULL_BINDING(723),
    SAPI_FEATURE_NOT_FOUND(724),
    SAPI_APK_SERVING_GROUP_MISMATCH(725),
    SAPI_AICORE_INCOMPATIBLE(726),
    SAPI_INVALID_INPUT_IMAGE(727),
    SAPI_PER_APP_BATTERY_USE_QUOTA_EXCEEDED(728),
    SAPI_PER_DEVICE_BATTERY_USE_QUOTA_EXCEEDED(729),
    SAPI_BACKGROUND_USE_BLOCKED(730),
    UNKNOWN_ERROR(9999);

    private final int zzaH;

    zznt(int i11) {
        this.zzaH = i11;
    }

    @Override // com.google.android.gms.internal.mlkit_vision_document_scanner.zzan
    public final int zza() {
        return this.zzaH;
    }
}
