package com.google.android.gms.internal.mlkit_vision_text_common;

import com.plaid.internal.EnumC4419g;
import rv.b;
import rv.c;
import rv.d;

/* JADX INFO: loaded from: classes5.dex */
final class zzio implements c {
    private static final b zzA;
    private static final b zzB;
    private static final b zzC;
    private static final b zzD;
    private static final b zzE;
    private static final b zzF;
    private static final b zzG;
    private static final b zzH;
    private static final b zzI;
    private static final b zzJ;
    private static final b zzK;
    private static final b zzL;
    private static final b zzM;
    private static final b zzN;
    private static final b zzO;
    private static final b zzP;
    private static final b zzQ;
    private static final b zzR;
    private static final b zzS;
    private static final b zzT;
    private static final b zzU;
    private static final b zzV;
    private static final b zzW;
    private static final b zzX;
    private static final b zzY;
    private static final b zzZ;
    static final zzio zza = new zzio();
    private static final b zzaA;
    private static final b zzaB;
    private static final b zzaC;
    private static final b zzaD;
    private static final b zzaE;
    private static final b zzaF;
    private static final b zzaG;
    private static final b zzaH;
    private static final b zzaI;
    private static final b zzaJ;
    private static final b zzaK;
    private static final b zzaL;
    private static final b zzaM;
    private static final b zzaN;
    private static final b zzaO;
    private static final b zzaP;
    private static final b zzaQ;
    private static final b zzaR;
    private static final b zzaS;
    private static final b zzaT;
    private static final b zzaU;
    private static final b zzaV;
    private static final b zzaW;
    private static final b zzaX;
    private static final b zzaY;
    private static final b zzaZ;
    private static final b zzaa;
    private static final b zzab;
    private static final b zzac;
    private static final b zzad;
    private static final b zzae;
    private static final b zzaf;
    private static final b zzag;
    private static final b zzah;
    private static final b zzai;
    private static final b zzaj;
    private static final b zzak;
    private static final b zzal;
    private static final b zzam;
    private static final b zzan;
    private static final b zzao;
    private static final b zzap;
    private static final b zzaq;
    private static final b zzar;
    private static final b zzas;
    private static final b zzat;
    private static final b zzau;
    private static final b zzav;
    private static final b zzaw;
    private static final b zzax;
    private static final b zzay;
    private static final b zzaz;
    private static final b zzb;
    private static final b zzba;
    private static final b zzbb;
    private static final b zzbc;
    private static final b zzbd;
    private static final b zzbe;
    private static final b zzbf;
    private static final b zzbg;
    private static final b zzbh;
    private static final b zzbi;
    private static final b zzbj;
    private static final b zzbk;
    private static final b zzbl;
    private static final b zzbm;
    private static final b zzbn;
    private static final b zzbo;
    private static final b zzbp;
    private static final b zzbq;
    private static final b zzbr;
    private static final b zzbs;
    private static final b zzbt;
    private static final b zzbu;
    private static final b zzbv;
    private static final b zzbw;
    private static final b zzbx;
    private static final b zzby;
    private static final b zzc;
    private static final b zzd;
    private static final b zze;
    private static final b zzf;
    private static final b zzg;
    private static final b zzh;
    private static final b zzi;
    private static final b zzj;
    private static final b zzk;
    private static final b zzl;
    private static final b zzm;
    private static final b zzn;
    private static final b zzo;
    private static final b zzp;
    private static final b zzq;
    private static final b zzr;
    private static final b zzs;
    private static final b zzt;
    private static final b zzu;
    private static final b zzv;
    private static final b zzw;
    private static final b zzx;
    private static final b zzy;
    private static final b zzz;

    static {
        b.C2317b c2317bA = b.a("systemInfo");
        zzct zzctVar = new zzct();
        zzctVar.zza(1);
        zzb = c2317bA.b(zzctVar.zzb()).a();
        b.C2317b c2317bA2 = b.a("eventName");
        zzct zzctVar2 = new zzct();
        zzctVar2.zza(2);
        zzc = c2317bA2.b(zzctVar2.zzb()).a();
        b.C2317b c2317bA3 = b.a("isThickClient");
        zzct zzctVar3 = new zzct();
        zzctVar3.zza(37);
        zzd = c2317bA3.b(zzctVar3.zzb()).a();
        b.C2317b c2317bA4 = b.a("clientType");
        zzct zzctVar4 = new zzct();
        zzctVar4.zza(61);
        zze = c2317bA4.b(zzctVar4.zzb()).a();
        b.C2317b c2317bA5 = b.a("modelDownloadLogEvent");
        zzct zzctVar5 = new zzct();
        zzctVar5.zza(3);
        zzf = c2317bA5.b(zzctVar5.zzb()).a();
        b.C2317b c2317bA6 = b.a("customModelLoadLogEvent");
        zzct zzctVar6 = new zzct();
        zzctVar6.zza(20);
        zzg = c2317bA6.b(zzctVar6.zzb()).a();
        b.C2317b c2317bA7 = b.a("customModelInferenceLogEvent");
        zzct zzctVar7 = new zzct();
        zzctVar7.zza(4);
        zzh = c2317bA7.b(zzctVar7.zzb()).a();
        b.C2317b c2317bA8 = b.a("customModelCreateLogEvent");
        zzct zzctVar8 = new zzct();
        zzctVar8.zza(29);
        zzi = c2317bA8.b(zzctVar8.zzb()).a();
        b.C2317b c2317bA9 = b.a("onDeviceFaceDetectionLogEvent");
        zzct zzctVar9 = new zzct();
        zzctVar9.zza(5);
        zzj = c2317bA9.b(zzctVar9.zzb()).a();
        b.C2317b c2317bA10 = b.a("onDeviceFaceLoadLogEvent");
        zzct zzctVar10 = new zzct();
        zzctVar10.zza(59);
        zzk = c2317bA10.b(zzctVar10.zzb()).a();
        b.C2317b c2317bA11 = b.a("onDeviceTextDetectionLogEvent");
        zzct zzctVar11 = new zzct();
        zzctVar11.zza(6);
        zzl = c2317bA11.b(zzctVar11.zzb()).a();
        b.C2317b c2317bA12 = b.a("onDeviceTextDetectionLoadLogEvent");
        zzct zzctVar12 = new zzct();
        zzctVar12.zza(79);
        zzm = c2317bA12.b(zzctVar12.zzb()).a();
        b.C2317b c2317bA13 = b.a("onDeviceBarcodeDetectionLogEvent");
        zzct zzctVar13 = new zzct();
        zzctVar13.zza(7);
        zzn = c2317bA13.b(zzctVar13.zzb()).a();
        b.C2317b c2317bA14 = b.a("onDeviceBarcodeLoadLogEvent");
        zzct zzctVar14 = new zzct();
        zzctVar14.zza(58);
        zzo = c2317bA14.b(zzctVar14.zzb()).a();
        b.C2317b c2317bA15 = b.a("onDeviceImageLabelCreateLogEvent");
        zzct zzctVar15 = new zzct();
        zzctVar15.zza(48);
        zzp = c2317bA15.b(zzctVar15.zzb()).a();
        b.C2317b c2317bA16 = b.a("onDeviceImageLabelLoadLogEvent");
        zzct zzctVar16 = new zzct();
        zzctVar16.zza(49);
        zzq = c2317bA16.b(zzctVar16.zzb()).a();
        b.C2317b c2317bA17 = b.a("onDeviceImageLabelDetectionLogEvent");
        zzct zzctVar17 = new zzct();
        zzctVar17.zza(18);
        zzr = c2317bA17.b(zzctVar17.zzb()).a();
        b.C2317b c2317bA18 = b.a("onDeviceObjectCreateLogEvent");
        zzct zzctVar18 = new zzct();
        zzctVar18.zza(26);
        zzs = c2317bA18.b(zzctVar18.zzb()).a();
        b.C2317b c2317bA19 = b.a("onDeviceObjectLoadLogEvent");
        zzct zzctVar19 = new zzct();
        zzctVar19.zza(27);
        zzt = c2317bA19.b(zzctVar19.zzb()).a();
        b.C2317b c2317bA20 = b.a("onDeviceObjectInferenceLogEvent");
        zzct zzctVar20 = new zzct();
        zzctVar20.zza(28);
        zzu = c2317bA20.b(zzctVar20.zzb()).a();
        b.C2317b c2317bA21 = b.a("onDevicePoseDetectionLogEvent");
        zzct zzctVar21 = new zzct();
        zzctVar21.zza(44);
        zzv = c2317bA21.b(zzctVar21.zzb()).a();
        b.C2317b c2317bA22 = b.a("onDeviceSegmentationLogEvent");
        zzct zzctVar22 = new zzct();
        zzctVar22.zza(45);
        zzw = c2317bA22.b(zzctVar22.zzb()).a();
        b.C2317b c2317bA23 = b.a("onDeviceSmartReplyLogEvent");
        zzct zzctVar23 = new zzct();
        zzctVar23.zza(19);
        zzx = c2317bA23.b(zzctVar23.zzb()).a();
        b.C2317b c2317bA24 = b.a("onDeviceLanguageIdentificationLogEvent");
        zzct zzctVar24 = new zzct();
        zzctVar24.zza(21);
        zzy = c2317bA24.b(zzctVar24.zzb()).a();
        b.C2317b c2317bA25 = b.a("onDeviceTranslationLogEvent");
        zzct zzctVar25 = new zzct();
        zzctVar25.zza(22);
        zzz = c2317bA25.b(zzctVar25.zzb()).a();
        b.C2317b c2317bA26 = b.a("cloudFaceDetectionLogEvent");
        zzct zzctVar26 = new zzct();
        zzctVar26.zza(8);
        zzA = c2317bA26.b(zzctVar26.zzb()).a();
        b.C2317b c2317bA27 = b.a("cloudCropHintDetectionLogEvent");
        zzct zzctVar27 = new zzct();
        zzctVar27.zza(9);
        zzB = c2317bA27.b(zzctVar27.zzb()).a();
        b.C2317b c2317bA28 = b.a("cloudDocumentTextDetectionLogEvent");
        zzct zzctVar28 = new zzct();
        zzctVar28.zza(10);
        zzC = c2317bA28.b(zzctVar28.zzb()).a();
        b.C2317b c2317bA29 = b.a("cloudImagePropertiesDetectionLogEvent");
        zzct zzctVar29 = new zzct();
        zzctVar29.zza(11);
        zzD = c2317bA29.b(zzctVar29.zzb()).a();
        b.C2317b c2317bA30 = b.a("cloudImageLabelDetectionLogEvent");
        zzct zzctVar30 = new zzct();
        zzctVar30.zza(12);
        zzE = c2317bA30.b(zzctVar30.zzb()).a();
        b.C2317b c2317bA31 = b.a("cloudLandmarkDetectionLogEvent");
        zzct zzctVar31 = new zzct();
        zzctVar31.zza(13);
        zzF = c2317bA31.b(zzctVar31.zzb()).a();
        b.C2317b c2317bA32 = b.a("cloudLogoDetectionLogEvent");
        zzct zzctVar32 = new zzct();
        zzctVar32.zza(14);
        zzG = c2317bA32.b(zzctVar32.zzb()).a();
        b.C2317b c2317bA33 = b.a("cloudSafeSearchDetectionLogEvent");
        zzct zzctVar33 = new zzct();
        zzctVar33.zza(15);
        zzH = c2317bA33.b(zzctVar33.zzb()).a();
        b.C2317b c2317bA34 = b.a("cloudTextDetectionLogEvent");
        zzct zzctVar34 = new zzct();
        zzctVar34.zza(16);
        zzI = c2317bA34.b(zzctVar34.zzb()).a();
        b.C2317b c2317bA35 = b.a("cloudWebSearchDetectionLogEvent");
        zzct zzctVar35 = new zzct();
        zzctVar35.zza(17);
        zzJ = c2317bA35.b(zzctVar35.zzb()).a();
        b.C2317b c2317bA36 = b.a("automlImageLabelingCreateLogEvent");
        zzct zzctVar36 = new zzct();
        zzctVar36.zza(23);
        zzK = c2317bA36.b(zzctVar36.zzb()).a();
        b.C2317b c2317bA37 = b.a("automlImageLabelingLoadLogEvent");
        zzct zzctVar37 = new zzct();
        zzctVar37.zza(24);
        zzL = c2317bA37.b(zzctVar37.zzb()).a();
        b.C2317b c2317bA38 = b.a("automlImageLabelingInferenceLogEvent");
        zzct zzctVar38 = new zzct();
        zzctVar38.zza(25);
        zzM = c2317bA38.b(zzctVar38.zzb()).a();
        b.C2317b c2317bA39 = b.a("isModelDownloadedLogEvent");
        zzct zzctVar39 = new zzct();
        zzctVar39.zza(39);
        zzN = c2317bA39.b(zzctVar39.zzb()).a();
        b.C2317b c2317bA40 = b.a("deleteModelLogEvent");
        zzct zzctVar40 = new zzct();
        zzctVar40.zza(40);
        zzO = c2317bA40.b(zzctVar40.zzb()).a();
        b.C2317b c2317bA41 = b.a("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzct zzctVar41 = new zzct();
        zzctVar41.zza(30);
        zzP = c2317bA41.b(zzctVar41.zzb()).a();
        b.C2317b c2317bA42 = b.a("aggregatedCustomModelInferenceLogEvent");
        zzct zzctVar42 = new zzct();
        zzctVar42.zza(31);
        zzQ = c2317bA42.b(zzctVar42.zzb()).a();
        b.C2317b c2317bA43 = b.a("aggregatedOnDeviceFaceDetectionLogEvent");
        zzct zzctVar43 = new zzct();
        zzctVar43.zza(32);
        zzR = c2317bA43.b(zzctVar43.zzb()).a();
        b.C2317b c2317bA44 = b.a("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzct zzctVar44 = new zzct();
        zzctVar44.zza(33);
        zzS = c2317bA44.b(zzctVar44.zzb()).a();
        b.C2317b c2317bA45 = b.a("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzct zzctVar45 = new zzct();
        zzctVar45.zza(34);
        zzT = c2317bA45.b(zzctVar45.zzb()).a();
        b.C2317b c2317bA46 = b.a("aggregatedOnDeviceObjectInferenceLogEvent");
        zzct zzctVar46 = new zzct();
        zzctVar46.zza(35);
        zzU = c2317bA46.b(zzctVar46.zzb()).a();
        b.C2317b c2317bA47 = b.a("aggregatedOnDeviceTextDetectionLogEvent");
        zzct zzctVar47 = new zzct();
        zzctVar47.zza(36);
        zzV = c2317bA47.b(zzctVar47.zzb()).a();
        b.C2317b c2317bA48 = b.a("aggregatedOnDevicePoseDetectionLogEvent");
        zzct zzctVar48 = new zzct();
        zzctVar48.zza(46);
        zzW = c2317bA48.b(zzctVar48.zzb()).a();
        b.C2317b c2317bA49 = b.a("aggregatedOnDeviceSegmentationLogEvent");
        zzct zzctVar49 = new zzct();
        zzctVar49.zza(47);
        zzX = c2317bA49.b(zzctVar49.zzb()).a();
        b.C2317b c2317bA50 = b.a("pipelineAccelerationInferenceEvents");
        zzct zzctVar50 = new zzct();
        zzctVar50.zza(69);
        zzY = c2317bA50.b(zzctVar50.zzb()).a();
        b.C2317b c2317bA51 = b.a("remoteConfigLogEvent");
        zzct zzctVar51 = new zzct();
        zzctVar51.zza(42);
        zzZ = c2317bA51.b(zzctVar51.zzb()).a();
        b.C2317b c2317bA52 = b.a("inputImageConstructionLogEvent");
        zzct zzctVar52 = new zzct();
        zzctVar52.zza(50);
        zzaa = c2317bA52.b(zzctVar52.zzb()).a();
        b.C2317b c2317bA53 = b.a("leakedHandleEvent");
        zzct zzctVar53 = new zzct();
        zzctVar53.zza(51);
        zzab = c2317bA53.b(zzctVar53.zzb()).a();
        b.C2317b c2317bA54 = b.a("cameraSourceLogEvent");
        zzct zzctVar54 = new zzct();
        zzctVar54.zza(52);
        zzac = c2317bA54.b(zzctVar54.zzb()).a();
        b.C2317b c2317bA55 = b.a("imageLabelOptionalModuleLogEvent");
        zzct zzctVar55 = new zzct();
        zzctVar55.zza(53);
        zzad = c2317bA55.b(zzctVar55.zzb()).a();
        b.C2317b c2317bA56 = b.a("languageIdentificationOptionalModuleLogEvent");
        zzct zzctVar56 = new zzct();
        zzctVar56.zza(54);
        zzae = c2317bA56.b(zzctVar56.zzb()).a();
        b.C2317b c2317bA57 = b.a("faceDetectionOptionalModuleLogEvent");
        zzct zzctVar57 = new zzct();
        zzctVar57.zza(60);
        zzaf = c2317bA57.b(zzctVar57.zzb()).a();
        b.C2317b c2317bA58 = b.a("documentDetectionOptionalModuleLogEvent");
        zzct zzctVar58 = new zzct();
        zzctVar58.zza(85);
        zzag = c2317bA58.b(zzctVar58.zzb()).a();
        b.C2317b c2317bA59 = b.a("documentCroppingOptionalModuleLogEvent");
        zzct zzctVar59 = new zzct();
        zzctVar59.zza(86);
        zzah = c2317bA59.b(zzctVar59.zzb()).a();
        b.C2317b c2317bA60 = b.a("documentEnhancementOptionalModuleLogEvent");
        zzct zzctVar60 = new zzct();
        zzctVar60.zza(87);
        zzai = c2317bA60.b(zzctVar60.zzb()).a();
        b.C2317b c2317bA61 = b.a("nlClassifierOptionalModuleLogEvent");
        zzct zzctVar61 = new zzct();
        zzctVar61.zza(55);
        zzaj = c2317bA61.b(zzctVar61.zzb()).a();
        b.C2317b c2317bA62 = b.a("nlClassifierClientLibraryLogEvent");
        zzct zzctVar62 = new zzct();
        zzctVar62.zza(56);
        zzak = c2317bA62.b(zzctVar62.zzb()).a();
        b.C2317b c2317bA63 = b.a("accelerationAllowlistLogEvent");
        zzct zzctVar63 = new zzct();
        zzctVar63.zza(57);
        zzal = c2317bA63.b(zzctVar63.zzb()).a();
        b.C2317b c2317bA64 = b.a("toxicityDetectionCreateEvent");
        zzct zzctVar64 = new zzct();
        zzctVar64.zza(62);
        zzam = c2317bA64.b(zzctVar64.zzb()).a();
        b.C2317b c2317bA65 = b.a("toxicityDetectionLoadEvent");
        zzct zzctVar65 = new zzct();
        zzctVar65.zza(63);
        zzan = c2317bA65.b(zzctVar65.zzb()).a();
        b.C2317b c2317bA66 = b.a("toxicityDetectionInferenceEvent");
        zzct zzctVar66 = new zzct();
        zzctVar66.zza(64);
        zzao = c2317bA66.b(zzctVar66.zzb()).a();
        b.C2317b c2317bA67 = b.a("barcodeDetectionOptionalModuleLogEvent");
        zzct zzctVar67 = new zzct();
        zzctVar67.zza(65);
        zzap = c2317bA67.b(zzctVar67.zzb()).a();
        b.C2317b c2317bA68 = b.a("customImageLabelOptionalModuleLogEvent");
        zzct zzctVar68 = new zzct();
        zzctVar68.zza(66);
        zzaq = c2317bA68.b(zzctVar68.zzb()).a();
        b.C2317b c2317bA69 = b.a("codeScannerScanApiEvent");
        zzct zzctVar69 = new zzct();
        zzctVar69.zza(67);
        zzar = c2317bA69.b(zzctVar69.zzb()).a();
        b.C2317b c2317bA70 = b.a("codeScannerOptionalModuleEvent");
        zzct zzctVar70 = new zzct();
        zzctVar70.zza(68);
        zzas = c2317bA70.b(zzctVar70.zzb()).a();
        b.C2317b c2317bA71 = b.a("onDeviceExplicitContentCreateLogEvent");
        zzct zzctVar71 = new zzct();
        zzctVar71.zza(70);
        zzat = c2317bA71.b(zzctVar71.zzb()).a();
        b.C2317b c2317bA72 = b.a("onDeviceExplicitContentLoadLogEvent");
        zzct zzctVar72 = new zzct();
        zzctVar72.zza(71);
        zzau = c2317bA72.b(zzctVar72.zzb()).a();
        b.C2317b c2317bA73 = b.a("onDeviceExplicitContentInferenceLogEvent");
        zzct zzctVar73 = new zzct();
        zzctVar73.zza(72);
        zzav = c2317bA73.b(zzctVar73.zzb()).a();
        b.C2317b c2317bA74 = b.a("aggregatedOnDeviceExplicitContentLogEvent");
        zzct zzctVar74 = new zzct();
        zzctVar74.zza(73);
        zzaw = c2317bA74.b(zzctVar74.zzb()).a();
        b.C2317b c2317bA75 = b.a("onDeviceFaceMeshCreateLogEvent");
        zzct zzctVar75 = new zzct();
        zzctVar75.zza(74);
        zzax = c2317bA75.b(zzctVar75.zzb()).a();
        b.C2317b c2317bA76 = b.a("onDeviceFaceMeshLoadLogEvent");
        zzct zzctVar76 = new zzct();
        zzctVar76.zza(75);
        zzay = c2317bA76.b(zzctVar76.zzb()).a();
        b.C2317b c2317bA77 = b.a("onDeviceFaceMeshLogEvent");
        zzct zzctVar77 = new zzct();
        zzctVar77.zza(76);
        zzaz = c2317bA77.b(zzctVar77.zzb()).a();
        b.C2317b c2317bA78 = b.a("aggregatedOnDeviceFaceMeshLogEvent");
        zzct zzctVar78 = new zzct();
        zzctVar78.zza(77);
        zzaA = c2317bA78.b(zzctVar78.zzb()).a();
        b.C2317b c2317bA79 = b.a("smartReplyOptionalModuleLogEvent");
        zzct zzctVar79 = new zzct();
        zzctVar79.zza(78);
        zzaB = c2317bA79.b(zzctVar79.zzb()).a();
        b.C2317b c2317bA80 = b.a("textDetectionOptionalModuleLogEvent");
        zzct zzctVar80 = new zzct();
        zzctVar80.zza(80);
        zzaC = c2317bA80.b(zzctVar80.zzb()).a();
        b.C2317b c2317bA81 = b.a("onDeviceImageQualityAnalysisCreateLogEvent");
        zzct zzctVar81 = new zzct();
        zzctVar81.zza(81);
        zzaD = c2317bA81.b(zzctVar81.zzb()).a();
        b.C2317b c2317bA82 = b.a("onDeviceImageQualityAnalysisLoadLogEvent");
        zzct zzctVar82 = new zzct();
        zzctVar82.zza(82);
        zzaE = c2317bA82.b(zzctVar82.zzb()).a();
        b.C2317b c2317bA83 = b.a("onDeviceImageQualityAnalysisLogEvent");
        zzct zzctVar83 = new zzct();
        zzctVar83.zza(83);
        zzaF = c2317bA83.b(zzctVar83.zzb()).a();
        b.C2317b c2317bA84 = b.a("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zzct zzctVar84 = new zzct();
        zzctVar84.zza(84);
        zzaG = c2317bA84.b(zzctVar84.zzb()).a();
        b.C2317b c2317bA85 = b.a("imageQualityAnalysisOptionalModuleLogEvent");
        zzct zzctVar85 = new zzct();
        zzctVar85.zza(88);
        zzaH = c2317bA85.b(zzctVar85.zzb()).a();
        b.C2317b c2317bA86 = b.a("imageCaptioningOptionalModuleLogEvent");
        zzct zzctVar86 = new zzct();
        zzctVar86.zza(89);
        zzaI = c2317bA86.b(zzctVar86.zzb()).a();
        b.C2317b c2317bA87 = b.a("onDeviceImageCaptioningCreateLogEvent");
        zzct zzctVar87 = new zzct();
        zzctVar87.zza(90);
        zzaJ = c2317bA87.b(zzctVar87.zzb()).a();
        b.C2317b c2317bA88 = b.a("onDeviceImageCaptioningLoadLogEvent");
        zzct zzctVar88 = new zzct();
        zzctVar88.zza(91);
        zzaK = c2317bA88.b(zzctVar88.zzb()).a();
        b.C2317b c2317bA89 = b.a("onDeviceImageCaptioningInferenceLogEvent");
        zzct zzctVar89 = new zzct();
        zzctVar89.zza(92);
        zzaL = c2317bA89.b(zzctVar89.zzb()).a();
        b.C2317b c2317bA90 = b.a("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zzct zzctVar90 = new zzct();
        zzctVar90.zza(93);
        zzaM = c2317bA90.b(zzctVar90.zzb()).a();
        b.C2317b c2317bA91 = b.a("onDeviceDocumentDetectionCreateLogEvent");
        zzct zzctVar91 = new zzct();
        zzctVar91.zza(94);
        zzaN = c2317bA91.b(zzctVar91.zzb()).a();
        b.C2317b c2317bA92 = b.a("onDeviceDocumentDetectionLoadLogEvent");
        zzct zzctVar92 = new zzct();
        zzctVar92.zza(95);
        zzaO = c2317bA92.b(zzctVar92.zzb()).a();
        b.C2317b c2317bA93 = b.a("onDeviceDocumentDetectionLogEvent");
        zzct zzctVar93 = new zzct();
        zzctVar93.zza(96);
        zzaP = c2317bA93.b(zzctVar93.zzb()).a();
        b.C2317b c2317bA94 = b.a("aggregatedOnDeviceDocumentDetectionLogEvent");
        zzct zzctVar94 = new zzct();
        zzctVar94.zza(97);
        zzaQ = c2317bA94.b(zzctVar94.zzb()).a();
        b.C2317b c2317bA95 = b.a("onDeviceDocumentCroppingCreateLogEvent");
        zzct zzctVar95 = new zzct();
        zzctVar95.zza(98);
        zzaR = c2317bA95.b(zzctVar95.zzb()).a();
        b.C2317b c2317bA96 = b.a("onDeviceDocumentCroppingLoadLogEvent");
        zzct zzctVar96 = new zzct();
        zzctVar96.zza(99);
        zzaS = c2317bA96.b(zzctVar96.zzb()).a();
        b.C2317b c2317bA97 = b.a("onDeviceDocumentCroppingLogEvent");
        zzct zzctVar97 = new zzct();
        zzctVar97.zza(100);
        zzaT = c2317bA97.b(zzctVar97.zzb()).a();
        b.C2317b c2317bA98 = b.a("aggregatedOnDeviceDocumentCroppingLogEvent");
        zzct zzctVar98 = new zzct();
        zzctVar98.zza(101);
        zzaU = c2317bA98.b(zzctVar98.zzb()).a();
        b.C2317b c2317bA99 = b.a("onDeviceDocumentEnhancementCreateLogEvent");
        zzct zzctVar99 = new zzct();
        zzctVar99.zza(102);
        zzaV = c2317bA99.b(zzctVar99.zzb()).a();
        b.C2317b c2317bA100 = b.a("onDeviceDocumentEnhancementLoadLogEvent");
        zzct zzctVar100 = new zzct();
        zzctVar100.zza(103);
        zzaW = c2317bA100.b(zzctVar100.zzb()).a();
        b.C2317b c2317bA101 = b.a("onDeviceDocumentEnhancementLogEvent");
        zzct zzctVar101 = new zzct();
        zzctVar101.zza(104);
        zzaX = c2317bA101.b(zzctVar101.zzb()).a();
        b.C2317b c2317bA102 = b.a("aggregatedOnDeviceDocumentEnhancementLogEvent");
        zzct zzctVar102 = new zzct();
        zzctVar102.zza(105);
        zzaY = c2317bA102.b(zzctVar102.zzb()).a();
        b.C2317b c2317bA103 = b.a("scannerAutoZoomEvent");
        zzct zzctVar103 = new zzct();
        zzctVar103.zza(106);
        zzaZ = c2317bA103.b(zzctVar103.zzb()).a();
        b.C2317b c2317bA104 = b.a("lowLightAutoExposureComputationEvent");
        zzct zzctVar104 = new zzct();
        zzctVar104.zza(107);
        zzba = c2317bA104.b(zzctVar104.zzb()).a();
        b.C2317b c2317bA105 = b.a("lowLightFrameProcessEvent");
        zzct zzctVar105 = new zzct();
        zzctVar105.zza(108);
        zzbb = c2317bA105.b(zzctVar105.zzb()).a();
        b.C2317b c2317bA106 = b.a("lowLightSceneDetectionEvent");
        zzct zzctVar106 = new zzct();
        zzctVar106.zza(109);
        zzbc = c2317bA106.b(zzctVar106.zzb()).a();
        b.C2317b c2317bA107 = b.a("onDeviceStainRemovalLogEvent");
        zzct zzctVar107 = new zzct();
        zzctVar107.zza(110);
        zzbd = c2317bA107.b(zzctVar107.zzb()).a();
        b.C2317b c2317bA108 = b.a("aggregatedOnDeviceStainRemovalLogEvent");
        zzct zzctVar108 = new zzct();
        zzctVar108.zza(111);
        zzbe = c2317bA108.b(zzctVar108.zzb()).a();
        b.C2317b c2317bA109 = b.a("stainRemovalOptionalModuleLogEvent");
        zzct zzctVar109 = new zzct();
        zzctVar109.zza(112);
        zzbf = c2317bA109.b(zzctVar109.zzb()).a();
        b.C2317b c2317bA110 = b.a("onDeviceShadowRemovalLogEvent");
        zzct zzctVar110 = new zzct();
        zzctVar110.zza(113);
        zzbg = c2317bA110.b(zzctVar110.zzb()).a();
        b.C2317b c2317bA111 = b.a("aggregatedOnDeviceShadowRemovalLogEvent");
        zzct zzctVar111 = new zzct();
        zzctVar111.zza(114);
        zzbh = c2317bA111.b(zzctVar111.zzb()).a();
        b.C2317b c2317bA112 = b.a("shadowRemovalOptionalModuleLogEvent");
        zzct zzctVar112 = new zzct();
        zzctVar112.zza(115);
        zzbi = c2317bA112.b(zzctVar112.zzb()).a();
        b.C2317b c2317bA113 = b.a("onDeviceDigitalInkSegmentationLogEvent");
        zzct zzctVar113 = new zzct();
        zzctVar113.zza(116);
        zzbj = c2317bA113.b(zzctVar113.zzb()).a();
        b.C2317b c2317bA114 = b.a("onDeviceDocumentScannerStartLogEvent");
        zzct zzctVar114 = new zzct();
        zzctVar114.zza(117);
        zzbk = c2317bA114.b(zzctVar114.zzb()).a();
        b.C2317b c2317bA115 = b.a("onDeviceDocumentScannerFinishLogEvent");
        zzct zzctVar115 = new zzct();
        zzctVar115.zza(118);
        zzbl = c2317bA115.b(zzctVar115.zzb()).a();
        b.C2317b c2317bA116 = b.a("onDeviceDocumentScannerUiStartLogEvent");
        zzct zzctVar116 = new zzct();
        zzctVar116.zza(119);
        zzbm = c2317bA116.b(zzctVar116.zzb()).a();
        b.C2317b c2317bA117 = b.a("onDeviceDocumentScannerUiFinishLogEvent");
        zzct zzctVar117 = new zzct();
        zzctVar117.zza(120);
        zzbn = c2317bA117.b(zzctVar117.zzb()).a();
        b.C2317b c2317bA118 = b.a("documentScannerUiOptionalModuleSessionStartLogEvent");
        zzct zzctVar118 = new zzct();
        zzctVar118.zza(121);
        zzbo = c2317bA118.b(zzctVar118.zzb()).a();
        b.C2317b c2317bA119 = b.a("documentScannerUiOptionalModuleSessionFinishLogEvent");
        zzct zzctVar119 = new zzct();
        zzctVar119.zza(122);
        zzbp = c2317bA119.b(zzctVar119.zzb()).a();
        b.C2317b c2317bA120 = b.a("onDeviceDocumentScannerUiCreateLogEvent");
        zzct zzctVar120 = new zzct();
        zzctVar120.zza(123);
        zzbq = c2317bA120.b(zzctVar120.zzb()).a();
        b.C2317b c2317bA121 = b.a("onDeviceSubjectSegmentationCreateLogEvent");
        zzct zzctVar121 = new zzct();
        zzctVar121.zza(124);
        zzbr = c2317bA121.b(zzctVar121.zzb()).a();
        b.C2317b c2317bA122 = b.a("onDeviceSubjectSegmentationLoadLogEvent");
        zzct zzctVar122 = new zzct();
        zzctVar122.zza(125);
        zzbs = c2317bA122.b(zzctVar122.zzb()).a();
        b.C2317b c2317bA123 = b.a("onDeviceSubjectSegmentationInferenceLogEvent");
        zzct zzctVar123 = new zzct();
        zzctVar123.zza(126);
        zzbt = c2317bA123.b(zzctVar123.zzb()).a();
        b.C2317b c2317bA124 = b.a("aggregatedOnDeviceSubjectSegmentationLogEvent");
        zzct zzctVar124 = new zzct();
        zzctVar124.zza(127);
        zzbu = c2317bA124.b(zzctVar124.zzb()).a();
        b.C2317b c2317bA125 = b.a("subjectSegmentationOptionalModuleLogEvent");
        zzct zzctVar125 = new zzct();
        zzctVar125.zza(128);
        zzbv = c2317bA125.b(zzctVar125.zzb()).a();
        b.C2317b c2317bA126 = b.a("documentScannerUiModuleScreenViewEvent");
        zzct zzctVar126 = new zzct();
        zzctVar126.zza(EnumC4419g.SDK_ASSET_ILLUSTRATION_FORM_VALUE);
        zzbw = c2317bA126.b(zzctVar126.zzb()).a();
        b.C2317b c2317bA127 = b.a("documentScannerUiModuleScreenClickEvent");
        zzct zzctVar127 = new zzct();
        zzctVar127.zza(EnumC4419g.SDK_ASSET_ILLUSTRATION_CONSUMER_VALUE);
        zzbx = c2317bA127.b(zzctVar127.zzb()).a();
        b.C2317b c2317bA128 = b.a("documentScannerUiModuleScreenErrorEvent");
        zzct zzctVar128 = new zzct();
        zzctVar128.zza(131);
        zzby = c2317bA128.b(zzctVar128.zzb()).a();
    }

    private zzio() {
    }

    @Override // rv.c
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) {
        zzoy zzoyVar = (zzoy) obj;
        d dVar = (d) obj2;
        dVar.add(zzb, zzoyVar.zzf());
        dVar.add(zzc, zzoyVar.zzc());
        dVar.add(zzd, (Object) null);
        dVar.add(zze, zzoyVar.zzb());
        dVar.add(zzf, (Object) null);
        dVar.add(zzg, (Object) null);
        dVar.add(zzh, (Object) null);
        dVar.add(zzi, (Object) null);
        dVar.add(zzj, (Object) null);
        dVar.add(zzk, (Object) null);
        dVar.add(zzl, zzoyVar.zze());
        dVar.add(zzm, zzoyVar.zzd());
        dVar.add(zzn, (Object) null);
        dVar.add(zzo, (Object) null);
        dVar.add(zzp, (Object) null);
        dVar.add(zzq, (Object) null);
        dVar.add(zzr, (Object) null);
        dVar.add(zzs, (Object) null);
        dVar.add(zzt, (Object) null);
        dVar.add(zzu, (Object) null);
        dVar.add(zzv, (Object) null);
        dVar.add(zzw, (Object) null);
        dVar.add(zzx, (Object) null);
        dVar.add(zzy, (Object) null);
        dVar.add(zzz, (Object) null);
        dVar.add(zzA, (Object) null);
        dVar.add(zzB, (Object) null);
        dVar.add(zzC, (Object) null);
        dVar.add(zzD, (Object) null);
        dVar.add(zzE, (Object) null);
        dVar.add(zzF, (Object) null);
        dVar.add(zzG, (Object) null);
        dVar.add(zzH, (Object) null);
        dVar.add(zzI, (Object) null);
        dVar.add(zzJ, (Object) null);
        dVar.add(zzK, (Object) null);
        dVar.add(zzL, (Object) null);
        dVar.add(zzM, (Object) null);
        dVar.add(zzN, (Object) null);
        dVar.add(zzO, (Object) null);
        dVar.add(zzP, (Object) null);
        dVar.add(zzQ, (Object) null);
        dVar.add(zzR, (Object) null);
        dVar.add(zzS, (Object) null);
        dVar.add(zzT, (Object) null);
        dVar.add(zzU, (Object) null);
        dVar.add(zzV, zzoyVar.zza());
        dVar.add(zzW, (Object) null);
        dVar.add(zzX, (Object) null);
        dVar.add(zzY, (Object) null);
        dVar.add(zzZ, (Object) null);
        dVar.add(zzaa, (Object) null);
        dVar.add(zzab, (Object) null);
        dVar.add(zzac, (Object) null);
        dVar.add(zzad, (Object) null);
        dVar.add(zzae, (Object) null);
        dVar.add(zzaf, (Object) null);
        dVar.add(zzag, (Object) null);
        dVar.add(zzah, (Object) null);
        dVar.add(zzai, (Object) null);
        dVar.add(zzaj, (Object) null);
        dVar.add(zzak, (Object) null);
        dVar.add(zzal, (Object) null);
        dVar.add(zzam, (Object) null);
        dVar.add(zzan, (Object) null);
        dVar.add(zzao, (Object) null);
        dVar.add(zzap, (Object) null);
        dVar.add(zzaq, (Object) null);
        dVar.add(zzar, (Object) null);
        dVar.add(zzas, (Object) null);
        dVar.add(zzat, (Object) null);
        dVar.add(zzau, (Object) null);
        dVar.add(zzav, (Object) null);
        dVar.add(zzaw, (Object) null);
        dVar.add(zzax, (Object) null);
        dVar.add(zzay, (Object) null);
        dVar.add(zzaz, (Object) null);
        dVar.add(zzaA, (Object) null);
        dVar.add(zzaB, (Object) null);
        dVar.add(zzaC, (Object) null);
        dVar.add(zzaD, (Object) null);
        dVar.add(zzaE, (Object) null);
        dVar.add(zzaF, (Object) null);
        dVar.add(zzaG, (Object) null);
        dVar.add(zzaH, (Object) null);
        dVar.add(zzaI, (Object) null);
        dVar.add(zzaJ, (Object) null);
        dVar.add(zzaK, (Object) null);
        dVar.add(zzaL, (Object) null);
        dVar.add(zzaM, (Object) null);
        dVar.add(zzaN, (Object) null);
        dVar.add(zzaO, (Object) null);
        dVar.add(zzaP, (Object) null);
        dVar.add(zzaQ, (Object) null);
        dVar.add(zzaR, (Object) null);
        dVar.add(zzaS, (Object) null);
        dVar.add(zzaT, (Object) null);
        dVar.add(zzaU, (Object) null);
        dVar.add(zzaV, (Object) null);
        dVar.add(zzaW, (Object) null);
        dVar.add(zzaX, (Object) null);
        dVar.add(zzaY, (Object) null);
        dVar.add(zzaZ, (Object) null);
        dVar.add(zzba, (Object) null);
        dVar.add(zzbb, (Object) null);
        dVar.add(zzbc, (Object) null);
        dVar.add(zzbd, (Object) null);
        dVar.add(zzbe, (Object) null);
        dVar.add(zzbf, (Object) null);
        dVar.add(zzbg, (Object) null);
        dVar.add(zzbh, (Object) null);
        dVar.add(zzbi, (Object) null);
        dVar.add(zzbj, (Object) null);
        dVar.add(zzbk, (Object) null);
        dVar.add(zzbl, (Object) null);
        dVar.add(zzbm, (Object) null);
        dVar.add(zzbn, (Object) null);
        dVar.add(zzbo, (Object) null);
        dVar.add(zzbp, (Object) null);
        dVar.add(zzbq, (Object) null);
        dVar.add(zzbr, (Object) null);
        dVar.add(zzbs, (Object) null);
        dVar.add(zzbt, (Object) null);
        dVar.add(zzbu, (Object) null);
        dVar.add(zzbv, (Object) null);
        dVar.add(zzbw, (Object) null);
        dVar.add(zzbx, (Object) null);
        dVar.add(zzby, (Object) null);
    }
}
