package com.google.android.gms.internal.mlkit_common;

import com.plaid.internal.EnumC4419g;
import rv.b;
import rv.c;
import rv.d;

/* JADX INFO: loaded from: classes5.dex */
final class zzgp implements c {
    private static final b zzA;
    private static final b zzB;
    private static final b zzC;
    private static final b zzD;
    private static final b zzE;
    private static final b zzF;
    private static final b zzG;
    private static final b zzH;
    private static final b zzI;
    private static final b zzJ;
    private static final b zzK;
    private static final b zzL;
    private static final b zzM;
    private static final b zzN;
    private static final b zzO;
    private static final b zzP;
    private static final b zzQ;
    private static final b zzR;
    private static final b zzS;
    private static final b zzT;
    private static final b zzU;
    private static final b zzV;
    private static final b zzW;
    private static final b zzX;
    private static final b zzY;
    private static final b zzZ;
    static final zzgp zza = new zzgp();
    private static final b zzaA;
    private static final b zzaB;
    private static final b zzaC;
    private static final b zzaD;
    private static final b zzaE;
    private static final b zzaF;
    private static final b zzaG;
    private static final b zzaH;
    private static final b zzaI;
    private static final b zzaJ;
    private static final b zzaK;
    private static final b zzaL;
    private static final b zzaM;
    private static final b zzaN;
    private static final b zzaO;
    private static final b zzaP;
    private static final b zzaQ;
    private static final b zzaR;
    private static final b zzaS;
    private static final b zzaT;
    private static final b zzaU;
    private static final b zzaV;
    private static final b zzaW;
    private static final b zzaX;
    private static final b zzaY;
    private static final b zzaZ;
    private static final b zzaa;
    private static final b zzab;
    private static final b zzac;
    private static final b zzad;
    private static final b zzae;
    private static final b zzaf;
    private static final b zzag;
    private static final b zzah;
    private static final b zzai;
    private static final b zzaj;
    private static final b zzak;
    private static final b zzal;
    private static final b zzam;
    private static final b zzan;
    private static final b zzao;
    private static final b zzap;
    private static final b zzaq;
    private static final b zzar;
    private static final b zzas;
    private static final b zzat;
    private static final b zzau;
    private static final b zzav;
    private static final b zzaw;
    private static final b zzax;
    private static final b zzay;
    private static final b zzaz;
    private static final b zzb;
    private static final b zzba;
    private static final b zzbb;
    private static final b zzbc;
    private static final b zzbd;
    private static final b zzbe;
    private static final b zzbf;
    private static final b zzbg;
    private static final b zzbh;
    private static final b zzbi;
    private static final b zzbj;
    private static final b zzbk;
    private static final b zzbl;
    private static final b zzbm;
    private static final b zzbn;
    private static final b zzbo;
    private static final b zzbp;
    private static final b zzbq;
    private static final b zzbr;
    private static final b zzbs;
    private static final b zzbt;
    private static final b zzbu;
    private static final b zzbv;
    private static final b zzbw;
    private static final b zzbx;
    private static final b zzby;
    private static final b zzc;
    private static final b zzd;
    private static final b zze;
    private static final b zzf;
    private static final b zzg;
    private static final b zzh;
    private static final b zzi;
    private static final b zzj;
    private static final b zzk;
    private static final b zzl;
    private static final b zzm;
    private static final b zzn;
    private static final b zzo;
    private static final b zzp;
    private static final b zzq;
    private static final b zzr;
    private static final b zzs;
    private static final b zzt;
    private static final b zzu;
    private static final b zzv;
    private static final b zzw;
    private static final b zzx;
    private static final b zzy;
    private static final b zzz;

    static {
        b.C2317b c2317bA = b.a("systemInfo");
        zzay zzayVar = new zzay();
        zzayVar.zza(1);
        zzb = c2317bA.b(zzayVar.zzb()).a();
        b.C2317b c2317bA2 = b.a("eventName");
        zzay zzayVar2 = new zzay();
        zzayVar2.zza(2);
        zzc = c2317bA2.b(zzayVar2.zzb()).a();
        b.C2317b c2317bA3 = b.a("isThickClient");
        zzay zzayVar3 = new zzay();
        zzayVar3.zza(37);
        zzd = c2317bA3.b(zzayVar3.zzb()).a();
        b.C2317b c2317bA4 = b.a("clientType");
        zzay zzayVar4 = new zzay();
        zzayVar4.zza(61);
        zze = c2317bA4.b(zzayVar4.zzb()).a();
        b.C2317b c2317bA5 = b.a("modelDownloadLogEvent");
        zzay zzayVar5 = new zzay();
        zzayVar5.zza(3);
        zzf = c2317bA5.b(zzayVar5.zzb()).a();
        b.C2317b c2317bA6 = b.a("customModelLoadLogEvent");
        zzay zzayVar6 = new zzay();
        zzayVar6.zza(20);
        zzg = c2317bA6.b(zzayVar6.zzb()).a();
        b.C2317b c2317bA7 = b.a("customModelInferenceLogEvent");
        zzay zzayVar7 = new zzay();
        zzayVar7.zza(4);
        zzh = c2317bA7.b(zzayVar7.zzb()).a();
        b.C2317b c2317bA8 = b.a("customModelCreateLogEvent");
        zzay zzayVar8 = new zzay();
        zzayVar8.zza(29);
        zzi = c2317bA8.b(zzayVar8.zzb()).a();
        b.C2317b c2317bA9 = b.a("onDeviceFaceDetectionLogEvent");
        zzay zzayVar9 = new zzay();
        zzayVar9.zza(5);
        zzj = c2317bA9.b(zzayVar9.zzb()).a();
        b.C2317b c2317bA10 = b.a("onDeviceFaceLoadLogEvent");
        zzay zzayVar10 = new zzay();
        zzayVar10.zza(59);
        zzk = c2317bA10.b(zzayVar10.zzb()).a();
        b.C2317b c2317bA11 = b.a("onDeviceTextDetectionLogEvent");
        zzay zzayVar11 = new zzay();
        zzayVar11.zza(6);
        zzl = c2317bA11.b(zzayVar11.zzb()).a();
        b.C2317b c2317bA12 = b.a("onDeviceTextDetectionLoadLogEvent");
        zzay zzayVar12 = new zzay();
        zzayVar12.zza(79);
        zzm = c2317bA12.b(zzayVar12.zzb()).a();
        b.C2317b c2317bA13 = b.a("onDeviceBarcodeDetectionLogEvent");
        zzay zzayVar13 = new zzay();
        zzayVar13.zza(7);
        zzn = c2317bA13.b(zzayVar13.zzb()).a();
        b.C2317b c2317bA14 = b.a("onDeviceBarcodeLoadLogEvent");
        zzay zzayVar14 = new zzay();
        zzayVar14.zza(58);
        zzo = c2317bA14.b(zzayVar14.zzb()).a();
        b.C2317b c2317bA15 = b.a("onDeviceImageLabelCreateLogEvent");
        zzay zzayVar15 = new zzay();
        zzayVar15.zza(48);
        zzp = c2317bA15.b(zzayVar15.zzb()).a();
        b.C2317b c2317bA16 = b.a("onDeviceImageLabelLoadLogEvent");
        zzay zzayVar16 = new zzay();
        zzayVar16.zza(49);
        zzq = c2317bA16.b(zzayVar16.zzb()).a();
        b.C2317b c2317bA17 = b.a("onDeviceImageLabelDetectionLogEvent");
        zzay zzayVar17 = new zzay();
        zzayVar17.zza(18);
        zzr = c2317bA17.b(zzayVar17.zzb()).a();
        b.C2317b c2317bA18 = b.a("onDeviceObjectCreateLogEvent");
        zzay zzayVar18 = new zzay();
        zzayVar18.zza(26);
        zzs = c2317bA18.b(zzayVar18.zzb()).a();
        b.C2317b c2317bA19 = b.a("onDeviceObjectLoadLogEvent");
        zzay zzayVar19 = new zzay();
        zzayVar19.zza(27);
        zzt = c2317bA19.b(zzayVar19.zzb()).a();
        b.C2317b c2317bA20 = b.a("onDeviceObjectInferenceLogEvent");
        zzay zzayVar20 = new zzay();
        zzayVar20.zza(28);
        zzu = c2317bA20.b(zzayVar20.zzb()).a();
        b.C2317b c2317bA21 = b.a("onDevicePoseDetectionLogEvent");
        zzay zzayVar21 = new zzay();
        zzayVar21.zza(44);
        zzv = c2317bA21.b(zzayVar21.zzb()).a();
        b.C2317b c2317bA22 = b.a("onDeviceSegmentationLogEvent");
        zzay zzayVar22 = new zzay();
        zzayVar22.zza(45);
        zzw = c2317bA22.b(zzayVar22.zzb()).a();
        b.C2317b c2317bA23 = b.a("onDeviceSmartReplyLogEvent");
        zzay zzayVar23 = new zzay();
        zzayVar23.zza(19);
        zzx = c2317bA23.b(zzayVar23.zzb()).a();
        b.C2317b c2317bA24 = b.a("onDeviceLanguageIdentificationLogEvent");
        zzay zzayVar24 = new zzay();
        zzayVar24.zza(21);
        zzy = c2317bA24.b(zzayVar24.zzb()).a();
        b.C2317b c2317bA25 = b.a("onDeviceTranslationLogEvent");
        zzay zzayVar25 = new zzay();
        zzayVar25.zza(22);
        zzz = c2317bA25.b(zzayVar25.zzb()).a();
        b.C2317b c2317bA26 = b.a("cloudFaceDetectionLogEvent");
        zzay zzayVar26 = new zzay();
        zzayVar26.zza(8);
        zzA = c2317bA26.b(zzayVar26.zzb()).a();
        b.C2317b c2317bA27 = b.a("cloudCropHintDetectionLogEvent");
        zzay zzayVar27 = new zzay();
        zzayVar27.zza(9);
        zzB = c2317bA27.b(zzayVar27.zzb()).a();
        b.C2317b c2317bA28 = b.a("cloudDocumentTextDetectionLogEvent");
        zzay zzayVar28 = new zzay();
        zzayVar28.zza(10);
        zzC = c2317bA28.b(zzayVar28.zzb()).a();
        b.C2317b c2317bA29 = b.a("cloudImagePropertiesDetectionLogEvent");
        zzay zzayVar29 = new zzay();
        zzayVar29.zza(11);
        zzD = c2317bA29.b(zzayVar29.zzb()).a();
        b.C2317b c2317bA30 = b.a("cloudImageLabelDetectionLogEvent");
        zzay zzayVar30 = new zzay();
        zzayVar30.zza(12);
        zzE = c2317bA30.b(zzayVar30.zzb()).a();
        b.C2317b c2317bA31 = b.a("cloudLandmarkDetectionLogEvent");
        zzay zzayVar31 = new zzay();
        zzayVar31.zza(13);
        zzF = c2317bA31.b(zzayVar31.zzb()).a();
        b.C2317b c2317bA32 = b.a("cloudLogoDetectionLogEvent");
        zzay zzayVar32 = new zzay();
        zzayVar32.zza(14);
        zzG = c2317bA32.b(zzayVar32.zzb()).a();
        b.C2317b c2317bA33 = b.a("cloudSafeSearchDetectionLogEvent");
        zzay zzayVar33 = new zzay();
        zzayVar33.zza(15);
        zzH = c2317bA33.b(zzayVar33.zzb()).a();
        b.C2317b c2317bA34 = b.a("cloudTextDetectionLogEvent");
        zzay zzayVar34 = new zzay();
        zzayVar34.zza(16);
        zzI = c2317bA34.b(zzayVar34.zzb()).a();
        b.C2317b c2317bA35 = b.a("cloudWebSearchDetectionLogEvent");
        zzay zzayVar35 = new zzay();
        zzayVar35.zza(17);
        zzJ = c2317bA35.b(zzayVar35.zzb()).a();
        b.C2317b c2317bA36 = b.a("automlImageLabelingCreateLogEvent");
        zzay zzayVar36 = new zzay();
        zzayVar36.zza(23);
        zzK = c2317bA36.b(zzayVar36.zzb()).a();
        b.C2317b c2317bA37 = b.a("automlImageLabelingLoadLogEvent");
        zzay zzayVar37 = new zzay();
        zzayVar37.zza(24);
        zzL = c2317bA37.b(zzayVar37.zzb()).a();
        b.C2317b c2317bA38 = b.a("automlImageLabelingInferenceLogEvent");
        zzay zzayVar38 = new zzay();
        zzayVar38.zza(25);
        zzM = c2317bA38.b(zzayVar38.zzb()).a();
        b.C2317b c2317bA39 = b.a("isModelDownloadedLogEvent");
        zzay zzayVar39 = new zzay();
        zzayVar39.zza(39);
        zzN = c2317bA39.b(zzayVar39.zzb()).a();
        b.C2317b c2317bA40 = b.a("deleteModelLogEvent");
        zzay zzayVar40 = new zzay();
        zzayVar40.zza(40);
        zzO = c2317bA40.b(zzayVar40.zzb()).a();
        b.C2317b c2317bA41 = b.a("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzay zzayVar41 = new zzay();
        zzayVar41.zza(30);
        zzP = c2317bA41.b(zzayVar41.zzb()).a();
        b.C2317b c2317bA42 = b.a("aggregatedCustomModelInferenceLogEvent");
        zzay zzayVar42 = new zzay();
        zzayVar42.zza(31);
        zzQ = c2317bA42.b(zzayVar42.zzb()).a();
        b.C2317b c2317bA43 = b.a("aggregatedOnDeviceFaceDetectionLogEvent");
        zzay zzayVar43 = new zzay();
        zzayVar43.zza(32);
        zzR = c2317bA43.b(zzayVar43.zzb()).a();
        b.C2317b c2317bA44 = b.a("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzay zzayVar44 = new zzay();
        zzayVar44.zza(33);
        zzS = c2317bA44.b(zzayVar44.zzb()).a();
        b.C2317b c2317bA45 = b.a("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzay zzayVar45 = new zzay();
        zzayVar45.zza(34);
        zzT = c2317bA45.b(zzayVar45.zzb()).a();
        b.C2317b c2317bA46 = b.a("aggregatedOnDeviceObjectInferenceLogEvent");
        zzay zzayVar46 = new zzay();
        zzayVar46.zza(35);
        zzU = c2317bA46.b(zzayVar46.zzb()).a();
        b.C2317b c2317bA47 = b.a("aggregatedOnDeviceTextDetectionLogEvent");
        zzay zzayVar47 = new zzay();
        zzayVar47.zza(36);
        zzV = c2317bA47.b(zzayVar47.zzb()).a();
        b.C2317b c2317bA48 = b.a("aggregatedOnDevicePoseDetectionLogEvent");
        zzay zzayVar48 = new zzay();
        zzayVar48.zza(46);
        zzW = c2317bA48.b(zzayVar48.zzb()).a();
        b.C2317b c2317bA49 = b.a("aggregatedOnDeviceSegmentationLogEvent");
        zzay zzayVar49 = new zzay();
        zzayVar49.zza(47);
        zzX = c2317bA49.b(zzayVar49.zzb()).a();
        b.C2317b c2317bA50 = b.a("pipelineAccelerationInferenceEvents");
        zzay zzayVar50 = new zzay();
        zzayVar50.zza(69);
        zzY = c2317bA50.b(zzayVar50.zzb()).a();
        b.C2317b c2317bA51 = b.a("remoteConfigLogEvent");
        zzay zzayVar51 = new zzay();
        zzayVar51.zza(42);
        zzZ = c2317bA51.b(zzayVar51.zzb()).a();
        b.C2317b c2317bA52 = b.a("inputImageConstructionLogEvent");
        zzay zzayVar52 = new zzay();
        zzayVar52.zza(50);
        zzaa = c2317bA52.b(zzayVar52.zzb()).a();
        b.C2317b c2317bA53 = b.a("leakedHandleEvent");
        zzay zzayVar53 = new zzay();
        zzayVar53.zza(51);
        zzab = c2317bA53.b(zzayVar53.zzb()).a();
        b.C2317b c2317bA54 = b.a("cameraSourceLogEvent");
        zzay zzayVar54 = new zzay();
        zzayVar54.zza(52);
        zzac = c2317bA54.b(zzayVar54.zzb()).a();
        b.C2317b c2317bA55 = b.a("imageLabelOptionalModuleLogEvent");
        zzay zzayVar55 = new zzay();
        zzayVar55.zza(53);
        zzad = c2317bA55.b(zzayVar55.zzb()).a();
        b.C2317b c2317bA56 = b.a("languageIdentificationOptionalModuleLogEvent");
        zzay zzayVar56 = new zzay();
        zzayVar56.zza(54);
        zzae = c2317bA56.b(zzayVar56.zzb()).a();
        b.C2317b c2317bA57 = b.a("faceDetectionOptionalModuleLogEvent");
        zzay zzayVar57 = new zzay();
        zzayVar57.zza(60);
        zzaf = c2317bA57.b(zzayVar57.zzb()).a();
        b.C2317b c2317bA58 = b.a("documentDetectionOptionalModuleLogEvent");
        zzay zzayVar58 = new zzay();
        zzayVar58.zza(85);
        zzag = c2317bA58.b(zzayVar58.zzb()).a();
        b.C2317b c2317bA59 = b.a("documentCroppingOptionalModuleLogEvent");
        zzay zzayVar59 = new zzay();
        zzayVar59.zza(86);
        zzah = c2317bA59.b(zzayVar59.zzb()).a();
        b.C2317b c2317bA60 = b.a("documentEnhancementOptionalModuleLogEvent");
        zzay zzayVar60 = new zzay();
        zzayVar60.zza(87);
        zzai = c2317bA60.b(zzayVar60.zzb()).a();
        b.C2317b c2317bA61 = b.a("nlClassifierOptionalModuleLogEvent");
        zzay zzayVar61 = new zzay();
        zzayVar61.zza(55);
        zzaj = c2317bA61.b(zzayVar61.zzb()).a();
        b.C2317b c2317bA62 = b.a("nlClassifierClientLibraryLogEvent");
        zzay zzayVar62 = new zzay();
        zzayVar62.zza(56);
        zzak = c2317bA62.b(zzayVar62.zzb()).a();
        b.C2317b c2317bA63 = b.a("accelerationAllowlistLogEvent");
        zzay zzayVar63 = new zzay();
        zzayVar63.zza(57);
        zzal = c2317bA63.b(zzayVar63.zzb()).a();
        b.C2317b c2317bA64 = b.a("toxicityDetectionCreateEvent");
        zzay zzayVar64 = new zzay();
        zzayVar64.zza(62);
        zzam = c2317bA64.b(zzayVar64.zzb()).a();
        b.C2317b c2317bA65 = b.a("toxicityDetectionLoadEvent");
        zzay zzayVar65 = new zzay();
        zzayVar65.zza(63);
        zzan = c2317bA65.b(zzayVar65.zzb()).a();
        b.C2317b c2317bA66 = b.a("toxicityDetectionInferenceEvent");
        zzay zzayVar66 = new zzay();
        zzayVar66.zza(64);
        zzao = c2317bA66.b(zzayVar66.zzb()).a();
        b.C2317b c2317bA67 = b.a("barcodeDetectionOptionalModuleLogEvent");
        zzay zzayVar67 = new zzay();
        zzayVar67.zza(65);
        zzap = c2317bA67.b(zzayVar67.zzb()).a();
        b.C2317b c2317bA68 = b.a("customImageLabelOptionalModuleLogEvent");
        zzay zzayVar68 = new zzay();
        zzayVar68.zza(66);
        zzaq = c2317bA68.b(zzayVar68.zzb()).a();
        b.C2317b c2317bA69 = b.a("codeScannerScanApiEvent");
        zzay zzayVar69 = new zzay();
        zzayVar69.zza(67);
        zzar = c2317bA69.b(zzayVar69.zzb()).a();
        b.C2317b c2317bA70 = b.a("codeScannerOptionalModuleEvent");
        zzay zzayVar70 = new zzay();
        zzayVar70.zza(68);
        zzas = c2317bA70.b(zzayVar70.zzb()).a();
        b.C2317b c2317bA71 = b.a("onDeviceExplicitContentCreateLogEvent");
        zzay zzayVar71 = new zzay();
        zzayVar71.zza(70);
        zzat = c2317bA71.b(zzayVar71.zzb()).a();
        b.C2317b c2317bA72 = b.a("onDeviceExplicitContentLoadLogEvent");
        zzay zzayVar72 = new zzay();
        zzayVar72.zza(71);
        zzau = c2317bA72.b(zzayVar72.zzb()).a();
        b.C2317b c2317bA73 = b.a("onDeviceExplicitContentInferenceLogEvent");
        zzay zzayVar73 = new zzay();
        zzayVar73.zza(72);
        zzav = c2317bA73.b(zzayVar73.zzb()).a();
        b.C2317b c2317bA74 = b.a("aggregatedOnDeviceExplicitContentLogEvent");
        zzay zzayVar74 = new zzay();
        zzayVar74.zza(73);
        zzaw = c2317bA74.b(zzayVar74.zzb()).a();
        b.C2317b c2317bA75 = b.a("onDeviceFaceMeshCreateLogEvent");
        zzay zzayVar75 = new zzay();
        zzayVar75.zza(74);
        zzax = c2317bA75.b(zzayVar75.zzb()).a();
        b.C2317b c2317bA76 = b.a("onDeviceFaceMeshLoadLogEvent");
        zzay zzayVar76 = new zzay();
        zzayVar76.zza(75);
        zzay = c2317bA76.b(zzayVar76.zzb()).a();
        b.C2317b c2317bA77 = b.a("onDeviceFaceMeshLogEvent");
        zzay zzayVar77 = new zzay();
        zzayVar77.zza(76);
        zzaz = c2317bA77.b(zzayVar77.zzb()).a();
        b.C2317b c2317bA78 = b.a("aggregatedOnDeviceFaceMeshLogEvent");
        zzay zzayVar78 = new zzay();
        zzayVar78.zza(77);
        zzaA = c2317bA78.b(zzayVar78.zzb()).a();
        b.C2317b c2317bA79 = b.a("smartReplyOptionalModuleLogEvent");
        zzay zzayVar79 = new zzay();
        zzayVar79.zza(78);
        zzaB = c2317bA79.b(zzayVar79.zzb()).a();
        b.C2317b c2317bA80 = b.a("textDetectionOptionalModuleLogEvent");
        zzay zzayVar80 = new zzay();
        zzayVar80.zza(80);
        zzaC = c2317bA80.b(zzayVar80.zzb()).a();
        b.C2317b c2317bA81 = b.a("onDeviceImageQualityAnalysisCreateLogEvent");
        zzay zzayVar81 = new zzay();
        zzayVar81.zza(81);
        zzaD = c2317bA81.b(zzayVar81.zzb()).a();
        b.C2317b c2317bA82 = b.a("onDeviceImageQualityAnalysisLoadLogEvent");
        zzay zzayVar82 = new zzay();
        zzayVar82.zza(82);
        zzaE = c2317bA82.b(zzayVar82.zzb()).a();
        b.C2317b c2317bA83 = b.a("onDeviceImageQualityAnalysisLogEvent");
        zzay zzayVar83 = new zzay();
        zzayVar83.zza(83);
        zzaF = c2317bA83.b(zzayVar83.zzb()).a();
        b.C2317b c2317bA84 = b.a("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zzay zzayVar84 = new zzay();
        zzayVar84.zza(84);
        zzaG = c2317bA84.b(zzayVar84.zzb()).a();
        b.C2317b c2317bA85 = b.a("imageQualityAnalysisOptionalModuleLogEvent");
        zzay zzayVar85 = new zzay();
        zzayVar85.zza(88);
        zzaH = c2317bA85.b(zzayVar85.zzb()).a();
        b.C2317b c2317bA86 = b.a("imageCaptioningOptionalModuleLogEvent");
        zzay zzayVar86 = new zzay();
        zzayVar86.zza(89);
        zzaI = c2317bA86.b(zzayVar86.zzb()).a();
        b.C2317b c2317bA87 = b.a("onDeviceImageCaptioningCreateLogEvent");
        zzay zzayVar87 = new zzay();
        zzayVar87.zza(90);
        zzaJ = c2317bA87.b(zzayVar87.zzb()).a();
        b.C2317b c2317bA88 = b.a("onDeviceImageCaptioningLoadLogEvent");
        zzay zzayVar88 = new zzay();
        zzayVar88.zza(91);
        zzaK = c2317bA88.b(zzayVar88.zzb()).a();
        b.C2317b c2317bA89 = b.a("onDeviceImageCaptioningInferenceLogEvent");
        zzay zzayVar89 = new zzay();
        zzayVar89.zza(92);
        zzaL = c2317bA89.b(zzayVar89.zzb()).a();
        b.C2317b c2317bA90 = b.a("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zzay zzayVar90 = new zzay();
        zzayVar90.zza(93);
        zzaM = c2317bA90.b(zzayVar90.zzb()).a();
        b.C2317b c2317bA91 = b.a("onDeviceDocumentDetectionCreateLogEvent");
        zzay zzayVar91 = new zzay();
        zzayVar91.zza(94);
        zzaN = c2317bA91.b(zzayVar91.zzb()).a();
        b.C2317b c2317bA92 = b.a("onDeviceDocumentDetectionLoadLogEvent");
        zzay zzayVar92 = new zzay();
        zzayVar92.zza(95);
        zzaO = c2317bA92.b(zzayVar92.zzb()).a();
        b.C2317b c2317bA93 = b.a("onDeviceDocumentDetectionLogEvent");
        zzay zzayVar93 = new zzay();
        zzayVar93.zza(96);
        zzaP = c2317bA93.b(zzayVar93.zzb()).a();
        b.C2317b c2317bA94 = b.a("aggregatedOnDeviceDocumentDetectionLogEvent");
        zzay zzayVar94 = new zzay();
        zzayVar94.zza(97);
        zzaQ = c2317bA94.b(zzayVar94.zzb()).a();
        b.C2317b c2317bA95 = b.a("onDeviceDocumentCroppingCreateLogEvent");
        zzay zzayVar95 = new zzay();
        zzayVar95.zza(98);
        zzaR = c2317bA95.b(zzayVar95.zzb()).a();
        b.C2317b c2317bA96 = b.a("onDeviceDocumentCroppingLoadLogEvent");
        zzay zzayVar96 = new zzay();
        zzayVar96.zza(99);
        zzaS = c2317bA96.b(zzayVar96.zzb()).a();
        b.C2317b c2317bA97 = b.a("onDeviceDocumentCroppingLogEvent");
        zzay zzayVar97 = new zzay();
        zzayVar97.zza(100);
        zzaT = c2317bA97.b(zzayVar97.zzb()).a();
        b.C2317b c2317bA98 = b.a("aggregatedOnDeviceDocumentCroppingLogEvent");
        zzay zzayVar98 = new zzay();
        zzayVar98.zza(101);
        zzaU = c2317bA98.b(zzayVar98.zzb()).a();
        b.C2317b c2317bA99 = b.a("onDeviceDocumentEnhancementCreateLogEvent");
        zzay zzayVar99 = new zzay();
        zzayVar99.zza(102);
        zzaV = c2317bA99.b(zzayVar99.zzb()).a();
        b.C2317b c2317bA100 = b.a("onDeviceDocumentEnhancementLoadLogEvent");
        zzay zzayVar100 = new zzay();
        zzayVar100.zza(103);
        zzaW = c2317bA100.b(zzayVar100.zzb()).a();
        b.C2317b c2317bA101 = b.a("onDeviceDocumentEnhancementLogEvent");
        zzay zzayVar101 = new zzay();
        zzayVar101.zza(104);
        zzaX = c2317bA101.b(zzayVar101.zzb()).a();
        b.C2317b c2317bA102 = b.a("aggregatedOnDeviceDocumentEnhancementLogEvent");
        zzay zzayVar102 = new zzay();
        zzayVar102.zza(105);
        zzaY = c2317bA102.b(zzayVar102.zzb()).a();
        b.C2317b c2317bA103 = b.a("scannerAutoZoomEvent");
        zzay zzayVar103 = new zzay();
        zzayVar103.zza(106);
        zzaZ = c2317bA103.b(zzayVar103.zzb()).a();
        b.C2317b c2317bA104 = b.a("lowLightAutoExposureComputationEvent");
        zzay zzayVar104 = new zzay();
        zzayVar104.zza(107);
        zzba = c2317bA104.b(zzayVar104.zzb()).a();
        b.C2317b c2317bA105 = b.a("lowLightFrameProcessEvent");
        zzay zzayVar105 = new zzay();
        zzayVar105.zza(108);
        zzbb = c2317bA105.b(zzayVar105.zzb()).a();
        b.C2317b c2317bA106 = b.a("lowLightSceneDetectionEvent");
        zzay zzayVar106 = new zzay();
        zzayVar106.zza(109);
        zzbc = c2317bA106.b(zzayVar106.zzb()).a();
        b.C2317b c2317bA107 = b.a("onDeviceStainRemovalLogEvent");
        zzay zzayVar107 = new zzay();
        zzayVar107.zza(110);
        zzbd = c2317bA107.b(zzayVar107.zzb()).a();
        b.C2317b c2317bA108 = b.a("aggregatedOnDeviceStainRemovalLogEvent");
        zzay zzayVar108 = new zzay();
        zzayVar108.zza(111);
        zzbe = c2317bA108.b(zzayVar108.zzb()).a();
        b.C2317b c2317bA109 = b.a("stainRemovalOptionalModuleLogEvent");
        zzay zzayVar109 = new zzay();
        zzayVar109.zza(112);
        zzbf = c2317bA109.b(zzayVar109.zzb()).a();
        b.C2317b c2317bA110 = b.a("onDeviceShadowRemovalLogEvent");
        zzay zzayVar110 = new zzay();
        zzayVar110.zza(113);
        zzbg = c2317bA110.b(zzayVar110.zzb()).a();
        b.C2317b c2317bA111 = b.a("aggregatedOnDeviceShadowRemovalLogEvent");
        zzay zzayVar111 = new zzay();
        zzayVar111.zza(114);
        zzbh = c2317bA111.b(zzayVar111.zzb()).a();
        b.C2317b c2317bA112 = b.a("shadowRemovalOptionalModuleLogEvent");
        zzay zzayVar112 = new zzay();
        zzayVar112.zza(115);
        zzbi = c2317bA112.b(zzayVar112.zzb()).a();
        b.C2317b c2317bA113 = b.a("onDeviceDigitalInkSegmentationLogEvent");
        zzay zzayVar113 = new zzay();
        zzayVar113.zza(116);
        zzbj = c2317bA113.b(zzayVar113.zzb()).a();
        b.C2317b c2317bA114 = b.a("onDeviceDocumentScannerStartLogEvent");
        zzay zzayVar114 = new zzay();
        zzayVar114.zza(117);
        zzbk = c2317bA114.b(zzayVar114.zzb()).a();
        b.C2317b c2317bA115 = b.a("onDeviceDocumentScannerFinishLogEvent");
        zzay zzayVar115 = new zzay();
        zzayVar115.zza(118);
        zzbl = c2317bA115.b(zzayVar115.zzb()).a();
        b.C2317b c2317bA116 = b.a("onDeviceDocumentScannerUiStartLogEvent");
        zzay zzayVar116 = new zzay();
        zzayVar116.zza(119);
        zzbm = c2317bA116.b(zzayVar116.zzb()).a();
        b.C2317b c2317bA117 = b.a("onDeviceDocumentScannerUiFinishLogEvent");
        zzay zzayVar117 = new zzay();
        zzayVar117.zza(120);
        zzbn = c2317bA117.b(zzayVar117.zzb()).a();
        b.C2317b c2317bA118 = b.a("documentScannerUiOptionalModuleSessionStartLogEvent");
        zzay zzayVar118 = new zzay();
        zzayVar118.zza(121);
        zzbo = c2317bA118.b(zzayVar118.zzb()).a();
        b.C2317b c2317bA119 = b.a("documentScannerUiOptionalModuleSessionFinishLogEvent");
        zzay zzayVar119 = new zzay();
        zzayVar119.zza(122);
        zzbp = c2317bA119.b(zzayVar119.zzb()).a();
        b.C2317b c2317bA120 = b.a("onDeviceDocumentScannerUiCreateLogEvent");
        zzay zzayVar120 = new zzay();
        zzayVar120.zza(123);
        zzbq = c2317bA120.b(zzayVar120.zzb()).a();
        b.C2317b c2317bA121 = b.a("onDeviceSubjectSegmentationCreateLogEvent");
        zzay zzayVar121 = new zzay();
        zzayVar121.zza(124);
        zzbr = c2317bA121.b(zzayVar121.zzb()).a();
        b.C2317b c2317bA122 = b.a("onDeviceSubjectSegmentationLoadLogEvent");
        zzay zzayVar122 = new zzay();
        zzayVar122.zza(125);
        zzbs = c2317bA122.b(zzayVar122.zzb()).a();
        b.C2317b c2317bA123 = b.a("onDeviceSubjectSegmentationInferenceLogEvent");
        zzay zzayVar123 = new zzay();
        zzayVar123.zza(126);
        zzbt = c2317bA123.b(zzayVar123.zzb()).a();
        b.C2317b c2317bA124 = b.a("aggregatedOnDeviceSubjectSegmentationLogEvent");
        zzay zzayVar124 = new zzay();
        zzayVar124.zza(127);
        zzbu = c2317bA124.b(zzayVar124.zzb()).a();
        b.C2317b c2317bA125 = b.a("subjectSegmentationOptionalModuleLogEvent");
        zzay zzayVar125 = new zzay();
        zzayVar125.zza(128);
        zzbv = c2317bA125.b(zzayVar125.zzb()).a();
        b.C2317b c2317bA126 = b.a("documentScannerUiModuleScreenViewEvent");
        zzay zzayVar126 = new zzay();
        zzayVar126.zza(EnumC4419g.SDK_ASSET_ILLUSTRATION_FORM_VALUE);
        zzbw = c2317bA126.b(zzayVar126.zzb()).a();
        b.C2317b c2317bA127 = b.a("documentScannerUiModuleScreenClickEvent");
        zzay zzayVar127 = new zzay();
        zzayVar127.zza(EnumC4419g.SDK_ASSET_ILLUSTRATION_CONSUMER_VALUE);
        zzbx = c2317bA127.b(zzayVar127.zzb()).a();
        b.C2317b c2317bA128 = b.a("documentScannerUiModuleScreenErrorEvent");
        zzay zzayVar128 = new zzay();
        zzayVar128.zza(131);
        zzby = c2317bA128.b(zzayVar128.zzb()).a();
    }

    private zzgp() {
    }

    @Override // rv.c
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) {
        zzmy zzmyVar = (zzmy) obj;
        d dVar = (d) obj2;
        dVar.add(zzb, zzmyVar.zzf());
        dVar.add(zzc, zzmyVar.zzd());
        dVar.add(zzd, (Object) null);
        dVar.add(zze, (Object) null);
        dVar.add(zzf, zzmyVar.zze());
        dVar.add(zzg, (Object) null);
        dVar.add(zzh, (Object) null);
        dVar.add(zzi, (Object) null);
        dVar.add(zzj, (Object) null);
        dVar.add(zzk, (Object) null);
        dVar.add(zzl, (Object) null);
        dVar.add(zzm, (Object) null);
        dVar.add(zzn, (Object) null);
        dVar.add(zzo, (Object) null);
        dVar.add(zzp, (Object) null);
        dVar.add(zzq, (Object) null);
        dVar.add(zzr, (Object) null);
        dVar.add(zzs, (Object) null);
        dVar.add(zzt, (Object) null);
        dVar.add(zzu, (Object) null);
        dVar.add(zzv, (Object) null);
        dVar.add(zzw, (Object) null);
        dVar.add(zzx, (Object) null);
        dVar.add(zzy, (Object) null);
        dVar.add(zzz, (Object) null);
        dVar.add(zzA, (Object) null);
        dVar.add(zzB, (Object) null);
        dVar.add(zzC, (Object) null);
        dVar.add(zzD, (Object) null);
        dVar.add(zzE, (Object) null);
        dVar.add(zzF, (Object) null);
        dVar.add(zzG, (Object) null);
        dVar.add(zzH, (Object) null);
        dVar.add(zzI, (Object) null);
        dVar.add(zzJ, (Object) null);
        dVar.add(zzK, (Object) null);
        dVar.add(zzL, (Object) null);
        dVar.add(zzM, (Object) null);
        dVar.add(zzN, zzmyVar.zzb());
        dVar.add(zzO, zzmyVar.zza());
        dVar.add(zzP, (Object) null);
        dVar.add(zzQ, (Object) null);
        dVar.add(zzR, (Object) null);
        dVar.add(zzS, (Object) null);
        dVar.add(zzT, (Object) null);
        dVar.add(zzU, (Object) null);
        dVar.add(zzV, (Object) null);
        dVar.add(zzW, (Object) null);
        dVar.add(zzX, (Object) null);
        dVar.add(zzY, (Object) null);
        dVar.add(zzZ, (Object) null);
        dVar.add(zzaa, (Object) null);
        dVar.add(zzab, zzmyVar.zzc());
        dVar.add(zzac, (Object) null);
        dVar.add(zzad, (Object) null);
        dVar.add(zzae, (Object) null);
        dVar.add(zzaf, (Object) null);
        dVar.add(zzag, (Object) null);
        dVar.add(zzah, (Object) null);
        dVar.add(zzai, (Object) null);
        dVar.add(zzaj, (Object) null);
        dVar.add(zzak, (Object) null);
        dVar.add(zzal, (Object) null);
        dVar.add(zzam, (Object) null);
        dVar.add(zzan, (Object) null);
        dVar.add(zzao, (Object) null);
        dVar.add(zzap, (Object) null);
        dVar.add(zzaq, (Object) null);
        dVar.add(zzar, (Object) null);
        dVar.add(zzas, (Object) null);
        dVar.add(zzat, (Object) null);
        dVar.add(zzau, (Object) null);
        dVar.add(zzav, (Object) null);
        dVar.add(zzaw, (Object) null);
        dVar.add(zzax, (Object) null);
        dVar.add(zzay, (Object) null);
        dVar.add(zzaz, (Object) null);
        dVar.add(zzaA, (Object) null);
        dVar.add(zzaB, (Object) null);
        dVar.add(zzaC, (Object) null);
        dVar.add(zzaD, (Object) null);
        dVar.add(zzaE, (Object) null);
        dVar.add(zzaF, (Object) null);
        dVar.add(zzaG, (Object) null);
        dVar.add(zzaH, (Object) null);
        dVar.add(zzaI, (Object) null);
        dVar.add(zzaJ, (Object) null);
        dVar.add(zzaK, (Object) null);
        dVar.add(zzaL, (Object) null);
        dVar.add(zzaM, (Object) null);
        dVar.add(zzaN, (Object) null);
        dVar.add(zzaO, (Object) null);
        dVar.add(zzaP, (Object) null);
        dVar.add(zzaQ, (Object) null);
        dVar.add(zzaR, (Object) null);
        dVar.add(zzaS, (Object) null);
        dVar.add(zzaT, (Object) null);
        dVar.add(zzaU, (Object) null);
        dVar.add(zzaV, (Object) null);
        dVar.add(zzaW, (Object) null);
        dVar.add(zzaX, (Object) null);
        dVar.add(zzaY, (Object) null);
        dVar.add(zzaZ, (Object) null);
        dVar.add(zzba, (Object) null);
        dVar.add(zzbb, (Object) null);
        dVar.add(zzbc, (Object) null);
        dVar.add(zzbd, (Object) null);
        dVar.add(zzbe, (Object) null);
        dVar.add(zzbf, (Object) null);
        dVar.add(zzbg, (Object) null);
        dVar.add(zzbh, (Object) null);
        dVar.add(zzbi, (Object) null);
        dVar.add(zzbj, (Object) null);
        dVar.add(zzbk, (Object) null);
        dVar.add(zzbl, (Object) null);
        dVar.add(zzbm, (Object) null);
        dVar.add(zzbn, (Object) null);
        dVar.add(zzbo, (Object) null);
        dVar.add(zzbp, (Object) null);
        dVar.add(zzbq, (Object) null);
        dVar.add(zzbr, (Object) null);
        dVar.add(zzbs, (Object) null);
        dVar.add(zzbt, (Object) null);
        dVar.add(zzbu, (Object) null);
        dVar.add(zzbv, (Object) null);
        dVar.add(zzbw, (Object) null);
        dVar.add(zzbx, (Object) null);
        dVar.add(zzby, (Object) null);
    }
}
