package com.google.android.gms.internal.mlkit_vision_barcode;

import com.plaid.internal.EnumC4419g;
import rv.b;
import rv.c;
import rv.d;

/* JADX INFO: loaded from: classes5.dex */
final class zzkv implements c {
    private static final b zzA;
    private static final b zzB;
    private static final b zzC;
    private static final b zzD;
    private static final b zzE;
    private static final b zzF;
    private static final b zzG;
    private static final b zzH;
    private static final b zzI;
    private static final b zzJ;
    private static final b zzK;
    private static final b zzL;
    private static final b zzM;
    private static final b zzN;
    private static final b zzO;
    private static final b zzP;
    private static final b zzQ;
    private static final b zzR;
    private static final b zzS;
    private static final b zzT;
    private static final b zzU;
    private static final b zzV;
    private static final b zzW;
    private static final b zzX;
    private static final b zzY;
    private static final b zzZ;
    static final zzkv zza = new zzkv();
    private static final b zzaA;
    private static final b zzaB;
    private static final b zzaC;
    private static final b zzaD;
    private static final b zzaE;
    private static final b zzaF;
    private static final b zzaG;
    private static final b zzaH;
    private static final b zzaI;
    private static final b zzaJ;
    private static final b zzaK;
    private static final b zzaL;
    private static final b zzaM;
    private static final b zzaN;
    private static final b zzaO;
    private static final b zzaP;
    private static final b zzaQ;
    private static final b zzaR;
    private static final b zzaS;
    private static final b zzaT;
    private static final b zzaU;
    private static final b zzaV;
    private static final b zzaW;
    private static final b zzaX;
    private static final b zzaY;
    private static final b zzaZ;
    private static final b zzaa;
    private static final b zzab;
    private static final b zzac;
    private static final b zzad;
    private static final b zzae;
    private static final b zzaf;
    private static final b zzag;
    private static final b zzah;
    private static final b zzai;
    private static final b zzaj;
    private static final b zzak;
    private static final b zzal;
    private static final b zzam;
    private static final b zzan;
    private static final b zzao;
    private static final b zzap;
    private static final b zzaq;
    private static final b zzar;
    private static final b zzas;
    private static final b zzat;
    private static final b zzau;
    private static final b zzav;
    private static final b zzaw;
    private static final b zzax;
    private static final b zzay;
    private static final b zzaz;
    private static final b zzb;
    private static final b zzba;
    private static final b zzbb;
    private static final b zzbc;
    private static final b zzbd;
    private static final b zzbe;
    private static final b zzbf;
    private static final b zzbg;
    private static final b zzbh;
    private static final b zzbi;
    private static final b zzbj;
    private static final b zzbk;
    private static final b zzbl;
    private static final b zzbm;
    private static final b zzbn;
    private static final b zzbo;
    private static final b zzbp;
    private static final b zzbq;
    private static final b zzbr;
    private static final b zzbs;
    private static final b zzbt;
    private static final b zzbu;
    private static final b zzbv;
    private static final b zzbw;
    private static final b zzbx;
    private static final b zzby;
    private static final b zzc;
    private static final b zzd;
    private static final b zze;
    private static final b zzf;
    private static final b zzg;
    private static final b zzh;
    private static final b zzi;
    private static final b zzj;
    private static final b zzk;
    private static final b zzl;
    private static final b zzm;
    private static final b zzn;
    private static final b zzo;
    private static final b zzp;
    private static final b zzq;
    private static final b zzr;
    private static final b zzs;
    private static final b zzt;
    private static final b zzu;
    private static final b zzv;
    private static final b zzw;
    private static final b zzx;
    private static final b zzy;
    private static final b zzz;

    static {
        b.C2317b c2317bA = b.a("systemInfo");
        zzfa zzfaVar = new zzfa();
        zzfaVar.zza(1);
        zzb = c2317bA.b(zzfaVar.zzb()).a();
        b.C2317b c2317bA2 = b.a("eventName");
        zzfa zzfaVar2 = new zzfa();
        zzfaVar2.zza(2);
        zzc = c2317bA2.b(zzfaVar2.zzb()).a();
        b.C2317b c2317bA3 = b.a("isThickClient");
        zzfa zzfaVar3 = new zzfa();
        zzfaVar3.zza(37);
        zzd = c2317bA3.b(zzfaVar3.zzb()).a();
        b.C2317b c2317bA4 = b.a("clientType");
        zzfa zzfaVar4 = new zzfa();
        zzfaVar4.zza(61);
        zze = c2317bA4.b(zzfaVar4.zzb()).a();
        b.C2317b c2317bA5 = b.a("modelDownloadLogEvent");
        zzfa zzfaVar5 = new zzfa();
        zzfaVar5.zza(3);
        zzf = c2317bA5.b(zzfaVar5.zzb()).a();
        b.C2317b c2317bA6 = b.a("customModelLoadLogEvent");
        zzfa zzfaVar6 = new zzfa();
        zzfaVar6.zza(20);
        zzg = c2317bA6.b(zzfaVar6.zzb()).a();
        b.C2317b c2317bA7 = b.a("customModelInferenceLogEvent");
        zzfa zzfaVar7 = new zzfa();
        zzfaVar7.zza(4);
        zzh = c2317bA7.b(zzfaVar7.zzb()).a();
        b.C2317b c2317bA8 = b.a("customModelCreateLogEvent");
        zzfa zzfaVar8 = new zzfa();
        zzfaVar8.zza(29);
        zzi = c2317bA8.b(zzfaVar8.zzb()).a();
        b.C2317b c2317bA9 = b.a("onDeviceFaceDetectionLogEvent");
        zzfa zzfaVar9 = new zzfa();
        zzfaVar9.zza(5);
        zzj = c2317bA9.b(zzfaVar9.zzb()).a();
        b.C2317b c2317bA10 = b.a("onDeviceFaceLoadLogEvent");
        zzfa zzfaVar10 = new zzfa();
        zzfaVar10.zza(59);
        zzk = c2317bA10.b(zzfaVar10.zzb()).a();
        b.C2317b c2317bA11 = b.a("onDeviceTextDetectionLogEvent");
        zzfa zzfaVar11 = new zzfa();
        zzfaVar11.zza(6);
        zzl = c2317bA11.b(zzfaVar11.zzb()).a();
        b.C2317b c2317bA12 = b.a("onDeviceTextDetectionLoadLogEvent");
        zzfa zzfaVar12 = new zzfa();
        zzfaVar12.zza(79);
        zzm = c2317bA12.b(zzfaVar12.zzb()).a();
        b.C2317b c2317bA13 = b.a("onDeviceBarcodeDetectionLogEvent");
        zzfa zzfaVar13 = new zzfa();
        zzfaVar13.zza(7);
        zzn = c2317bA13.b(zzfaVar13.zzb()).a();
        b.C2317b c2317bA14 = b.a("onDeviceBarcodeLoadLogEvent");
        zzfa zzfaVar14 = new zzfa();
        zzfaVar14.zza(58);
        zzo = c2317bA14.b(zzfaVar14.zzb()).a();
        b.C2317b c2317bA15 = b.a("onDeviceImageLabelCreateLogEvent");
        zzfa zzfaVar15 = new zzfa();
        zzfaVar15.zza(48);
        zzp = c2317bA15.b(zzfaVar15.zzb()).a();
        b.C2317b c2317bA16 = b.a("onDeviceImageLabelLoadLogEvent");
        zzfa zzfaVar16 = new zzfa();
        zzfaVar16.zza(49);
        zzq = c2317bA16.b(zzfaVar16.zzb()).a();
        b.C2317b c2317bA17 = b.a("onDeviceImageLabelDetectionLogEvent");
        zzfa zzfaVar17 = new zzfa();
        zzfaVar17.zza(18);
        zzr = c2317bA17.b(zzfaVar17.zzb()).a();
        b.C2317b c2317bA18 = b.a("onDeviceObjectCreateLogEvent");
        zzfa zzfaVar18 = new zzfa();
        zzfaVar18.zza(26);
        zzs = c2317bA18.b(zzfaVar18.zzb()).a();
        b.C2317b c2317bA19 = b.a("onDeviceObjectLoadLogEvent");
        zzfa zzfaVar19 = new zzfa();
        zzfaVar19.zza(27);
        zzt = c2317bA19.b(zzfaVar19.zzb()).a();
        b.C2317b c2317bA20 = b.a("onDeviceObjectInferenceLogEvent");
        zzfa zzfaVar20 = new zzfa();
        zzfaVar20.zza(28);
        zzu = c2317bA20.b(zzfaVar20.zzb()).a();
        b.C2317b c2317bA21 = b.a("onDevicePoseDetectionLogEvent");
        zzfa zzfaVar21 = new zzfa();
        zzfaVar21.zza(44);
        zzv = c2317bA21.b(zzfaVar21.zzb()).a();
        b.C2317b c2317bA22 = b.a("onDeviceSegmentationLogEvent");
        zzfa zzfaVar22 = new zzfa();
        zzfaVar22.zza(45);
        zzw = c2317bA22.b(zzfaVar22.zzb()).a();
        b.C2317b c2317bA23 = b.a("onDeviceSmartReplyLogEvent");
        zzfa zzfaVar23 = new zzfa();
        zzfaVar23.zza(19);
        zzx = c2317bA23.b(zzfaVar23.zzb()).a();
        b.C2317b c2317bA24 = b.a("onDeviceLanguageIdentificationLogEvent");
        zzfa zzfaVar24 = new zzfa();
        zzfaVar24.zza(21);
        zzy = c2317bA24.b(zzfaVar24.zzb()).a();
        b.C2317b c2317bA25 = b.a("onDeviceTranslationLogEvent");
        zzfa zzfaVar25 = new zzfa();
        zzfaVar25.zza(22);
        zzz = c2317bA25.b(zzfaVar25.zzb()).a();
        b.C2317b c2317bA26 = b.a("cloudFaceDetectionLogEvent");
        zzfa zzfaVar26 = new zzfa();
        zzfaVar26.zza(8);
        zzA = c2317bA26.b(zzfaVar26.zzb()).a();
        b.C2317b c2317bA27 = b.a("cloudCropHintDetectionLogEvent");
        zzfa zzfaVar27 = new zzfa();
        zzfaVar27.zza(9);
        zzB = c2317bA27.b(zzfaVar27.zzb()).a();
        b.C2317b c2317bA28 = b.a("cloudDocumentTextDetectionLogEvent");
        zzfa zzfaVar28 = new zzfa();
        zzfaVar28.zza(10);
        zzC = c2317bA28.b(zzfaVar28.zzb()).a();
        b.C2317b c2317bA29 = b.a("cloudImagePropertiesDetectionLogEvent");
        zzfa zzfaVar29 = new zzfa();
        zzfaVar29.zza(11);
        zzD = c2317bA29.b(zzfaVar29.zzb()).a();
        b.C2317b c2317bA30 = b.a("cloudImageLabelDetectionLogEvent");
        zzfa zzfaVar30 = new zzfa();
        zzfaVar30.zza(12);
        zzE = c2317bA30.b(zzfaVar30.zzb()).a();
        b.C2317b c2317bA31 = b.a("cloudLandmarkDetectionLogEvent");
        zzfa zzfaVar31 = new zzfa();
        zzfaVar31.zza(13);
        zzF = c2317bA31.b(zzfaVar31.zzb()).a();
        b.C2317b c2317bA32 = b.a("cloudLogoDetectionLogEvent");
        zzfa zzfaVar32 = new zzfa();
        zzfaVar32.zza(14);
        zzG = c2317bA32.b(zzfaVar32.zzb()).a();
        b.C2317b c2317bA33 = b.a("cloudSafeSearchDetectionLogEvent");
        zzfa zzfaVar33 = new zzfa();
        zzfaVar33.zza(15);
        zzH = c2317bA33.b(zzfaVar33.zzb()).a();
        b.C2317b c2317bA34 = b.a("cloudTextDetectionLogEvent");
        zzfa zzfaVar34 = new zzfa();
        zzfaVar34.zza(16);
        zzI = c2317bA34.b(zzfaVar34.zzb()).a();
        b.C2317b c2317bA35 = b.a("cloudWebSearchDetectionLogEvent");
        zzfa zzfaVar35 = new zzfa();
        zzfaVar35.zza(17);
        zzJ = c2317bA35.b(zzfaVar35.zzb()).a();
        b.C2317b c2317bA36 = b.a("automlImageLabelingCreateLogEvent");
        zzfa zzfaVar36 = new zzfa();
        zzfaVar36.zza(23);
        zzK = c2317bA36.b(zzfaVar36.zzb()).a();
        b.C2317b c2317bA37 = b.a("automlImageLabelingLoadLogEvent");
        zzfa zzfaVar37 = new zzfa();
        zzfaVar37.zza(24);
        zzL = c2317bA37.b(zzfaVar37.zzb()).a();
        b.C2317b c2317bA38 = b.a("automlImageLabelingInferenceLogEvent");
        zzfa zzfaVar38 = new zzfa();
        zzfaVar38.zza(25);
        zzM = c2317bA38.b(zzfaVar38.zzb()).a();
        b.C2317b c2317bA39 = b.a("isModelDownloadedLogEvent");
        zzfa zzfaVar39 = new zzfa();
        zzfaVar39.zza(39);
        zzN = c2317bA39.b(zzfaVar39.zzb()).a();
        b.C2317b c2317bA40 = b.a("deleteModelLogEvent");
        zzfa zzfaVar40 = new zzfa();
        zzfaVar40.zza(40);
        zzO = c2317bA40.b(zzfaVar40.zzb()).a();
        b.C2317b c2317bA41 = b.a("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzfa zzfaVar41 = new zzfa();
        zzfaVar41.zza(30);
        zzP = c2317bA41.b(zzfaVar41.zzb()).a();
        b.C2317b c2317bA42 = b.a("aggregatedCustomModelInferenceLogEvent");
        zzfa zzfaVar42 = new zzfa();
        zzfaVar42.zza(31);
        zzQ = c2317bA42.b(zzfaVar42.zzb()).a();
        b.C2317b c2317bA43 = b.a("aggregatedOnDeviceFaceDetectionLogEvent");
        zzfa zzfaVar43 = new zzfa();
        zzfaVar43.zza(32);
        zzR = c2317bA43.b(zzfaVar43.zzb()).a();
        b.C2317b c2317bA44 = b.a("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzfa zzfaVar44 = new zzfa();
        zzfaVar44.zza(33);
        zzS = c2317bA44.b(zzfaVar44.zzb()).a();
        b.C2317b c2317bA45 = b.a("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzfa zzfaVar45 = new zzfa();
        zzfaVar45.zza(34);
        zzT = c2317bA45.b(zzfaVar45.zzb()).a();
        b.C2317b c2317bA46 = b.a("aggregatedOnDeviceObjectInferenceLogEvent");
        zzfa zzfaVar46 = new zzfa();
        zzfaVar46.zza(35);
        zzU = c2317bA46.b(zzfaVar46.zzb()).a();
        b.C2317b c2317bA47 = b.a("aggregatedOnDeviceTextDetectionLogEvent");
        zzfa zzfaVar47 = new zzfa();
        zzfaVar47.zza(36);
        zzV = c2317bA47.b(zzfaVar47.zzb()).a();
        b.C2317b c2317bA48 = b.a("aggregatedOnDevicePoseDetectionLogEvent");
        zzfa zzfaVar48 = new zzfa();
        zzfaVar48.zza(46);
        zzW = c2317bA48.b(zzfaVar48.zzb()).a();
        b.C2317b c2317bA49 = b.a("aggregatedOnDeviceSegmentationLogEvent");
        zzfa zzfaVar49 = new zzfa();
        zzfaVar49.zza(47);
        zzX = c2317bA49.b(zzfaVar49.zzb()).a();
        b.C2317b c2317bA50 = b.a("pipelineAccelerationInferenceEvents");
        zzfa zzfaVar50 = new zzfa();
        zzfaVar50.zza(69);
        zzY = c2317bA50.b(zzfaVar50.zzb()).a();
        b.C2317b c2317bA51 = b.a("remoteConfigLogEvent");
        zzfa zzfaVar51 = new zzfa();
        zzfaVar51.zza(42);
        zzZ = c2317bA51.b(zzfaVar51.zzb()).a();
        b.C2317b c2317bA52 = b.a("inputImageConstructionLogEvent");
        zzfa zzfaVar52 = new zzfa();
        zzfaVar52.zza(50);
        zzaa = c2317bA52.b(zzfaVar52.zzb()).a();
        b.C2317b c2317bA53 = b.a("leakedHandleEvent");
        zzfa zzfaVar53 = new zzfa();
        zzfaVar53.zza(51);
        zzab = c2317bA53.b(zzfaVar53.zzb()).a();
        b.C2317b c2317bA54 = b.a("cameraSourceLogEvent");
        zzfa zzfaVar54 = new zzfa();
        zzfaVar54.zza(52);
        zzac = c2317bA54.b(zzfaVar54.zzb()).a();
        b.C2317b c2317bA55 = b.a("imageLabelOptionalModuleLogEvent");
        zzfa zzfaVar55 = new zzfa();
        zzfaVar55.zza(53);
        zzad = c2317bA55.b(zzfaVar55.zzb()).a();
        b.C2317b c2317bA56 = b.a("languageIdentificationOptionalModuleLogEvent");
        zzfa zzfaVar56 = new zzfa();
        zzfaVar56.zza(54);
        zzae = c2317bA56.b(zzfaVar56.zzb()).a();
        b.C2317b c2317bA57 = b.a("faceDetectionOptionalModuleLogEvent");
        zzfa zzfaVar57 = new zzfa();
        zzfaVar57.zza(60);
        zzaf = c2317bA57.b(zzfaVar57.zzb()).a();
        b.C2317b c2317bA58 = b.a("documentDetectionOptionalModuleLogEvent");
        zzfa zzfaVar58 = new zzfa();
        zzfaVar58.zza(85);
        zzag = c2317bA58.b(zzfaVar58.zzb()).a();
        b.C2317b c2317bA59 = b.a("documentCroppingOptionalModuleLogEvent");
        zzfa zzfaVar59 = new zzfa();
        zzfaVar59.zza(86);
        zzah = c2317bA59.b(zzfaVar59.zzb()).a();
        b.C2317b c2317bA60 = b.a("documentEnhancementOptionalModuleLogEvent");
        zzfa zzfaVar60 = new zzfa();
        zzfaVar60.zza(87);
        zzai = c2317bA60.b(zzfaVar60.zzb()).a();
        b.C2317b c2317bA61 = b.a("nlClassifierOptionalModuleLogEvent");
        zzfa zzfaVar61 = new zzfa();
        zzfaVar61.zza(55);
        zzaj = c2317bA61.b(zzfaVar61.zzb()).a();
        b.C2317b c2317bA62 = b.a("nlClassifierClientLibraryLogEvent");
        zzfa zzfaVar62 = new zzfa();
        zzfaVar62.zza(56);
        zzak = c2317bA62.b(zzfaVar62.zzb()).a();
        b.C2317b c2317bA63 = b.a("accelerationAllowlistLogEvent");
        zzfa zzfaVar63 = new zzfa();
        zzfaVar63.zza(57);
        zzal = c2317bA63.b(zzfaVar63.zzb()).a();
        b.C2317b c2317bA64 = b.a("toxicityDetectionCreateEvent");
        zzfa zzfaVar64 = new zzfa();
        zzfaVar64.zza(62);
        zzam = c2317bA64.b(zzfaVar64.zzb()).a();
        b.C2317b c2317bA65 = b.a("toxicityDetectionLoadEvent");
        zzfa zzfaVar65 = new zzfa();
        zzfaVar65.zza(63);
        zzan = c2317bA65.b(zzfaVar65.zzb()).a();
        b.C2317b c2317bA66 = b.a("toxicityDetectionInferenceEvent");
        zzfa zzfaVar66 = new zzfa();
        zzfaVar66.zza(64);
        zzao = c2317bA66.b(zzfaVar66.zzb()).a();
        b.C2317b c2317bA67 = b.a("barcodeDetectionOptionalModuleLogEvent");
        zzfa zzfaVar67 = new zzfa();
        zzfaVar67.zza(65);
        zzap = c2317bA67.b(zzfaVar67.zzb()).a();
        b.C2317b c2317bA68 = b.a("customImageLabelOptionalModuleLogEvent");
        zzfa zzfaVar68 = new zzfa();
        zzfaVar68.zza(66);
        zzaq = c2317bA68.b(zzfaVar68.zzb()).a();
        b.C2317b c2317bA69 = b.a("codeScannerScanApiEvent");
        zzfa zzfaVar69 = new zzfa();
        zzfaVar69.zza(67);
        zzar = c2317bA69.b(zzfaVar69.zzb()).a();
        b.C2317b c2317bA70 = b.a("codeScannerOptionalModuleEvent");
        zzfa zzfaVar70 = new zzfa();
        zzfaVar70.zza(68);
        zzas = c2317bA70.b(zzfaVar70.zzb()).a();
        b.C2317b c2317bA71 = b.a("onDeviceExplicitContentCreateLogEvent");
        zzfa zzfaVar71 = new zzfa();
        zzfaVar71.zza(70);
        zzat = c2317bA71.b(zzfaVar71.zzb()).a();
        b.C2317b c2317bA72 = b.a("onDeviceExplicitContentLoadLogEvent");
        zzfa zzfaVar72 = new zzfa();
        zzfaVar72.zza(71);
        zzau = c2317bA72.b(zzfaVar72.zzb()).a();
        b.C2317b c2317bA73 = b.a("onDeviceExplicitContentInferenceLogEvent");
        zzfa zzfaVar73 = new zzfa();
        zzfaVar73.zza(72);
        zzav = c2317bA73.b(zzfaVar73.zzb()).a();
        b.C2317b c2317bA74 = b.a("aggregatedOnDeviceExplicitContentLogEvent");
        zzfa zzfaVar74 = new zzfa();
        zzfaVar74.zza(73);
        zzaw = c2317bA74.b(zzfaVar74.zzb()).a();
        b.C2317b c2317bA75 = b.a("onDeviceFaceMeshCreateLogEvent");
        zzfa zzfaVar75 = new zzfa();
        zzfaVar75.zza(74);
        zzax = c2317bA75.b(zzfaVar75.zzb()).a();
        b.C2317b c2317bA76 = b.a("onDeviceFaceMeshLoadLogEvent");
        zzfa zzfaVar76 = new zzfa();
        zzfaVar76.zza(75);
        zzay = c2317bA76.b(zzfaVar76.zzb()).a();
        b.C2317b c2317bA77 = b.a("onDeviceFaceMeshLogEvent");
        zzfa zzfaVar77 = new zzfa();
        zzfaVar77.zza(76);
        zzaz = c2317bA77.b(zzfaVar77.zzb()).a();
        b.C2317b c2317bA78 = b.a("aggregatedOnDeviceFaceMeshLogEvent");
        zzfa zzfaVar78 = new zzfa();
        zzfaVar78.zza(77);
        zzaA = c2317bA78.b(zzfaVar78.zzb()).a();
        b.C2317b c2317bA79 = b.a("smartReplyOptionalModuleLogEvent");
        zzfa zzfaVar79 = new zzfa();
        zzfaVar79.zza(78);
        zzaB = c2317bA79.b(zzfaVar79.zzb()).a();
        b.C2317b c2317bA80 = b.a("textDetectionOptionalModuleLogEvent");
        zzfa zzfaVar80 = new zzfa();
        zzfaVar80.zza(80);
        zzaC = c2317bA80.b(zzfaVar80.zzb()).a();
        b.C2317b c2317bA81 = b.a("onDeviceImageQualityAnalysisCreateLogEvent");
        zzfa zzfaVar81 = new zzfa();
        zzfaVar81.zza(81);
        zzaD = c2317bA81.b(zzfaVar81.zzb()).a();
        b.C2317b c2317bA82 = b.a("onDeviceImageQualityAnalysisLoadLogEvent");
        zzfa zzfaVar82 = new zzfa();
        zzfaVar82.zza(82);
        zzaE = c2317bA82.b(zzfaVar82.zzb()).a();
        b.C2317b c2317bA83 = b.a("onDeviceImageQualityAnalysisLogEvent");
        zzfa zzfaVar83 = new zzfa();
        zzfaVar83.zza(83);
        zzaF = c2317bA83.b(zzfaVar83.zzb()).a();
        b.C2317b c2317bA84 = b.a("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zzfa zzfaVar84 = new zzfa();
        zzfaVar84.zza(84);
        zzaG = c2317bA84.b(zzfaVar84.zzb()).a();
        b.C2317b c2317bA85 = b.a("imageQualityAnalysisOptionalModuleLogEvent");
        zzfa zzfaVar85 = new zzfa();
        zzfaVar85.zza(88);
        zzaH = c2317bA85.b(zzfaVar85.zzb()).a();
        b.C2317b c2317bA86 = b.a("imageCaptioningOptionalModuleLogEvent");
        zzfa zzfaVar86 = new zzfa();
        zzfaVar86.zza(89);
        zzaI = c2317bA86.b(zzfaVar86.zzb()).a();
        b.C2317b c2317bA87 = b.a("onDeviceImageCaptioningCreateLogEvent");
        zzfa zzfaVar87 = new zzfa();
        zzfaVar87.zza(90);
        zzaJ = c2317bA87.b(zzfaVar87.zzb()).a();
        b.C2317b c2317bA88 = b.a("onDeviceImageCaptioningLoadLogEvent");
        zzfa zzfaVar88 = new zzfa();
        zzfaVar88.zza(91);
        zzaK = c2317bA88.b(zzfaVar88.zzb()).a();
        b.C2317b c2317bA89 = b.a("onDeviceImageCaptioningInferenceLogEvent");
        zzfa zzfaVar89 = new zzfa();
        zzfaVar89.zza(92);
        zzaL = c2317bA89.b(zzfaVar89.zzb()).a();
        b.C2317b c2317bA90 = b.a("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zzfa zzfaVar90 = new zzfa();
        zzfaVar90.zza(93);
        zzaM = c2317bA90.b(zzfaVar90.zzb()).a();
        b.C2317b c2317bA91 = b.a("onDeviceDocumentDetectionCreateLogEvent");
        zzfa zzfaVar91 = new zzfa();
        zzfaVar91.zza(94);
        zzaN = c2317bA91.b(zzfaVar91.zzb()).a();
        b.C2317b c2317bA92 = b.a("onDeviceDocumentDetectionLoadLogEvent");
        zzfa zzfaVar92 = new zzfa();
        zzfaVar92.zza(95);
        zzaO = c2317bA92.b(zzfaVar92.zzb()).a();
        b.C2317b c2317bA93 = b.a("onDeviceDocumentDetectionLogEvent");
        zzfa zzfaVar93 = new zzfa();
        zzfaVar93.zza(96);
        zzaP = c2317bA93.b(zzfaVar93.zzb()).a();
        b.C2317b c2317bA94 = b.a("aggregatedOnDeviceDocumentDetectionLogEvent");
        zzfa zzfaVar94 = new zzfa();
        zzfaVar94.zza(97);
        zzaQ = c2317bA94.b(zzfaVar94.zzb()).a();
        b.C2317b c2317bA95 = b.a("onDeviceDocumentCroppingCreateLogEvent");
        zzfa zzfaVar95 = new zzfa();
        zzfaVar95.zza(98);
        zzaR = c2317bA95.b(zzfaVar95.zzb()).a();
        b.C2317b c2317bA96 = b.a("onDeviceDocumentCroppingLoadLogEvent");
        zzfa zzfaVar96 = new zzfa();
        zzfaVar96.zza(99);
        zzaS = c2317bA96.b(zzfaVar96.zzb()).a();
        b.C2317b c2317bA97 = b.a("onDeviceDocumentCroppingLogEvent");
        zzfa zzfaVar97 = new zzfa();
        zzfaVar97.zza(100);
        zzaT = c2317bA97.b(zzfaVar97.zzb()).a();
        b.C2317b c2317bA98 = b.a("aggregatedOnDeviceDocumentCroppingLogEvent");
        zzfa zzfaVar98 = new zzfa();
        zzfaVar98.zza(101);
        zzaU = c2317bA98.b(zzfaVar98.zzb()).a();
        b.C2317b c2317bA99 = b.a("onDeviceDocumentEnhancementCreateLogEvent");
        zzfa zzfaVar99 = new zzfa();
        zzfaVar99.zza(102);
        zzaV = c2317bA99.b(zzfaVar99.zzb()).a();
        b.C2317b c2317bA100 = b.a("onDeviceDocumentEnhancementLoadLogEvent");
        zzfa zzfaVar100 = new zzfa();
        zzfaVar100.zza(103);
        zzaW = c2317bA100.b(zzfaVar100.zzb()).a();
        b.C2317b c2317bA101 = b.a("onDeviceDocumentEnhancementLogEvent");
        zzfa zzfaVar101 = new zzfa();
        zzfaVar101.zza(104);
        zzaX = c2317bA101.b(zzfaVar101.zzb()).a();
        b.C2317b c2317bA102 = b.a("aggregatedOnDeviceDocumentEnhancementLogEvent");
        zzfa zzfaVar102 = new zzfa();
        zzfaVar102.zza(105);
        zzaY = c2317bA102.b(zzfaVar102.zzb()).a();
        b.C2317b c2317bA103 = b.a("scannerAutoZoomEvent");
        zzfa zzfaVar103 = new zzfa();
        zzfaVar103.zza(106);
        zzaZ = c2317bA103.b(zzfaVar103.zzb()).a();
        b.C2317b c2317bA104 = b.a("lowLightAutoExposureComputationEvent");
        zzfa zzfaVar104 = new zzfa();
        zzfaVar104.zza(107);
        zzba = c2317bA104.b(zzfaVar104.zzb()).a();
        b.C2317b c2317bA105 = b.a("lowLightFrameProcessEvent");
        zzfa zzfaVar105 = new zzfa();
        zzfaVar105.zza(108);
        zzbb = c2317bA105.b(zzfaVar105.zzb()).a();
        b.C2317b c2317bA106 = b.a("lowLightSceneDetectionEvent");
        zzfa zzfaVar106 = new zzfa();
        zzfaVar106.zza(109);
        zzbc = c2317bA106.b(zzfaVar106.zzb()).a();
        b.C2317b c2317bA107 = b.a("onDeviceStainRemovalLogEvent");
        zzfa zzfaVar107 = new zzfa();
        zzfaVar107.zza(110);
        zzbd = c2317bA107.b(zzfaVar107.zzb()).a();
        b.C2317b c2317bA108 = b.a("aggregatedOnDeviceStainRemovalLogEvent");
        zzfa zzfaVar108 = new zzfa();
        zzfaVar108.zza(111);
        zzbe = c2317bA108.b(zzfaVar108.zzb()).a();
        b.C2317b c2317bA109 = b.a("stainRemovalOptionalModuleLogEvent");
        zzfa zzfaVar109 = new zzfa();
        zzfaVar109.zza(112);
        zzbf = c2317bA109.b(zzfaVar109.zzb()).a();
        b.C2317b c2317bA110 = b.a("onDeviceShadowRemovalLogEvent");
        zzfa zzfaVar110 = new zzfa();
        zzfaVar110.zza(113);
        zzbg = c2317bA110.b(zzfaVar110.zzb()).a();
        b.C2317b c2317bA111 = b.a("aggregatedOnDeviceShadowRemovalLogEvent");
        zzfa zzfaVar111 = new zzfa();
        zzfaVar111.zza(114);
        zzbh = c2317bA111.b(zzfaVar111.zzb()).a();
        b.C2317b c2317bA112 = b.a("shadowRemovalOptionalModuleLogEvent");
        zzfa zzfaVar112 = new zzfa();
        zzfaVar112.zza(115);
        zzbi = c2317bA112.b(zzfaVar112.zzb()).a();
        b.C2317b c2317bA113 = b.a("onDeviceDigitalInkSegmentationLogEvent");
        zzfa zzfaVar113 = new zzfa();
        zzfaVar113.zza(116);
        zzbj = c2317bA113.b(zzfaVar113.zzb()).a();
        b.C2317b c2317bA114 = b.a("onDeviceDocumentScannerStartLogEvent");
        zzfa zzfaVar114 = new zzfa();
        zzfaVar114.zza(117);
        zzbk = c2317bA114.b(zzfaVar114.zzb()).a();
        b.C2317b c2317bA115 = b.a("onDeviceDocumentScannerFinishLogEvent");
        zzfa zzfaVar115 = new zzfa();
        zzfaVar115.zza(118);
        zzbl = c2317bA115.b(zzfaVar115.zzb()).a();
        b.C2317b c2317bA116 = b.a("onDeviceDocumentScannerUiStartLogEvent");
        zzfa zzfaVar116 = new zzfa();
        zzfaVar116.zza(119);
        zzbm = c2317bA116.b(zzfaVar116.zzb()).a();
        b.C2317b c2317bA117 = b.a("onDeviceDocumentScannerUiFinishLogEvent");
        zzfa zzfaVar117 = new zzfa();
        zzfaVar117.zza(120);
        zzbn = c2317bA117.b(zzfaVar117.zzb()).a();
        b.C2317b c2317bA118 = b.a("documentScannerUiOptionalModuleSessionStartLogEvent");
        zzfa zzfaVar118 = new zzfa();
        zzfaVar118.zza(121);
        zzbo = c2317bA118.b(zzfaVar118.zzb()).a();
        b.C2317b c2317bA119 = b.a("documentScannerUiOptionalModuleSessionFinishLogEvent");
        zzfa zzfaVar119 = new zzfa();
        zzfaVar119.zza(122);
        zzbp = c2317bA119.b(zzfaVar119.zzb()).a();
        b.C2317b c2317bA120 = b.a("onDeviceDocumentScannerUiCreateLogEvent");
        zzfa zzfaVar120 = new zzfa();
        zzfaVar120.zza(123);
        zzbq = c2317bA120.b(zzfaVar120.zzb()).a();
        b.C2317b c2317bA121 = b.a("onDeviceSubjectSegmentationCreateLogEvent");
        zzfa zzfaVar121 = new zzfa();
        zzfaVar121.zza(124);
        zzbr = c2317bA121.b(zzfaVar121.zzb()).a();
        b.C2317b c2317bA122 = b.a("onDeviceSubjectSegmentationLoadLogEvent");
        zzfa zzfaVar122 = new zzfa();
        zzfaVar122.zza(125);
        zzbs = c2317bA122.b(zzfaVar122.zzb()).a();
        b.C2317b c2317bA123 = b.a("onDeviceSubjectSegmentationInferenceLogEvent");
        zzfa zzfaVar123 = new zzfa();
        zzfaVar123.zza(126);
        zzbt = c2317bA123.b(zzfaVar123.zzb()).a();
        b.C2317b c2317bA124 = b.a("aggregatedOnDeviceSubjectSegmentationLogEvent");
        zzfa zzfaVar124 = new zzfa();
        zzfaVar124.zza(127);
        zzbu = c2317bA124.b(zzfaVar124.zzb()).a();
        b.C2317b c2317bA125 = b.a("subjectSegmentationOptionalModuleLogEvent");
        zzfa zzfaVar125 = new zzfa();
        zzfaVar125.zza(128);
        zzbv = c2317bA125.b(zzfaVar125.zzb()).a();
        b.C2317b c2317bA126 = b.a("documentScannerUiModuleScreenViewEvent");
        zzfa zzfaVar126 = new zzfa();
        zzfaVar126.zza(EnumC4419g.SDK_ASSET_ILLUSTRATION_FORM_VALUE);
        zzbw = c2317bA126.b(zzfaVar126.zzb()).a();
        b.C2317b c2317bA127 = b.a("documentScannerUiModuleScreenClickEvent");
        zzfa zzfaVar127 = new zzfa();
        zzfaVar127.zza(EnumC4419g.SDK_ASSET_ILLUSTRATION_CONSUMER_VALUE);
        zzbx = c2317bA127.b(zzfaVar127.zzb()).a();
        b.C2317b c2317bA128 = b.a("documentScannerUiModuleScreenErrorEvent");
        zzfa zzfaVar128 = new zzfa();
        zzfaVar128.zza(131);
        zzby = c2317bA128.b(zzfaVar128.zzb()).a();
    }

    private zzkv() {
    }

    @Override // rv.c
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) {
        zzrf zzrfVar = (zzrf) obj;
        d dVar = (d) obj2;
        dVar.add(zzb, zzrfVar.zzg());
        dVar.add(zzc, zzrfVar.zzc());
        dVar.add(zzd, (Object) null);
        dVar.add(zze, zzrfVar.zzb());
        dVar.add(zzf, (Object) null);
        dVar.add(zzg, (Object) null);
        dVar.add(zzh, (Object) null);
        dVar.add(zzi, (Object) null);
        dVar.add(zzj, (Object) null);
        dVar.add(zzk, (Object) null);
        dVar.add(zzl, (Object) null);
        dVar.add(zzm, (Object) null);
        dVar.add(zzn, zzrfVar.zzd());
        dVar.add(zzo, zzrfVar.zze());
        dVar.add(zzp, (Object) null);
        dVar.add(zzq, (Object) null);
        dVar.add(zzr, (Object) null);
        dVar.add(zzs, (Object) null);
        dVar.add(zzt, (Object) null);
        dVar.add(zzu, (Object) null);
        dVar.add(zzv, (Object) null);
        dVar.add(zzw, (Object) null);
        dVar.add(zzx, (Object) null);
        dVar.add(zzy, (Object) null);
        dVar.add(zzz, (Object) null);
        dVar.add(zzA, (Object) null);
        dVar.add(zzB, (Object) null);
        dVar.add(zzC, (Object) null);
        dVar.add(zzD, (Object) null);
        dVar.add(zzE, (Object) null);
        dVar.add(zzF, (Object) null);
        dVar.add(zzG, (Object) null);
        dVar.add(zzH, (Object) null);
        dVar.add(zzI, (Object) null);
        dVar.add(zzJ, (Object) null);
        dVar.add(zzK, (Object) null);
        dVar.add(zzL, (Object) null);
        dVar.add(zzM, (Object) null);
        dVar.add(zzN, (Object) null);
        dVar.add(zzO, (Object) null);
        dVar.add(zzP, (Object) null);
        dVar.add(zzQ, (Object) null);
        dVar.add(zzR, (Object) null);
        dVar.add(zzS, zzrfVar.zza());
        dVar.add(zzT, (Object) null);
        dVar.add(zzU, (Object) null);
        dVar.add(zzV, (Object) null);
        dVar.add(zzW, (Object) null);
        dVar.add(zzX, (Object) null);
        dVar.add(zzY, (Object) null);
        dVar.add(zzZ, (Object) null);
        dVar.add(zzaa, (Object) null);
        dVar.add(zzab, (Object) null);
        dVar.add(zzac, (Object) null);
        dVar.add(zzad, (Object) null);
        dVar.add(zzae, (Object) null);
        dVar.add(zzaf, (Object) null);
        dVar.add(zzag, (Object) null);
        dVar.add(zzah, (Object) null);
        dVar.add(zzai, (Object) null);
        dVar.add(zzaj, (Object) null);
        dVar.add(zzak, (Object) null);
        dVar.add(zzal, (Object) null);
        dVar.add(zzam, (Object) null);
        dVar.add(zzan, (Object) null);
        dVar.add(zzao, (Object) null);
        dVar.add(zzap, (Object) null);
        dVar.add(zzaq, (Object) null);
        dVar.add(zzar, (Object) null);
        dVar.add(zzas, (Object) null);
        dVar.add(zzat, (Object) null);
        dVar.add(zzau, (Object) null);
        dVar.add(zzav, (Object) null);
        dVar.add(zzaw, (Object) null);
        dVar.add(zzax, (Object) null);
        dVar.add(zzay, (Object) null);
        dVar.add(zzaz, (Object) null);
        dVar.add(zzaA, (Object) null);
        dVar.add(zzaB, (Object) null);
        dVar.add(zzaC, (Object) null);
        dVar.add(zzaD, (Object) null);
        dVar.add(zzaE, (Object) null);
        dVar.add(zzaF, (Object) null);
        dVar.add(zzaG, (Object) null);
        dVar.add(zzaH, (Object) null);
        dVar.add(zzaI, (Object) null);
        dVar.add(zzaJ, (Object) null);
        dVar.add(zzaK, (Object) null);
        dVar.add(zzaL, (Object) null);
        dVar.add(zzaM, (Object) null);
        dVar.add(zzaN, (Object) null);
        dVar.add(zzaO, (Object) null);
        dVar.add(zzaP, (Object) null);
        dVar.add(zzaQ, (Object) null);
        dVar.add(zzaR, (Object) null);
        dVar.add(zzaS, (Object) null);
        dVar.add(zzaT, (Object) null);
        dVar.add(zzaU, (Object) null);
        dVar.add(zzaV, (Object) null);
        dVar.add(zzaW, (Object) null);
        dVar.add(zzaX, (Object) null);
        dVar.add(zzaY, (Object) null);
        dVar.add(zzaZ, zzrfVar.zzf());
        dVar.add(zzba, (Object) null);
        dVar.add(zzbb, (Object) null);
        dVar.add(zzbc, (Object) null);
        dVar.add(zzbd, (Object) null);
        dVar.add(zzbe, (Object) null);
        dVar.add(zzbf, (Object) null);
        dVar.add(zzbg, (Object) null);
        dVar.add(zzbh, (Object) null);
        dVar.add(zzbi, (Object) null);
        dVar.add(zzbj, (Object) null);
        dVar.add(zzbk, (Object) null);
        dVar.add(zzbl, (Object) null);
        dVar.add(zzbm, (Object) null);
        dVar.add(zzbn, (Object) null);
        dVar.add(zzbo, (Object) null);
        dVar.add(zzbp, (Object) null);
        dVar.add(zzbq, (Object) null);
        dVar.add(zzbr, (Object) null);
        dVar.add(zzbs, (Object) null);
        dVar.add(zzbt, (Object) null);
        dVar.add(zzbu, (Object) null);
        dVar.add(zzbv, (Object) null);
        dVar.add(zzbw, (Object) null);
        dVar.add(zzbx, (Object) null);
        dVar.add(zzby, (Object) null);
    }
}
